### ISSUE TITLE
Hey.

### ISSUE THREAD

**Issue by themaoci** [sailro/EscapeFromTarkov-Trainer#1]
Devs will propably don't even fix that ... Good find anyway didn't think about that aproach.
i found a glitch with pocket map with like 2000+ commits back at version 11.7.3333 .. its still not fixed. I even posted all things what they need to do to patch it out on their reddit ...

**Comment by fipso** [comment]
The did not fix it, but BE will flag you.
I built my own wallhack/esp using the same NLog bug.
Got banned after 3 days.

https://github.com/fipso/EST-Player-Item-ESP

**Comment by themaoci** [comment]
BE scans dll's btw ...

**Comment by petitfilou974** [comment]
so is this trainer detected by BE or it's not detected ?

**Comment by NoNameG0d** [comment]
@petitfilou974 It's detected dude, what do you think

**Comment by themaoci** [comment]
@PedroLuz89 have fun being BEd after 1-3 week's xD

**Comment by victorsena13** [comment]
can someone help me make this work on Just emu tarkov, i've zero knowledge in this plz

**Comment by fipso** [comment]
@ghost i have no idea weather this still works

**Comment by a1184132521** [comment]
> @鬼我不知道这是否仍然有效
I want to know how to use these codes, because it's a beginner or something

**Comment by dami-boop** [comment]
> can someone help me make this work on Just emu tarkov, i've zero knowledge in this plz

Not only are you bad at the game, but you also don't even know how to cheat when it's laid at your feet.
If you spent the time you are trying to cheat into actually playing the game you wouldn't need to cheat
