### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by Pandolphina** [sailro/EscapeFromTarkov-Trainer#10]
So, commands don't seem to work for me. I'm running SP-Tarkov. After some mild trial-and-error, the trainer loads, but commands to toggle anything don't work. Only things like help, status, and list work, the rest just say "NO SUCH COMMAND".

**Comment by sailro** [comment]
Hi

- Are you using a release or are you compiling yourself ?
- What is your EFT and sptarkov versions ?

**Comment by sailro** [comment]
Closing given no responses were given

**Comment by TonyStank1** [comment]
I have the same problem,
Using release 
sp-tarkov versions 0.12.11.15453
