### ISSUE TITLE
Can't install via installer

### ISSUE THREAD

**Issue by DarkyKira** [sailro/EscapeFromTarkov-Trainer#101]
When trying to install, this message appears, ran as administrator, the file was in the game folder
I have a licensed version of the game and Escape from Tarkov SPT-AKI installed
Trainer I install on SPT-AKI

Error: Underlying connection closed: Failed to establish trust for the SSL / TLS secure channel.
Error: Underlying connection closed: Failed to establish trust for the SSL / TLS secure channel.
Unable to compile trainer for version 0.12.11.14002. Please file an issue here:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by sailro** [comment]
I think it is the same issue as this:

https://github.com/sailro/EscapeFromTarkov-Trainer/issues/81

Are you on Windows 7 ?

**Comment by DarkyKira** [comment]
I use Windows 10
and I looked SSL 3.0
TLS 1.0
TLS 1.1
TLS 1.2
TLS 1.3 
included
but,now I am getting another error:
Error: Unable to connect to remote server
Error: Unable to connect to remote server
Unable to compile trainer for version 0.12.11.14002. Please file an issue here:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by DarkyKira** [comment]
![Снимок](https://user-images.githubusercontent.com/93761059/141506972-18103949-529c-4813-bdb3-523f3474eddb.PNG)

**Comment by DarkyKira** [comment]
And I apologize for answering late, there was no access to the PC

**Comment by sailro** [comment]
Ah, a firewall rule perhaps? are you using a proxy? The installer is clearly unable to access the Internet. It is needed given the workflow is to download the latest repo snapshot.

**Comment by DarkyKira** [comment]
I understand that the program cannot connect to the server, but I cannot understand why
After all, antivirus and firewall are disabled

**Comment by DarkyKira** [comment]
Maybe the problem is that the version of the game I have is 0.12.11.2.14290
And the error indicates a different version of the game

**Comment by sailro** [comment]
Nope. It is clearly a network issue.

**Comment by sailro** [comment]
(When we are unable to compile, we have a distinct message about it. Here we are not even able to download the snapshot).

**Comment by sailro** [comment]
Are you sure you are not using an HTTP proxy ?

**Comment by sailro** [comment]
If it's the case, you can try to create a config file name `installer.exe.config` along with your `installer.exe` with the following content:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy useDefaultCredentials="true">
      <proxy usesystemdefault="true" />
    </defaultProxy>
  </system.net>
</configuration>
```

**Comment by DarkyKira** [comment]
I'm sure I'm not using proxy
After I created the configuration file, the setup file stopped running and shows the following error:
The application failed to start because its parallel configuration is incorrect. see the application event log for more information or use a command line tool sxstrace.exe
for more information

**Comment by DarkyKira** [comment]
![Снимок](https://user-images.githubusercontent.com/93761059/141637011-711357e0-1d9f-4a18-a20c-b4475b304532.PNG)

**Comment by DarkyKira** [comment]
![Снимок](https://user-images.githubusercontent.com/93761059/141638086-08c20bbe-5f80-4f7e-9d5f-c88abc5ba072.PNG)

**Comment by DarkyKira** [comment]
![Снимок](https://user-images.githubusercontent.com/93761059/141640026-46a5216c-4c2e-4a23-aa77-04ba2c4f2e3f.PNG)
![Снимок2](https://user-images.githubusercontent.com/93761059/141640048-051a6c42-e142-4911-92f7-5ebbf9b034d8.PNG)

**Comment by sailro** [comment]
it is working on my side with the exact same file I gave you ... Attaching it. Remove the `txt` extension.

[Installer.exe.config.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7531944/Installer.exe.config.txt)

**Comment by DarkyKira** [comment]
Unable to connect to remote server

Could it be easier to manually install the files?
It's just that when I installed manually and downloaded from some site the mod did not work, but I found the mod on another site (perhaps yours) but there are fewer functions and it works

**Comment by DarkyKira** [comment]
the cheat with which I'm playing now I downloaded from this site
http://kronzky.info/eft/trainer.html
And he looks like yours

**Comment by sailro** [comment]
> Unable to connect to remote server
> 
> Could it be easier to manually install the files? It's just that when I installed manually and downloaded from some site the mod did not work, but I found the mod on another site (perhaps yours) but there are fewer functions and it works and I installed it manually

No it is not easier given we have to compile against an exact version of the game.

I fear that if you are not able to use the installer, compiling yourself the bits will be a lot harder.

I advise to stay on your current trainer.

Sorry.

**Comment by sailro** [comment]
And indeed it seems the link you gave is just precompiled version of my trainer.

**Comment by DarkyKira** [comment]
I feel sorry I do not know how to compile manually correctly, just the versions of your coach who have already been fragmented for some reason did not work
