### ISSUE TITLE
Unable to compile against EFT 0.12.11.15261

### ISSUE THREAD

**Issue by timaKlu** [sailro/EscapeFromTarkov-Trainer#103]
![image](https://user-images.githubusercontent.com/73841149/141699721-d03bec1d-5628-4c01-8936-6f543e693ebd.png)

**Comment by sailro** [comment]
We are just missing a reference to `UnityEngine.InputLegacyModule.dll` given EFT migrated to Unity 2019

**Comment by sailro** [comment]
Fixed here: https://github.com/sailro/EscapeFromTarkov-Trainer/commit/350542f59796d066b64f670a667a251ee65476c4
