### ISSUE TITLE
stamina still drops when moving overweighted

### ISSUE THREAD

**Issue by kafuuchino-desu** [sailro/EscapeFromTarkov-Trainer#104]
looked into the code for a bit, maybe u forgot to add the parameter for this?
my weight was over 100kg that the red overweight status thingy shown, and with unlimited stamina enabled, when my charater moves the stamina will drop.

**Comment by sailro** [comment]
I'm going to have a look

**Comment by sailro** [comment]
You should be good with this: 
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/ce5d1271b63e74d5a5c8afa5db8d8cffb5bd0af3

**Comment by sailro** [comment]
Just a note: this is now server-sided, so it will only work for offline raids (like those used in sptarkov)
