### ISSUE TITLE
Possible to track all of listr/listsr items 

### ISSUE THREAD

**Issue by mmnt1337** [sailro/EscapeFromTarkov-Trainer#105]
Can you add a function that allows to track all items from listsr or listr by one command.
Thank you in advance :)

**Comment by sailro** [comment]
You should be good with [this](https://github.com/sailro/EscapeFromTarkov-Trainer/commit/71098d26609bb02fee5ea9b3b5a67a19608431eb)

I added `trackr` and `tracksr` commands, working like `track` but with a rarity filter.

Usages:
* `tracksr *` => track all *SuperRare* items (using default color)
* `tracksr Cobra` => track *SuperRare* items with **Cobra** (using default color)
* `trackr foo red` => track *Rare* items with **foo** (using red color)
* `trackr bar [1.0, 1.0, 1.0, 1.0]` => track *Rare* items with **bar** (using custom RGBA color)

`tracklist` will display tracked items, with rarity, reusing the color used.
