### ISSUE TITLE
add better gui and in gui customizability

### ISSUE THREAD

**Issue by Juhiz12** [sailro/EscapeFromTarkov-Trainer#106]
it would be better if you could tweak stuff ingame instead of trainer.ini. it would be easier to create good looking visuals and switch keybinds

**Comment by sailro** [comment]
I'm thinking of it. And we have everything we need to dynamically build those interfaces. The save/load system used for trainer.ini is already 100% dynamic.

**Comment by Juhiz12** [comment]
yes but configuring the trainer.ini is hard (atleast to me)

**Comment by sailro** [comment]
Working on it !

![image](https://user-images.githubusercontent.com/638167/143491921-377a8eab-06f4-4d24-ade7-76af5401d0de.png)

**Comment by Juhiz12** [comment]
looks good :)
