### ISSUE TITLE
infinite stamina doesn't work if you are too heavy

### ISSUE THREAD

**Issue by Juhiz12** [sailro/EscapeFromTarkov-Trainer#108]
i had infinite stamina on and it drained completely (i was really overweight)

**Comment by sailro** [comment]
It think it should be fixed by this: https://github.com/sailro/EscapeFromTarkov-Trainer/issues/104

Did you try to reinstall the trainer recently?

**Comment by Juhiz12** [comment]
i reinstalled the trainer about a day ago

**Comment by sailro** [comment]
as a workaround if you are still hitting the issue, you can use the new `skills` feature to have elite levels + level 3 mastering on all weapons.

**Comment by sailro** [comment]
this should be fixed now
