### ISSUE TITLE
The game loads forever in the initial loading screen

### ISSUE THREAD

**Issue by CrispyCatto** [sailro/EscapeFromTarkov-Trainer#11]
using the latest release of the code, trying to use this online, using live client and i also renamed the Nlog.dll.nlog-live file to Nlog.dll.nlog, yet the game seems to be stuck at the first loading screen, the wheel keeps spinning forever so the game is not frozen but it just doesnt load.

**Comment by sailro** [comment]
As explained in the readme and in the releases section, you need an exact EFT version for this to work (like 0.12.10.11661). Or you need to compile yourself against valid references.

**Comment by CrispyCatto** [comment]
Could you teach me how to compile it myself?
