### ISSUE TITLE
Is it possible to have this work for sp tarkov 2.1.1 0.12.11.7.15426?

### ISSUE THREAD

**Issue by boostedcitizens** [sailro/EscapeFromTarkov-Trainer#112]
I tried to install this on 0.12.11.7.15426 but can't get it to load. Any suggestions?

**Comment by sailro** [comment]
Did not try this one yet. I will have a look

**Comment by sailro** [comment]
I confirm this is working properly on my side

**Comment by sailro** [comment]
Are you sure you are running the proper EFT instance? you can double check with the file %LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt, search for an installation path (often along with Fallback handler could not load library errors). Perhaps you forgot to update your shortcuts to server.exe/launcher.exe files.
