### ISSUE TITLE
in game console does not detect commands

### ISSUE THREAD

**Issue by SamanSarandib** [sailro/EscapeFromTarkov-Trainer#113]
While running installer.exe I get the correct messages, but the ingame console does not detect any of the inputs.

**Comment by sailro** [comment]
The trainer is not loaded : are you sure you are running the proper EFT instance? you can double check with the file `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt`, search for an installation path (often along with Fallback handler could not load library errors). Perhaps you forgot to update your shortcuts to server.exe/launcher.exe files.
