### ISSUE TITLE
Able to make the ESP/Chams visible only?

### ISSUE THREAD

**Issue by nickjok** [sailro/EscapeFromTarkov-Trainer#115]
Not trying to cheat, have horrible eye sight, 100% night blind and have trouble seeing enemies in tarkov sometimes but dont like to cheat. Is there a way to only see enemies when they are visible in my fov, rather than behind walls like the wallhack included in your tool? 

To be clear, I just want charms/chams when enemies are in my line of sight and actually visible so i can see them easier, i do not want wallhack/ESP , Is this possible? :)

**Comment by sailro** [comment]
Yes that's possible. I think @Billybishop is doing this with its own fork of this project.

https://github.com/Billybishop/EscapeFromTarkov-Trainer
