### ISSUE TITLE
 Missing features.

### ISSUE THREAD

**Issue by ByYasin** [sailro/EscapeFromTarkov-Trainer#116]
**Aimbot**
- [x] 	Normal Aimbot `EFT.Trainer.Features.Aimbot`
- [x] 	Silent Aimbot `EFT.Trainer.Features.Aimbot.SilentAim` 
- [x] 	Aimbot Hotkey `EFT.Trainer.Features.Aimbot.Key`
- [ ] 	Bone selection
- [x] 	Aimbot Max Distance `EFT.Trainer.Features.Aimbot.MaximumDistance`
- [x]	Aimbot FOV `EFT.Trainer.Features.Aimbot.FovRadius`
- [x] 	Aimbot Smoothness `EFT.Trainer.Features.Aimbot.Smoothness`
- [x] 	Circle FOV `EFT.Trainer.Features.Aimbot.ShowFovCircle`
- [x] 	Instant Aim `EFT.Trainer.Features.Aimbot.Smoothness=1` 
- [x] 	Instant Hit `EFT.Trainer.Features.Aimbot.SilentAimSpeedFactor` 
- [ ] 	Swap Instant
- [ ] 	Prediction
- [ ] 	Lock Mode
- [ ] 	Draw Aim Line

**Player/Bots ESP**
- [x] 	Chams `EFT.Trainer.Features.Players.ShowCharms`
- [ ] 	Combat Mode
- [ ] 	Combat Mode Hotkey
- [x] 	Players `EFT.Trainer.Features.Players`
- [x] 	Players Max Dist. `EFT.Trainer.Features.Players.MaximumDistance`
- [x] 	Players Bones `EFT.Trainer.Features.Players.ShowSkeletons`
- [x] 	Players Bones Max Dist. `EFT.Trainer.Features.Players.MaximumDistance`
- [x] 	Player Info `EFT.Trainer.Features.Players.ShowInfos`
- [x] 	Player Distance `EFT.Trainer.Features.Players.MaximumDistance`
- [x]  Colors `EFT.Trainer.Features.Players.[Bear|Boss|Cultist|Scav|Usec]Color`
- [ ] 	Teams
- [x] 	Item in Hands `EFT.Trainer.Features.Players.ShowInfos`
- [x] 	Health `EFT.Trainer.Features.Players.ShowInfos`
- [x] 	Health Max Dist. `EFT.Trainer.Features.Players.MaximumDistance`
- [x] 	Hit Markers `EFT.Trainer.Features.Hits`
- [ ] 	World ESP
- [x] 	Grenade esp `EFT.Trainer.Features.Grenades`
- [x] 	Extraction Zone esp `EFT.Trainer.Features.ExfiltrationPoints`
- [x] 	Ammo Count display `EFT.Trainer.Features.Hud`
- [x] 	Crosshair display `EFT.Trainer.Features.CrossHair`
- [x] 	Crosshair Size adjustment `EFT.Trainer.Features.CrossHair.[Thickness|Size]`
- [x] 	Compass `EFT.Trainer.Features.Hud.Compass`

**Loot ESP**
- [x] 	Loot Max Dist. `EFT.Trainer.Features.LootItems.MaximumDistance`
- [x] 	Items `EFT.Trainer.Features.LootItems`
- [x] 	Items Distance `EFT.Trainer.Features.LootItems.MaximumDistance`
- [x] 	Containers `EFT.Trainer.Features.LootableContainers` and `EFT.Trainer.Features.LootItems.SearchInsideContainers`
- [ ] 	Inventories
- [x] 	Corpses `EFT.Trainer.Features.LootItems.SearchInsideCorpses`
- [x] 	Corpses Max.Dist `EFT.Trainer.Features.LootItems.MaximumDistance`
- [ ] 	Corpses Bones
- [ ] 	Corpses Bones Max Dist.
- [ ] 	Price Per Slot / Total Price selection
- [x] 	Prices `EFT.Trainer.Features.LootItems.ShowPrices`
- [ ] 	Price Slider
- [x] 	Item Filter `EFT.Trainer.Features.LootItems.TrackedNames`
- [x] 	Toggle key `EFT.Trainer.Features.LootItems.Key`
- [ ] 	Tags List
- [x] 	Item List `tracklist`, `list`, `listr`, `listsr` commands
- [x] 	Search `list <search>`, `listr <search>`, `listsr <search>` commands

**Misc**
- [x] 	No Recoil `EFT.Trainer.Features.NoRecoil`
- [x] 	No Spread `EFT.Trainer.Features.NoRecoil` 
- [x]  No collisions `EFT.Trainer.Features.NoCollision`
- [x] 	Infinite Stam `EFT.Trainer.Features.Stamina`
- [x]  Automatic gun `EFT.Trainer.Features.AutomaticGun`
- [x]  Automatic gun rate `EFT.Trainer.Features.AutomaticGun.Rate`
- [x]  Quests `EFT.Trainer.Features.Quests`
- [x]  All skills `EFT.Trainer.Features.Skills`
- [x]  All items examined `EFT.Trainer.Features.Examine`
- [x]   Door/Car/Misc opener `EFT.Trainer.Features.WorldInteractiveObjects`
- [x]  Shoot through walls `EFT.Trainer.Features.WallShoot`
- [x]  Maximum penetration `EFT.Trainer.Features.WallShoot`
- [ ] Strip weapon in raid
- [x] 	Thermal Vision `EFT.Trainer.Features.ThermalVision`
- [x] 	Thermal Vision Hotkey `EFT.Trainer.Features.ThermalVision.Key`
- [x] 	Night Vision `EFT.Trainer.Features.NightVision`
- [x] 	Night Vision Hotkey `EFT.Trainer.Features.NightVision.Key`
- [x] 	No Visor `EFT.Trainer.Features.NoVisor`
- [x]	No Fall `EFT.Trainer.Features.Health` 
- [x] 	Multi Search
- [ ] 	Loot Through Walls
- [ ] 	Loot Through Walls Sensitivity
- [ ] 	Loot Through Walls Hotkey
- [x] 	Faster Magazine Management `EFT.Trainer.Features.Skills` 
- [ ] 	High Jump
- [ ] 	High Jump Value
- [x] 	Speed Hack `EFT.Trainer.Features.Speed`
- [x] 	Speed Value `EFT.Trainer.Features.Speed.Intensity`
- [x] 	SpeedHack Hotkey `EFT.Trainer.Features.Speed.Key`
- [x] 	FreeCamera `EFT.Trainer.Features.Camera`
- [x] 	Teleport `EFT.Trainer.Features.Camera.Teleport`

**Comment by sailro** [comment]
for aimbot:
1- The key is fully configurable (and we a a GUI now)
2- Agree
3- What do you mean by that exactly
5- What do you mean by that exactly: not targeting the head but another bone?

misc:
2- We have that already (wallshoot) : maximum penetration and minimal deviation/ricochet

**Comment by ByYasin** [comment]
InstantHit 
so available?

**Comment by ByYasin** [comment]
for aimbot:
3-SilentAim 

example : https://github.com/JoakimCarlsson/EscapeFromTarkov-CP/tree/master/Citadel/CitadelEFT

**Comment by ByYasin** [comment]
@sailro

**Comment by ByYasin** [comment]
Aimbot
	Normal Aimbot
	Silent Aimbot
	Aimbot Hotkey
	Bone selection
	Aimbot Max Distance
	Aimbot FOV
	Circle FOV
	Swap Instant
	Prediction
	Lock Mode
	Draw Aim Line
Player ESP
	Chams
		Combat Mode
		Combat Mode Hotkey
		Players
		Players Max Dist.
		Players Bones
		Players Bones Max Dist.
		Player Info
		Player Distance
		Teams
		Item in Hands
		Health
		Health Max Dist.
		Bot ESP
	Bots
		Bots Max Dist.
		Bots Bones
		Bots Bones Max Dist.
		Item In Hands
		Health Bots
		Health Max Dist.
		World ESP
	Grenade esp
	Extraction Zone esp
	Ammo Count display
	Crosshair display
	Crosshair Size adjustment
Loot ESP
	Loot Max Dist.
	Items
	Items Distance
	Containers
	Inventories
	Items Distance
	Containers
	Corpses
	Corpses Max.Dist
	Corpses Bones
	Corpses Bones Max Dist.
	Price Per Slot / Total Price selection
	Prices
	Price Slider
	Item Filter
	Item Filter
	Toggle key
	Tags List
	Item List
	Search Bar
Colors
	Wide color selection(including transparency)
Misc
	No Recoil
	No Spread
	Infinite Stam
	Instant Aim
	Instant Hit (best)
	Strip Weapon(In raid)
	Thermal Vision
	Thermal Vision Hotkey
	Night Vision
	Night Vision Hotkey
	No Visor
	No Fall
	No Fall Hotkey
	No Fall Up HotKey
	No Fall Down HotKey
	Multi Search
	Loot Through Walls
	Loot Through Walls Sensitivity
	Loot Through Walls Hotkey
	Faster Magazine Management
	High Jump
	High Jump Value
	Speed Hack
	Speed Value
	SpeedHack Hotkey



My suggestions to add. This will make your project legendary.

**Comment by sailro** [comment]
I'm going to refactor a bit this thread with this last list you gave

**Comment by ByYasin** [comment]
> I'm going to refactor a bit this thread with the last list you gave. (done)

thanks.

**Comment by sailro** [comment]
I just added an [`health`](https://github.com/sailro/EscapeFromTarkov-Trainer/pull/127/files) feature, gives full health, prevent any damage (so even when falling), keeping energy and hydration at maximum (off by default). Updating the list.

**Comment by sailro** [comment]
I just added `camera` feature with free camera and teleport.

**Comment by ByYasin** [comment]
Instant Hit, Silent Aimbot, Aimbot FOV 

Is it possible to be added?
Thanks for the other features.

**Comment by sailro** [comment]
I added FOV and FOV circle.

See with a 512 radius (set to 0 to use the full screen as previously):

![Screenshot 2022-01-17 16 41 32](https://user-images.githubusercontent.com/638167/149802244-210f90d7-ac9b-4624-a807-ad6bad45b710.png)

**Comment by ByYasin** [comment]
Instant Hit, Silent Aimbot Is it possible to be added?
Thanks for the other features.

**Comment by sailro** [comment]
I added SilentAim (`EFT.Trainer.Features.Aimbot.SilentAim`), which is using Instant Hit (`EFT.Trainer.Features.Aimbot.SilentAimSpeedFactor`)

![Screenshot 2022-01-20 10 17 55](https://user-images.githubusercontent.com/638167/150313523-00a9d069-f460-4076-809a-57fb10ab83c7.png)

It is working quite well:

![Screenshot 2022-01-20 10 36 44](https://user-images.githubusercontent.com/638167/150313662-a7735360-59a2-4e92-9a58-e2d21c55da44.png)

**Comment by ByYasin** [comment]
Thanks. Should the settings remain as default?

**Comment by sailro** [comment]
By default SilentAim is disabled

**Comment by ByYasin** [comment]
Yes, okay.

**Comment by sailro** [comment]
I just added hit markers and item auto-examination

**Comment by Billybishop** [comment]
Hey fellas, I updated the existing enhancement for the 'Bone Selection' feature and added a new feature request which could be named 'Container Highlighting'. Feel free to update this list when you get a chance and we can link those specific items to the corresponding open enhancements:

- **Bone Selection**:
   https://github.com/sailro/EscapeFromTarkov-Trainer/issues/75
- **Container Highlighting**:
   https://github.com/sailro/EscapeFromTarkov-Trainer/issues/150
   
**Note**:  'Container Highlighting' intent is to provide color-coded highlighting or rendering of non-living game objects. So it's under the assumption that dead player/npc objects are considered 'containers'. Feel free to rename it to a more fitting title.

**Comment by ByYasin** [comment]
> I just added hit markers and item auto-examination


Does DROP display come to Esp features?
