### ISSUE TITLE
New loader not supported the uninstall

### ISSUE THREAD

**Issue by Lacedenou** [sailro/EscapeFromTarkov-Trainer#117]
Hi, 

It's impossible for me to uninstall this 3 patches :

1. remove the file EscapeFromTarkov_Data\Managed\NLog.EFT.Trainer.dll

2. remove the file EscapeFromTarkov_Data\outline

3. edit the file EscapeFromTarkov_Data\Managed\NLog.dll.nlog, remove the line <target name="EFTTarget" xsi:type="EFTTarget" />

**Comment by sailro** [comment]
You can use the universal installer for that:

`installer.exe uninstall "path\to\eft"`

**Comment by Lacedenou** [comment]
Is this a command that I need to add to the software?!

**Comment by sailro** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-1.7

See Usages.

**Comment by Lacedenou** [comment]
The installer suggests that this ...

**Comment by sailro** [comment]
I'm afraid I do not understand what you want :)
