### ISSUE TITLE
Exfil Suggestion

### ISSUE THREAD

**Issue by Elicit2** [sailro/EscapeFromTarkov-Trainer#118]
You should add a option to toggle non eligible exfils on and off, after awhile it gets pretty annoying when the non eligible exfils are blocking the eligible exfils. Thank you for your consideration, Elicit

**Comment by sailro** [comment]
Yep. and it's super easy to do. I was just keeping them given for me  it's an easy way to locate POI:)

**Comment by sailro** [comment]
Done!

You can save/load to update your `trainer.ini`, you'll find the following new keys:

```
EFT.Trainer.Features.ExfiltrationPoints.ShowEligible=true
EFT.Trainer.Features.ExfiltrationPoints.ShowNotEligible=true
EFT.Trainer.Features.ExfiltrationPoints.StatusFilter=""   =>  like `Closed` to filter closed exfil points.
```

Or you can use the GUI:

![image](https://user-images.githubusercontent.com/638167/147392448-0b94c967-8938-4f99-b308-ff908bfed994.png)
