### ISSUE TITLE
Compiled Release for SPT AKI 1.0.1

### ISSUE THREAD

**Issue by boostedcitizens** [sailro/EscapeFromTarkov-Trainer#12]
Hi, would it be possible if you can provide a compiled release that supports SPT AKI 1.0.1? Thank you so much in advance!

**Comment by sailro** [comment]
It's only the EFT version that is important. Given sptarkov 1.0.1 targets `0.12.10.11661`, it should work as is with the latest [release](https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/0.12.10.11661)

Can you give it a try, I will reword the release section, to make it more explicit.

**Comment by boostedcitizens** [comment]
You are awesome! I'm so sorry to even waste your time for this. It worked for spt 1.0.1. Thank you!

**Comment by sailro** [comment]
Great!

**Comment by sailro** [comment]
Updated the release section accordingly:

https://github.com/sailro/EscapeFromTarkov-Trainer/releases
