### ISSUE TITLE
Please update for 12.12.16338

### ISSUE THREAD

**Issue by UniqDzn** [sailro/EscapeFromTarkov-Trainer#121]
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.12.12.16338) in C:\Games\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.12.12.16338) in C:\Games\EFT.
>> Try #1 Compilation failed for master branch.
>> Try #2 Branch dev-0.12.12.16338 not found.
Unable to compile trainer for version 0.12.12.16338. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by sailro** [comment]
We should be good now.

![image](https://user-images.githubusercontent.com/638167/147405940-a78620ee-1806-4481-a7cb-47c29316a2ea.png)
