### ISSUE TITLE
Support for 0.12.12.x (Quests are disabled for now)

### ISSUE THREAD

**Issue by ScaredTheDEV** [sailro/EscapeFromTarkov-Trainer#122]
Update pls....

**Comment by sailro** [comment]
![image](https://user-images.githubusercontent.com/638167/147651564-27b9adf1-6710-4de2-b064-dbdbaa953e07.png)

Given I reverted the changes related to Quests, this feature is automatically disabled.

I will work on that when spt-aki will be available for `0.12.12.x`

**Comment by sailro** [comment]
Fixed here: https://github.com/sailro/EscapeFromTarkov-Trainer/commit/a0b025acef81d153e428c164c6c370ce013c8aeb

**Comment by sailro** [comment]
![image](https://user-images.githubusercontent.com/638167/152657873-780f484a-0638-4ad1-860d-1cc63e444cdc.png)
