### ISSUE TITLE
Ability to Only show box around players and bots without colouring the model or show skeleton

### ISSUE THREAD

**Issue by asdkevinasd123** [sailro/EscapeFromTarkov-Trainer#123]
As titled, I want to know if it is possible to only draw the box and info and nothing else when using wallhack. No coloring the model nor skeleton.

**Comment by sailro** [comment]
Sure, you can edit your `trainer.ini` for this:

```
EFT.Trainer.Features.Players.ShowBoxes=true
EFT.Trainer.Features.Players.BoxThickness=2.0
EFT.Trainer.Features.Players.ShowCharms=false
EFT.Trainer.Features.Players.ShowInfos=true
EFT.Trainer.Features.Players.ShowSkeletons=false
EFT.Trainer.Features.Players.SkeletonThickness=2.0
```
Or you can use the in-game GUI (default-key is `RightAlt`):

![image](https://user-images.githubusercontent.com/638167/147853023-acedf0e2-6ee4-4a94-88bc-201e9f461fe9.png)

**Comment by asdkevinasd123** [comment]
Ok thanks!
