### ISSUE TITLE
Enhancement: Loot rarity/categories

### ISSUE THREAD

**Issue by RobinxR** [sailro/EscapeFromTarkov-Trainer#124]
Hey, I think it would be beneficial if you could create your own category or list of items and then only track them ingame.
For example you can create a config json/ini in which you insert item ID's (to stop strings from interfiering with eachother like "RAT"poison and sp"RAT"s) and then use the track function like "track "myowncategory".

**Comment by sailro** [comment]
@RobinxR 

I added support for loading/saving dedicated tracklists. And now you can search by item ID as well.

Demo (`5b432f3d5acfc4704b4a1dfb` is the `ID` for `Momex balaclava`)

`track Plague red`
`track shmaska blue`
`track 5b432f3d5acfc4704b4a1dfb`

Now you have setup your tracklist, you can save it:

`savetl headwear`

This will create a `headwear.tl` in the same folder than your `trainer.ini`

Now you can alter your tracklist and restore it after using `loadtl headwear`

done here: https://github.com/sailro/EscapeFromTarkov-Trainer/commit/5bba896082fb77765bf8686da3dfbf6eee214fac

Example of `headwear.tl` content:

```json
[
  "5b432f3d5acfc4704b4a1dfb",
  {
    "Name": "Plague",
    "Color": [
      1.0,
      0.0,
      0.0,
      1.0
    ],
    "Rarity": null
  },
  {
    "Name": "shmaska",
    "Color": [
      0.0,
      0.0,
      1.0,
      1.0
    ],
    "Rarity": null
  }
]
```
