### ISSUE TITLE
Trainer.ini

### ISSUE THREAD

**Issue by Arlecchino94** [sailro/EscapeFromTarkov-Trainer#125]
does not create the trainer.ini file for me and nothing works in the game, it is as if it was not installed despite being installed successfully, does anyone have a solution to the problem?

**Comment by sailro** [comment]
`trainer.ini` is not created by default (only if you use the `save` command in the console or if you use save from the GUI).

- Did you use the Universal installer?
- Could you share your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log` ?

**Comment by Arlecchino94** [comment]
[Player-prev.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7857958/Player-prev.log)
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7857959/Player.log)
this is my log and yes, use Universal installer

**Comment by bvparekh** [comment]
Hi Sebastian,

I created the trainer.ini file by hand and saved it in the folder. Can you tell me how to pull up the GUI? For some reason, I do not get the separate colors for USEC, BEARS, Scavs and Bosses. All bots show up as RED color. I am trying to figure how to change the colors. Any help will be appreciated.

Thank you!

**Comment by Arlecchino94** [comment]
> 

How create this file and location?

**Comment by sailro** [comment]
> [Player-prev.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7857958/Player-prev.log) [Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7857959/Player.log) this is my log and yes, use Universal installer

I can see `E:/Escape.from.Tarkov.v0.12.12.11.16440-P2P/Client.0.12.12.11.16440/` in the logs. @Arlecchino94 do you confirm you installed in this directory? I cannot spot any errors in logs.

**Comment by sailro** [comment]
> Hi Sebastian,
> 
> I created the trainer.ini file by hand and saved it in the folder. Can you tell me how to pull up the GUI? For some reason, I do not get the separate colors for USEC, BEARS, Scavs and Bosses. All bots show up as RED color. I am trying to figure how to change the colors. Any help will be appreciated.
> 
> Thank you!

Default hot key is `RightAlt`:

![Screenshot 2022-01-13 08 38 33](https://user-images.githubusercontent.com/638167/149286475-dde59e0a-42f6-4cdb-8a38-914667fa5d18.png)

**Comment by sailro** [comment]
So we have to manually check stuff:

You should find in your install directory:

-`EscapeFromTarkov_Data\Managed\NLog.EFT.Trainer.dll` this is the compiled code for the trainer.
-`EscapeFromTarkov_Data\outline` this is the dedicated shader we use to outline players [wallhack].
-`EscapeFromTarkov_Data\Managed\NLog.dll.nlog` this is the entry point configuration for the dll. Could you share it for verification ?

To check that the trainer is loaded, you can use the `status` command in the console.

**Comment by bvparekh** [comment]
@sailro - Thank you. I will try it out the next time I get an opportunity to play SPT. Thank you!

**Comment by Arlecchino94** [comment]
Work! Gratis! Thx for help
