### ISSUE TITLE
Support for 0.12.12.11.16440

### ISSUE THREAD

**Issue by tonysamas** [sailro/EscapeFromTarkov-Trainer#128]
hi,im test u trainer in 0.12.12.11.16440 now,but is not supported.BTW im useing  sptarkov 2.2.0 bleededge the vision is 0.12.12.11.16440.
if u have free time,could u update it?thanks! have nice day!

**Comment by sailro** [comment]
Hi, is it not supported at all? It should work except `Quests` that should be the only auto-disabled feature.

**Comment by sailro** [comment]
Are you building sptarkov from source ? I was waiting for the release but perhaps I should do the same

**Comment by sailro** [comment]
![image](https://user-images.githubusercontent.com/638167/149795631-31054f4e-1571-47b4-bc07-a06374767eae.png)

**Comment by sailro** [comment]
Closing, as this one is already tracked here:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/122

Thanks

**Comment by tonysamas** [comment]
sorry,i was so busy.and thank you for answer me.and if u dont mind i translate most page in chinese,even im dont good at it.and thanhk you again sailro,if u need translate doc let me know,i'll email it for u.
