### ISSUE TITLE
0.12.11.7.15261 wallhack bug?

### ISSUE THREAD

**Issue by rwloadArcadia** [sailro/EscapeFromTarkov-Trainer#129]
![unknown (2)](https://user-images.githubusercontent.com/97954368/150124005-ee0feaec-4ef6-4fe5-8071-9fe99e5340ac.png)
Is it normal for the skeleton and gun description to appear like the picture?

**Comment by sailro** [comment]
Yes, just disable ShowSkeleton and ShowInfos if you don't want them. Quite straightforward or am I missing something?

**Comment by rwloadArcadia** [comment]
> 예, 원하지 않는 경우 ShowSkeleton 및 ShowInfos를 비활성화하십시오. 아주 간단합니까 아니면 내가 뭔가를 놓치고 있습니까?

![149804010-f3389aee-8539-4a59-b043-374d700d2e85](https://user-images.githubusercontent.com/97954368/150305074-c83a5476-a0ef-403a-ae23-8bc1526b88ec.png)
The skin tone and gun descriptions seem to be in the wrong location.. Is that normal?

**Comment by rwloadArcadia** [comment]
The colored area is where the corresponding pmc is located, and the hitbox and skeleton are below the colored area.
