### ISSUE TITLE
The boarder box of the wallhack lag behind the actual character

### ISSUE THREAD

**Issue by asdkevinasd123** [sailro/EscapeFromTarkov-Trainer#131]
As title, the box usually lag behind the actual character by 1 to 0.5 second when it is moving. Is there anyway I can improve this aspect? Like force the update rate of the box be faster?

**Comment by sailro** [comment]
This is clearly something I do not repro. Could you share your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log` ? Perhaps we have exceptions killing the performance ?

**Comment by asdkevinasd123** [comment]
Pasted here: https://pastebin.com/NQc5tbw7

**Comment by asdkevinasd123** [comment]
https://pastebin.com/A7FecU3G

Another log, seems to be a lot of port error
