### ISSUE TITLE
loot

### ISSUE THREAD

**Issue by LoadHack** [sailro/EscapeFromTarkov-Trainer#135]
I don't show loot
what should I do?

**Comment by sailro** [comment]
Everything explained in the readme:

Make sure `loot` is enabled and use `track` to track a specific or all items.

| Command   | Values              | Default | Description                         |
|-----------|---------------------|---------|-------------------------------------|
| list      | `<optional filter>` |         | List lootable items                 |
| listr     | `<optional filter>` |         | List only rare lootable items       |
| listsr    | `<optional filter>` |         | List only super rare lootable items |
| loot      | `on` or `off`       |         | Show/Hide tracked items             |
| track     | `[name]` or `*`     |         | Track all items matching `name`     |
| track     | `[name]` `<color>`  |         | Ex: track `roler` `red`             |
| track     | `[name]` `<rgba>`   |         | Ex: track `roler` `[1,1,1,0.5]`     |
| tracks    | same as `track`     |         | Track rare items only               |
| tracksr   | same as `track`     |         | Track super rare items only         |
| tracklist |                     |         | Show tracked items                  |
| untrack   | `[name]` or `*`     |         | Untrack a `name` or `*` for all     |
