### ISSUE TITLE
Feature suggestion: visible-only charms

### ISSUE THREAD

**Issue by youncc** [sailro/EscapeFromTarkov-Trainer#138]
please add visible only chams, would help people like me that are incredibly blind :)

**Comment by sailro** [comment]
I added a new setting `XRayVision`:

![InkedScreenshot 2022-02-08 20 38 20_LI](https://user-images.githubusercontent.com/638167/153063719-568696b3-2fd2-4e9e-9b45-e9c559bbc0ec.jpg)

When enabled (by default):
![Screenshot 2022-02-08 20 37 01](https://user-images.githubusercontent.com/638167/153063952-94a82122-eaf4-40a9-8a92-53b086d47307.png)

When disabled:
![Screenshot 2022-02-08 20 37 35](https://user-images.githubusercontent.com/638167/153064104-d440c4a1-d63f-429f-bd19-f9c17e0befd7.png)
