### ISSUE TITLE
Error Message when Installing for SPT v2.2.0 - EFT v0.12.12.15.16584

### ISSUE THREAD

**Issue by bvparekh** [sailro/EscapeFromTarkov-Trainer#139]
Hi Sailro,

I got the attached error when I tried to install for the latest SPT v2.2.0; Error message said to file this as an issue so here it is.
![EFT Issue](https://user-images.githubusercontent.com/66034563/152656357-a745798a-9474-4a80-b3cf-48de7ef6ae35.PNG)

**Comment by sailro** [comment]
Yep, this is tracked here already:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/122

The good news is that I just pushed an update, so you should be good. Just re-run the installer :)
