### ISSUE TITLE
ERROE:CS8600

### ISSUE THREAD

**Issue by cracky5322** [sailro/EscapeFromTarkov-Trainer#14]
Hello, how can I solve the error code of CS8600 when compiling?
The error position is in lines 16 and 68 of CachableMonoBehaviour

**Comment by sailro** [comment]
Try to use the latest Visual Studio 2019 ?

**Comment by cracky5322** [comment]
> 嘗試使用最新的Visual Studio 2019嗎？

Microsoft Visual Studio Community 2019
VER 16.7.7

**Comment by sailro** [comment]
Latest is 16.9.4 so as I said please update. This should solve this issue

**Comment by cracky5322** [comment]
> Latest is 16.9.4 so as I said please update. This should solve this issue
In the past, I used offline installation, which caused the need to update manually
Thank you for your awareness

**Comment by cracky5322** [comment]
> > Latest is 16.9.4 so as I said please update. This should solve this issue
In the past, I used offline installation, which caused the need to update manually
Thank you for your awareness
