### ISSUE TITLE
Aki 2.2.0, "listsr","listr" commands do not work

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#140]
As shown in the image, all items are marked as Common

![2022-02-06 16-23  (0)](https://user-images.githubusercontent.com/85558614/152671374-71cdefc9-aae1-4ab7-a1d4-80e92eb2c570.png)
.

**Comment by sailro** [comment]
Yes so it seems they removed this information, but we can guess using the related `LootExperience`:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/85c0b4302699cc8034c5d1a708ae386fab7c5cf6

![Screenshot 2022-02-06 11 16 20](https://user-images.githubusercontent.com/638167/152676432-2631660e-c694-4515-846e-826302f12c18.png)
