### ISSUE TITLE
[Request] Track Item with WishList

### ISSUE THREAD

**Issue by Woudidi** [sailro/EscapeFromTarkov-Trainer#141]
Possible to get a new features " Track Items " sync with the Wishlist 
" Like for Track - Unlike for untrack " ?
Thx

**Comment by sailro** [comment]
We have that already.

See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/124#issuecomment-1031937651

**Comment by Woudidi** [comment]
But is not with the " wishlist " In-game ? if i right click and click to " add to wishlist " is going directly in tracklist ? sry bad english im french

**Comment by sailro** [comment]
Passe en français alors parce que je comprends rien :)

**Comment by sailro** [comment]
Ah si oui ok, utiliser la wishlist de tarkov pour alimenter notre tracklist pour le loot.

**Comment by Woudidi** [comment]
Oui voila ! j'ai vue cette feature sur un autre trainer et ça fonctionne parfaitement

**Comment by W1cke4d** [comment]
is there englisch translation ? :_D

**Comment by sailro** [comment]
The `loadwl` command allows to load the tracklist from the tarkov wishlist. Only one small constraint: it must be invoked in-raid or from the hideout so that the list is up-to-date in the player's profile.
