### ISSUE TITLE
UI rendering issue when Texture resampling is not off (1x)

### ISSUE THREAD

**Issue by DIASILEDU** [sailro/EscapeFromTarkov-Trainer#149]
I've been using this for a week in SPT-AKI and I noticed that sometimes the walls and boxes are not working on some player objects but charms is. Also I noticed that the XRay feature stopped working on 2.2.3, or at least for me and the hitmarker never worked.

Maybe also add an offset to the aim because is pointing to the chest, maybe make it point to the head?

And I'd like to know if you can make this compatible with the resampling graphic setting in the game, I have a 1440p monitor but run the game at  0.75x downsampling (1080p cuz FPS drops) and the boxes move to a completely different position, the aim point to another part, this migh be the same when using supersampling.

I hope this is not a lot to ask :D

**Comment by sailro** [comment]
When changing resolutions, this is style working properly.

But indeed there is an issue when using resampling <> 1x

**Comment by sailro** [comment]
Fixed by https://github.com/sailro/EscapeFromTarkov-Trainer/pull/269 as well
