### ISSUE TITLE
Does NOT work with 0.12.12.15.17107 (15 Mar 2022) *** add SPT-AKI 2.3.0 (with BepInEx)

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#151]
With SPT-AKI 2.3.0 now integrated with and using BepInEx, version 1.8 of the installer.exe no longer works.  Running it detects the game, and actully succeeds and patches and creates the files.  However, once the game loads, and counts down to start/launch, it just stis there and never starts.  There are numberous errors in the BepInEx Console, starting with one about not being able to load (outline) and then other errors.

03/21/2022 - Not looking to pressure anyone, just wondering if anyone can acknowlege that this has been seen.   Thanks.

**Comment by sailro** [comment]
I'm going to have a look

**Comment by sailro** [comment]
![image](https://user-images.githubusercontent.com/638167/159551194-525793cd-7cac-4a71-8f8e-c4e28a41c4b7.png)

It is working on my side, but now given they switched to `BepInEx`, they removed `Harmony` support.

As a result:
- Silent Aim - not working (bullets are not redirected)
- All items examined - not working
- Hit markers - not working
- Stamina and Health are working but in degraded mode

**Comment by sailro** [comment]
So I'm going to upgrade the installer to install harmony now

**Comment by RogueTech67** [comment]
Sailro, thanks so much.  V1.9 now works for game 0.12.12.15.17107 (11 Mar
2022) *** add SPT-AKI 2.3.0.  Much appreciated.  Love the trainer, I'm
"horrible" at the game :-)
