### ISSUE TITLE
Drop

### ISSUE THREAD

**Issue by narzhull** [sailro/EscapeFromTarkov-Trainer#152]
Hello . Firstly i have to THANK for this beautiful work @sailro . That made my offline gaming better.

I just want to ask is this trainer causes fps drop thing ?  Or its my computer.

**Comment by CorzaHorizon** [comment]
Obviously, the "track item" causes frame drops as the list is updated every few seconds.

**Comment by narzhull** [comment]
> Obviously, the "track item" causes frame drops as the list is updated every few seconds.

Just that option ? Is there any other generally ?

**Comment by sailro** [comment]
All features need computing power. In particular loot items. But everything is quite configurable like tweaking your:

`EFT.Trainer.Features.LootItems.CacheTimeInSec=3.0`

To a higher value.

**Comment by narzhull** [comment]
> All features need computing power. In particular loot items. But everything is quite configurable like tweaking your:
> 
> `EFT.Trainer.Features.LootItems.CacheTimeInSec=3.0`
> 
> To a higher value.

Thanks a lot sir. I got what i wanted with your trainer. But couldnt find where i will write the code for uninstall
