### ISSUE TITLE
The "Loot" feature has serious performance issues

### ISSUE THREAD

**Issue by hugeWrongMistake** [sailro/EscapeFromTarkov-Trainer#154]
It took about 68ms to RefreshData on I7 core cpu.

**Comment by hugeWrongMistake** [comment]
Try not to scan so many loots at a time, or use multiple threads. It happens when there is a lot of loots in raid.

**Comment by sayrex2009** [comment]
> 

How did you enable scanning? I can only see the list through the console, but the loot does not show

**Comment by hughz001** [comment]
you must type track ... and what ever you are trying to track only then will show up also dont track to much at once fps will become a problem hope this helps
