### ISSUE TITLE
newbie looking to learn

### ISSUE THREAD

**Issue by Jermski08** [sailro/EscapeFromTarkov-Trainer#156]
hello, i was wondering what the next step is after i run the launcher and find my games path directory. i guess my main question is how to open the menu in game. i tired using the in game command console ~ but none of the commands work.

**Comment by Jermski08** [comment]
![Capture12](https://user-images.githubusercontent.com/102268315/160012766-352dad23-a3b9-49d2-a83c-6ce64601b269.PNG)

**Comment by Jermski08** [comment]
this is as far as i got lol

**Comment by sailro** [comment]
Everything is quite documented on the main page (commands, ...) : https://github.com/sailro/EscapeFromTarkov-Trainer

The default key for the in-game menu is `RightAlt`. Perhaps we need to be more explicit about this one.

**Comment by Jermski08** [comment]
yea it says just to run the installer and pick the directory of your game, i do that and load up my game and press right ALT and nothing happens. not sure what i am doing wrong. Ill ask for help on another platform

**Comment by sailro** [comment]
Are you sure you are running the proper EFT instance? you can double check with the file `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log`, search for an installation path (often along with Fallback handler could not load library errors). Perhaps you forgot to update your shortcuts to server.exe/launcher.exe files if you are using `spt-aki`.

**Comment by Jermski08** [comment]
that was the problem! omg thank you
