### ISSUE TITLE
Ram comsumption

### ISSUE THREAD

**Issue by duyphamvu47** [sailro/EscapeFromTarkov-Trainer#157]
Hi, I have a problem with my memory when using the trainer. It's just going up up and the game crash when I run out of RAM
P/s: I have 16GBs of RAM and thanks for the trainer btw

**Comment by sailro** [comment]
Ah strange, never hit such an issue.

Could you share your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log`, in case we can find something interesting. Thanks

**Comment by duyphamvu47** [comment]
> Ah strange, never hit such an issue.
> 
> Could you share your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log`, in case we can find something interesting. Thanks

I can't find any file which name is "Player.log" at that path. There is just 1 file  in that folder and it's name is "output_log.txt"

**Comment by sailro** [comment]
You are using an old EFT version. Any chance you can upgrade to the latest ?

Since this old version, both EFT and the trainer improved their memory footprint.

**Comment by duyphamvu47** [comment]
> You are using an old EFT version. Any chance you can upgrade to the latest ?
> 
> Since this old version, both EFT and the trainer improved their memory footprint.

Thanks for explanation. I'll try to update to the latest version and inform you if the problem still happen
