### ISSUE TITLE
how can i enable thos features?

### ISSUE THREAD

**Issue by a3de25** [sailro/EscapeFromTarkov-Trainer#158]
![image](https://user-images.githubusercontent.com/102370532/160138542-a8c9306d-617f-4d4e-b4fd-cc92d2e31abc.png)

i know when i open alt right i get this menu how can i get those advanced features like:wallhack thickness, color,maximumdistance,show box etc.
plus i need to know how can i change things like:player speed of aimbot speed?

p.s sorry for bad english

**Comment by a3de25** [comment]
![Screenshot (37)](https://user-images.githubusercontent.com/102370532/160140322-04aab56d-3184-4a84-b407-99e64607f499.png)
i only have something like this

**Comment by sailro** [comment]
That' because you are using an obsolete version of the trainer. I do not even know how that's possible.

Only use this for installing : https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-1.9

do not download unknown stuff elsewhere.

**Comment by a3de25** [comment]
> 

i actually downloaded this obsolete version from here

**Comment by a3de25** [comment]
i just download from the link you gave me and its still the same menu

**Comment by sailro** [comment]
That's because you are not running the proper EFT....

**Comment by sailro** [comment]
Ah another idea: you have a super old EFT, so the installer is using an old branch. Show us your installer window please.

**Comment by a3de25** [comment]
![Screenshot (39)](https://user-images.githubusercontent.com/102370532/160156905-f78da9d6-bf7e-4e71-971d-09282dd38a68.png)

**Comment by a3de25** [comment]
i use a cracked version of the game

**Comment by sailro** [comment]
That's bad we do not support piracy. Closing this thread.
