### ISSUE TITLE
This dont work!

### ISSUE THREAD

**Issue by neil501** [sailro/EscapeFromTarkov-Trainer#16]
I've been at this 3 days now all day trying to figure out what i'm missing I was able to do everything you wrote but this trainer doesnt respond nor does it even work when i hit the right alt key or the period key for locked doors! Nothing even shows up! The game plays normal like no trainer was installed. Do i have to create my very own trainer ini file? Well i hate to give bad news but whatever you tried to make sadly didnt work. I put 3 full days in on it and nothing i dont think most people would bother to waste that much time on this. Sorry anyway good luck! I hope you figure out what went wrong because i can't and i really really tried! If you ever get this to work please let us know.

**Comment by sailro** [comment]
Everything is super simple and explained in the main readme. Sorry if you are not able to use it, but it works indeed, given all the feedback I ghave from users.

**Comment by neil501** [comment]
question-

 inside theNLog.dll.nlog  file should it look like this? 


<target name="Aki.Loader" xsi:type="Aki.Loader" />
		<target name="EFTTarget" xsi:type="EFTTarget" />

or should it ONLY be 

<target name="EFTTarget" xsi:type="EFTTarget" />     

I uninstalled and reinstalled the game to have a fresh game to start with and going step by step
