### ISSUE TITLE
Purple Models?

### ISSUE THREAD

**Issue by DEVILISHTUNE** [sailro/EscapeFromTarkov-Trainer#161]
Is there a setting to remove the models from being the unity missing texture?

**Comment by sailro** [comment]
If you hit purple models then your installation probably failed. We use this as a deprecated mode when our `outline` file is not found.

Could you re-run the installer and give the ouptut here?

**Comment by DEVILISHTUNE** [comment]
Well, well I fixed it by re-installing SPT/Tarkov it was actually some of my files messed up. Thanks for telling me in case it does happen that way!

**Comment by sailro** [comment]
Great if it is working now
