### ISSUE TITLE
Fallback 08.04.22

### ISSUE THREAD

**Issue by YoupsTV** [sailro/EscapeFromTarkov-Trainer#162]
![image](https://user-images.githubusercontent.com/103287537/162527850-eee6051f-29b6-4c85-8d3d-2e06b965aac6.png)

**Comment by sailro** [comment]
Are you using the latest installer?

**Comment by sailro** [comment]
You are not, but indeed I repro as well on the latest

**Comment by sailro** [comment]
Fixed in main. Please re-run the latest installer.
