### ISSUE TITLE
Request - Add Showing Loose Loot / Stand-Alone Items As Well in Stash

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#163]
Hope it's okay to add a "Request" in here.  Saw only an Issues section.  A modded named Kronzky had made and was maintaining a similar (almost the same) trainer (http://www.kronzky.info/eft/trainer.html) up until version 0.12.11.7.15680 (29 Nov 2021) *** for SPT-AKI 2.1.2.  Appears he is no longer updating it.  His version allowed showing of the Loose Loot items in the map, as well as the containers and caches.  Being a new player myself, it was great to be able to have help seeing where the items lying around the map were.  I would like to request that this feature be added, if you are willing.   Thanks in advance.

**Comment by sailro** [comment]
Well you can do the same thing. Either use the GUI or the console commands. You have `stash`, `track` and `tracklist` commands. You should find all the explanation on the main readme. 

I think Kronzky in his fork just enabled this by default.
