### ISSUE TITLE
Génialissime

### ISSUE THREAD

**Issue by computeur** [sailro/EscapeFromTarkov-Trainer#164]
Je cherchais un mode comme dans le jeu original c'est totalement ça (je joue sur la version SPT-AKI)
Par contre je suis passé en 2.3.1 et bizarement les NPC sont en mode divin (immortels) tout comme moi 
Sinon tout fonctionne avec le fichier .ini dans Mes Documents 
Tout comme les commandes de la console
seul  bémol je dois jouer avec la version 2.2.1 afin de pouvoir tuer les npc 
Et encorter merci pour cet outil

**Comment by sailro** [comment]
Merci!> Oui a priori j'ai fais une petite régression pour mon dernier patch, je suis en train de regarder ça

**Comment by sailro** [comment]
cc https://github.com/sailro/EscapeFromTarkov-Trainer/issues/165

**Comment by sailro** [comment]
C'est corrigé, il suffit de relancer l'installeur
