### ISSUE TITLE
Health feature is making Other Usec/Bear, Scavs, Bosses invicible as well

### ISSUE THREAD

**Issue by 2Krunchy** [sailro/EscapeFromTarkov-Trainer#165]
I've used spt-aki for awhile (mainly 2.2.3) and when I updated to 2.3.0 (New folder + new installation) with the new installer (1.9) I've noticed using the health feature makes everything invincible including the player (Other Usec/Bear, Scavs, Bosses). I looked into the closed issues of this trainer and saw that it was already noticed. I went back to spt-aki 2.2.3 (again, creating a whole new folder + new installation with it being patched to 12.12.16909) and the problem persisted into 2.2.3, with the health feature making everything invincible. I used the main installer (1.9). I saw there was a way to make the trainer install a certain branch that was more compatible with 2.2.3 however I am not very tech-savvy and I could not get it to work (It always installed under the master branch) Any help would be greatly appreciated.

**Comment by sailro** [comment]
Yes got it, I think I made a mistake with my last commit.

I'm going to have a look.

**Comment by sailro** [comment]
`Installer --branch dev-0.12.12.17107` should do the trick while I'm investigating the issue

**Comment by sailro** [comment]
This is now fixed, you just nee to re-run the installer
