### ISSUE TITLE
Installer not compatible with 0.12.12.17686

### ISSUE THREAD

**Issue by ZeusTRL** [sailro/EscapeFromTarkov-Trainer#168]
It does not appear that the installer is compatible with the most recent version of the game

![Capture](https://user-images.githubusercontent.com/101527389/164981957-fac531d3-1a89-4dfd-a64c-c60bbd0580d3.PNG)
e

**Comment by valerEFT** [comment]
same error for me, 1st time here, wanted to try cheat did u have allrdy tried, is it working? cant belive that its free xD

**Comment by sailro** [comment]
Thanks for the report, it is already tracked here: #167
