### ISSUE TITLE
Feature Suggestion: ESP/Chams color visible and not visible to player

### ISSUE THREAD

**Issue by Elicit2** [sailro/EscapeFromTarkov-Trainer#169]
You should add a color option when the ESP/Chams are visible to the character and when they're not, like seen on CSGO cheats. Thanks!

**Comment by valerEFT** [comment]
@Elicit2 hi, is cheat working for u? 1st time decided to download it xD but have error Unable to compile trainer for version 0.12.12.17686. is chet working for u guys?

**Comment by sailro** [comment]
@Elicit2 we have that if I'm understanding correctly, see https://github.com/sailro/EscapeFromTarkov-Trainer/issues/138

**Comment by sailro** [comment]
See the `XRayVision` parameter:

![image](https://user-images.githubusercontent.com/638167/165247924-57c58e39-37d5-46f4-8217-05360e80221a.png)

**Comment by valerEFT** [comment]
> @Elicit2 we have that if I'm understanding correctly, see #138
hi, is cheat not working now? want to know we must wait for u to update it? or its maybe working and im doing smth wrong
