### ISSUE TITLE
Ram consumption

### ISSUE THREAD

**Issue by MaxBroonn** [sailro/EscapeFromTarkov-Trainer#171]
Hi!
Thank you for the trainer - it`s great!
But I have a problem with my memory when using the trainer 1.9 (especially "Loot" feature) with SPT-AKI 2.3.1. It's just going up and up and the game crash when I run out of RAM. I have 32GBs of RAM.
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/8602703/Player.log)
[trainerini.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/8602729/trainerini.txt)

**Comment by sailro** [comment]
I never hit this issue, and I see nothing special in the logs. Are you using other tools/mods with tarkov or spt-aki ?

**Comment by sailro** [comment]
Still no repro on my side. Closing
