### ISSUE TITLE
Possible Incompatibility

### ISSUE THREAD

**Issue by Official-Husko** [sailro/EscapeFromTarkov-Trainer#174]
Using this Trainer, [CoreMod][0] & [ZEreshkigal AllinOneMod][1] seems to cause a problem where the sound bugs away and if being shot it will cause a black screen that most of the time freezes the game. Could this be checked? These mods are needed to change some stuff in tarkov to make more like the old version. 
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/8692962/Player.log)

Edit: After testing it seems that any mod that changes weight values into a negative number causes these problems with this trainer.

[0]:https://hub.sp-tarkov.com/files/file/97-ereshkigal-coremod/
[1]:https://hub.sp-tarkov.com/files/file/521-ereshkigal-allinonemod/

**Comment by sailro** [comment]
No, see the following:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Extensions/ItemExtensions.cs#L26

I'm not using `weight` anymore.
