### ISSUE TITLE
Live Trainer 

### ISSUE THREAD

**Issue by mxtchl1** [sailro/EscapeFromTarkov-Trainer#184]
I was able to get the trainer working on Aki - How can I use this on multiplayer with other players instead of solo only?

**Comment by LDmitrii** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/167
Its pinned. Check next time issues list.

**Comment by sailro** [comment]
> > I was able to get the trainer working on Aki - How can I use this on multiplayer with other players instead of solo only?
> 
> How did you get the trainer working, If you dont mind me asking?

In the README.MD file:

master branch can build against `EFT 0.12.12.17349` (tested with [spt-aki Version 2.3.1](https://hub.sp-tarkov.com/files/file/6-spt-aki/#versions)). 

Again I'm waiting for the next spt-aki, before working on the upgrade (given this time it will require a bit of work, they changed a lot of stuff impacting me, like console commands).
