### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by imuseless** [sailro/EscapeFromTarkov-Trainer#189]
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

"Target EscapeFromTarkov (0.12.12.17349) in A:\Games\SPTARKOV.
>> Try #1 Compilation failed for master branch.
>> Try #2 Compilation failed for dev-0.12.12.17349 branch.
Unable to compile trainer for version 0.12.12.17349. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues"

i did check the issues before posting, and i saw a couple people mention #167 but it seems to have been removed.

pls help

**Comment by sailro** [comment]
See #190
