### ISSUE TITLE
Loading Asset from AssetBundle causing crash

### ISSUE THREAD

**Issue by zpacedesu** [sailro/EscapeFromTarkov-Trainer#192]
Hi, I am currently trying to break down your source code to learn.

I am currently crashing when I am trying to LoadAsset from the bundle. This is the code:

```
                var bundle = AssetBundle.LoadFromFile(Path.Combine(Application.dataPath, "outline"));
                OutlineShader = bundle.LoadAsset<Shader>("assets/outline.shader");
```

Would be nice if you can help out, thank you.

**Comment by sailro** [comment]
You are probably missing this `outline` file in your EFT installation. It is expected when you are compiling the trainer yourself with Visual Studio.

You can either:
- use the universal install to install all dependencies for you, then building on top of that
- or you can do it manually, the `outline` file is [here](https://github.com/sailro/EscapeFromTarkov-Trainer/raw/master/Files/outline) and must be copied in your `[TARKOV_INSTALLATION]\\EscapeFromTarkov_Data`
