### ISSUE TITLE
AKI 3.0.0 ESP Problem

### ISSUE THREAD

**Issue by REALMWTH** [sailro/EscapeFromTarkov-Trainer#195]
Incorrect aligned. Tried to change FOV, doesn't fix it at all
Chams are working fine.
![2022-06-24 02-01 _364 1, 4 9, 103 4_0 0, 0 9, 0 0, 0 5_14 61 (0)](https://user-images.githubusercontent.com/1342847/175434618-9cb218a9-ab43-4c17-a18a-4143527f17f1.png)

**Comment by REALMWTH** [comment]
Update: seems that this issue is related to W2S because of DLSS

**Comment by sailro** [comment]
There is a known issue when resampling <> 1x
