### ISSUE TITLE
How to uninstall this??

### ISSUE THREAD

**Issue by Laccsss** [sailro/EscapeFromTarkov-Trainer#196]
How to uninstall this??

**Comment by sailro** [comment]
`Installer uninstall` to remove the trainer.

**Comment by Laccsss** [comment]
Where do you put this?

**Comment by Laccsss** [comment]
> `Installer uninstall` to remove the trainer.

Where do you put this?

**Comment by Laccsss** [comment]
![image](https://user-images.githubusercontent.com/35138280/175785382-af781aaa-7298-43a8-a0e5-68c84c4d046d.png)
does this mean its removed now? @sailro

**Comment by sailro** [comment]
yep

**Comment by laktis** [comment]
> 

where did you out it?
