### ISSUE TITLE
The "hit marker" only works when the "health" is on.

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#197]
It didn't work the first time I tried to use "hit marker". However, it was confirmed that it works when "health" is turned on. Can't we just use "hit marker" alone?

**Comment by sailro** [comment]
Ah that is weird, definitively a bug. I'm going to have a look.

**Comment by sailro** [comment]
Fixed here:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/998a7cd31ec78f783bc18ac973b95459fbc4d505

We were wrongly testing if the `Health` feature was enabled instead of `Hits`. :sweat_smile:
