### ISSUE TITLE
Can't save any settigns / Reset every time i relaunch

### ISSUE THREAD

**Issue by GhendraNova** [sailro/EscapeFromTarkov-Trainer#198]
Everything stated in the title, i can't seem to save any modifications and it always resets no matter what i change after i restart the game.

**Comment by sailro** [comment]
Are you using the `save` command or the `Save settings` button after changing your setup?

**Comment by GhendraNova** [comment]
The save settings in the GUI. 
should i input the save command in the console instead?

**Comment by GhendraNova** [comment]
I found the issue. Something wasn't letting me access the tarkov folder in my documents, which led it to say "Could not find a path to x\x\Documents\Escape from tarkov\Trainer.ini.

Should be fixed now

**Comment by sailro** [comment]
Ah okidoki

Perfect
