### ISSUE TITLE
Is it possible to add a breath removal function?

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#199]
Can add a function that can remove the tremor caused by breathing?

**Comment by sailro** [comment]
Do you hit this even with the `health` feature on ?

**Comment by sailro** [comment]
Do you hit this even when `Stamina` feature is `on` ?

**Comment by MongMikng** [comment]
Yes, regardless of the stamina, isn't there a slight shaking when ADS.

**Comment by sailro** [comment]
Seems to be good with this change:

https://github.com/sailro/EscapeFromTarkov-Trainer/commit/7a2e275f8056c4525be8a1e6e7159f7f1de25568
