### ISSUE TITLE
Wont load

### ISSUE THREAD

**Issue by TTVDannyg82** [sailro/EscapeFromTarkov-Trainer#20]
When i try to load in it just gets stuck on the buffering thing

**Comment by sailro** [comment]
You are using the exact specified EFT version + exact specified SPTarkov version right ?

**Comment by TTVDannyg82** [comment]
Yep

**Comment by TTVDannyg82** [comment]
> You are using the exact specified EFT version + exact specified SPTarkov version right ?

you got discord? i can screenshare! Mine is Kye#2012

**Comment by sailro** [comment]
Tried with:

- EFT v0.12.10.12192
- sptarkov v1.3.0

All working properly.

See https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/0.12.10.12192

> If you want to compile the code yourself, be sure to properly clean your solution when upgrading your EFT/sptarkov bits (even removing `bin` and `obj` folders) and to check all your references.
> Typical issue when having something out-of-sync is EFT being stuck at the loading screen with type/tokens errors in `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt`
