### ISSUE TITLE
Hoping for help, I fell into a sea of no response!

### ISSUE THREAD

**Issue by huangchenbo** [sailro/EscapeFromTarkov-Trainer#200]
Hello, I played the sptarkov version 3.0.0, but I use the https://github.com/sailro/EscapeFromTarkov-Trainer/releases after the game has no effect, please ask what you said (update the existing file accordingly) need me to do? Folder name? Or content? 
```
  D:\EFT\EscapeFromTarkov_Data\Managed\NLog.dll.nlog- ->>D:\EFT\EscapeFromTarkov_Data\Managed\NLog.dll.nlog-sptarkov
 ```
```
  <targets>
  NLog.dll.nlog-sptarkov
  <target name="EFTTarget" xsi:type="EFTTarget" /></targets>
</nlog>
```

**Comment by sailro** [comment]
Hello,

You are mixing manual instructions for installing the trainer and the universal installer (which is able to do everything for you automatically).

Now that you screwed your `Nlog.dll.nlog` file, I suggest you remove it and try to re-run the Universal installer.

Please read instructions next time and try to understand what you are doing :)
