### ISSUE TITLE
wallhack function - need to be updated

### ISSUE THREAD

**Issue by bauhiniak** [sailro/EscapeFromTarkov-Trainer#202]
I have installed the trainer with version 0.12.12.18346 SPT AKI 3.0 .
since there are USEC rogue invasion  scenario, I suggest add more faction slot to wallhack, since I found that USEC PMC and Rouge currently use the same slot.

[trainer.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/9079695/trainer.txt)

**Comment by Trissssss** [comment]
I have a different problem with the wallhack. The different USEC PMCs have the same bone/box colors as the bosses.

**Comment by sailro** [comment]
Fixed here:
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/474
