### ISSUE TITLE
Better crosshair?

### ISSUE THREAD

**Issue by NikIkle** [sailro/EscapeFromTarkov-Trainer#204]
Suggestion. A dynamic crosshair, as in the mod from untitledSPT, would be excellent because the weapons in this game are not laser guns (unfortunately, mod is outdated).

here's video with this mod
[https://youtu.be/W56z6mTprl4](url)

**Comment by sailro** [comment]
You can dynamically setup your crosshair using the in-game trainer GUI.

**Comment by NikIkle** [comment]
I am aware of the crosshair settings, but there are only a couple of them and they don't do what i need. I mean a crosshair that works like a laser and follows the muzzle of the gun, you can clearly see what i mean in the attached video

**Comment by sailro** [comment]
Okidoki

**Comment by NikIkle** [comment]
Thanks!
