### ISSUE TITLE
No trainer.ini file when installing

### ISSUE THREAD

**Issue by Quinnnnnq** [sailro/EscapeFromTarkov-Trainer#205]
i noticed that trainer.ini file won't create itself so there's no way to save settings.After the file was manually created,"load settings" function works well.(i have re-installed the trainer but before the file was created,it's still not working)

**Comment by anotherbeardman** [comment]
Have you received any feedback yet. im having the same issue. go to save the setting and the trainer.ini file doesnt exist

**Comment by sailro** [comment]
By design we do not create the trainer.ini until settings are saved. I think we already spotted an issue if the game is missing proper rights to write in your document folder. Could you double check ?

**Comment by Vardigard** [comment]
> i noticed that trainer.ini file won't create itself so there's no way to save settings.After the file was manually created,"load settings" function works well.(i have re-installed the trainer but before the file was created,it's still not working)

Check the direcotry
`%USERPROFILE%\Documents\Escape from Tarkov\`

If not exists, the create it.

And then ingame use "Save" feature of the trainer. After then trainer.ini will be created.

And sorry for my english.

**Comment by Quinnnnnq** [comment]
tested on SPT-AKI 3.0.0.Now everything works great and changes were saved.i think this bug only happens on ver2.3.1?

**Comment by Quinnnnnq** [comment]
i think this needs more investigates.does anyone still playing on SPT-AKI 2.3.0 or 2.3.1?

**Comment by sailro** [comment]
I updated the installer to auto-create the folder now
