### ISSUE TITLE
opening the installer in SPT-AKI folder 3.0.0 has cannot show selection prompt since the current terminal does not support ansi escape sequences error

### ISSUE THREAD

**Issue by oceanbandit** [sailro/EscapeFromTarkov-Trainer#207]
What the title says, can you upload the required files to unzip directly into the folder of the game since it doesnt even recognize the SPT installation when i run the installer outside of the folder? Thank you

**Comment by sailro** [comment]
The installer does not unzip a payload, it compiles on the fly the trainer after downloading the source. And I do not understand the issue title, could you give more information please ? I was perfectly able to install into SPT-AKI 3.0

**Comment by oceanbandit** [comment]
https://imgur.com/a/iL64vqy
^pic related is what the issue title means, this happens when i try to run the installer inside my SPT-AKI main folder, i placed it in there because it seems when i run the installer outside the folder it only detects my escape from tarkov live installation instead and if press Y, it doesnt continue searching for other installations, instead it just attempts to install the trainer in the EFT live folder(which it fails because of some connection issues according to this pic https://imgur.com/a/RmFpZzK
i hope this clears things out for you

**Comment by sailro** [comment]
What OS are you using?

**Comment by oceanbandit** [comment]
windows 7 home premium 64bit

**Comment by sailro** [comment]
That why, for all the CLI stuff we are using `Spectre.Console`. Some functionality in `Spectre.Console`, such as some prompts, requires a terminal that knows how to interpret VT/ANSI sequences. Sadly, cmd.exe in versions prior to Windows 10 (build 16257) does not support that.

**Comment by oceanbandit** [comment]
so is there an alternative way for me to install the trainer? like putting the .dll and nlog and .ini stuff in a .rar/zip file and just unzip in their proper paths?

**Comment by sailro** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer#manual-installation
