### ISSUE TITLE
I'm sorry, but I want to know how to install this program in spt. How do I install it?....

### ISSUE THREAD

**Issue by babyshhoter** [sailro/EscapeFromTarkov-Trainer#209]
How do I install this method? I tried to control it, but I don't know how to do it.Can't you tell me how, uh...

**Comment by sailro** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer/releases

**Comment by babyshhoter** [comment]
I can't create a trainer.ini, how do I set the key? Can't you force creation?

**Comment by ajdrigs** [comment]
> I can't create a trainer.ini, how do I set the key? Can't you force creation?

Use the Right ALT to open the trainer, Set everything how you want then click save, and it should create the .ini, under documents/Escape from Tarkov, If you're using this for SPtarkov and don't have a folder under Documents, create a folder called "Escape from Tarkov" Just like that, Now try to save the settings and it should save your settings to an ini.
