### ISSUE TITLE
help with the track feature for items

### ISSUE THREAD

**Issue by Pullermann124** [sailro/EscapeFromTarkov-Trainer#210]
track trackr and tracksr all do the same and only show some more common items like ak gastubes or 560mm shotgun barrels could someone explain how to use the tracker correctly? and if its possible to track specific items?

**Comment by westteam1** [comment]
I also want to know more commands to search for items.

**Comment by sailro** [comment]
Make sure loot is enabled: `loot on` in the command bar, or using the GUI (Right Alt)

Use `list *` to display all loot.

Use `track <item>` (trackr / tracksr if you want to filter on rarity).

Use `tracklist` to check your current tracking list.

Everything is already explained on the main page.
