### ISSUE TITLE
After install of trainer, spt doesn't recognize the game. 

### ISSUE THREAD

**Issue by ItsDrLuxx** [sailro/EscapeFromTarkov-Trainer#211]
Basically as the title says, 
SPT worked with mods before installing the trainer. After installing the trainer (using universal installer), spt wont start and says "In order to use spt you need to buy the game, support the developers."
I've reinstalled eft and spt tried it with vanilla and still get the same issue.

**Comment by sailro** [comment]
What is your spt version?

**Comment by Kowalskyy** [comment]
I have same problem. spt 2.3.1

**Comment by ItsDrLuxx** [comment]
3.0.0 / eft is 12.12.18346

**Comment by ItsDrLuxx** [comment]
So after another uninstall reinstall, the updater says it installbed but I get another error saying: 

Mono path[0] = 'E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Managed'
Mono config path = 'E:/Games/SPT-AKI 3.0.0/MonoBleedingEdge/etc'
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/lib/usr/lib/libSystem.dylib.dll
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/libc.so.6
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/libc.so.6.dll
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/libc.so.6
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/data-000001A21DC2C8B0.dll
Fallback handler could not load library E:/Games/SPT-AKI 3.0.0/EscapeFromTarkov_Data/Mono/data-000001A2224E0080.dll
Initialize engine version: 2019.4.39f1 (78d14dfa024b)

Hopefully that's helpfull. I've used this in the past with spt and it's worked flawlessly. If there's anything else I could send you to help troubleshoot this issue let me know. Also included my player log.
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/9180323/Player.log)
.

**Comment by sailro** [comment]
Try to upgrade to spt-aki 3.1.0 perhaps. I do not repro on my side, so I think you have an issue with your setup.

There is nothing related to us in your player log unfortunately.
