### ISSUE TITLE
fps drop 12.12.15.18346

### ISSUE THREAD

**Issue by zak0vich** [sailro/EscapeFromTarkov-Trainer#212]
i'm using version 12.12.15.18346 and once i enter map and npc spown fps drop form 120 to 60 - 50 
any way to fix this ?

**Comment by sailro** [comment]
Do you repro without the trainer? Like it is known to have a FPS drop with spt-aki when ennemies are spawned.

**Comment by zak0vich** [comment]
> Do you repro without the trainer? Like it is known to have a FPS drop with spt-aki when ennemies are spawned.

yes but from 120 to 90 max if i chosse hard AI amount 
with trainer on hard amount i have under 60 fps drop

**Comment by sailro** [comment]
Same as https://github.com/sailro/EscapeFromTarkov-Trainer/issues/288
