### ISSUE TITLE
Loot not showing. SPTarkov AKI 3.0.0

### ISSUE THREAD

**Issue by ajdrigs** [sailro/EscapeFromTarkov-Trainer#213]
For some reason loot isn't showing for ESP, I put the uni installer 1.9 in my 3.0.0 directory, and ran the .exe which seems to have worked fine, I also had played before running the installer as well.

**Comment by sailro** [comment]
it is working for both 3.0.0 and 3.1.0. Please read the docs. You have to use `track` command.

**Comment by ajdrigs** [comment]
Ah, I didn't realize I needed to use that.

**Comment by ajdrigs** [comment]
> it is working for both 3.0.0 and 3.1.0. Please read the docs. You have to use `track` command.

Is it possible to clear my console? So there's not a bunch of text etc.
