### ISSUE TITLE
Free Camera Not Working

### ISSUE THREAD

**Issue by Elicit2** [sailro/EscapeFromTarkov-Trainer#215]
When I was in the hideout at the firing range it didn't allow me to move the free camera. I'm not sure if this is a issue with SP-Tarkov or the trainer itself. Also, I didn't try to free cam in raid because I haven't had enough time to even play videogames as of late. Also I'm on version 3.0.0 on SP-Tarkov if that helps.

**Comment by sailro** [comment]
Yep it was only designed for in-game raids.
