### ISSUE TITLE
esp

### ISSUE THREAD

**Issue by OneSneakyTurtle** [sailro/EscapeFromTarkov-Trainer#216]
i used the auto installer and my esp for all player/scavs is off, and loot, but the chams is fine. wondering how i can fix it.
![Escape From Tarkov Screenshot 2022 07 25 - 14 52 24 94](https://user-images.githubusercontent.com/109991216/180868210-963c6f28-b78e-4c5d-88e6-f83df80143f4.png)

**Comment by sailro** [comment]
You probably have the game gfx settings with resampling <> 1x. We have an open issue about that

**Comment by OneSneakyTurtle** [comment]
i changed my resampling to 2x and it fixed it thanks
