### ISSUE TITLE
3.1.1 vs installation error

### ISSUE THREAD

**Issue by lukeclegs** [sailro/EscapeFromTarkov-Trainer#218]
I used the auto installer and it appears that it installed it with 3.1.1, but when i open the game, i can't get the menu to appear. It is probable the fault is on my end, I just don't know how to fix it.

**Comment by lukeclegs** [comment]
So if i dig into the files, i can see the trainer .dll file, but the GUI doesn't  open using the right "alt" key.

**Comment by sailro** [comment]
You should have a look here: https://github.com/sailro/EscapeFromTarkov-Trainer#manual-installation

Perhaps the nlog file is not correct?
