### ISSUE TITLE
Loot not showing 

### ISSUE THREAD

**Issue by W1cke4d** [sailro/EscapeFromTarkov-Trainer#220]
Hello guys ,
I have the problem when I select the Loot enable option( in the guy) it doesn't show me any lot nearby even when I set the radius to 300
Every other feature like stash/wh is working perfectly thank you.
Regards 
Max

**Comment by W1cke4d** [comment]
I figured I should use the track command but the console is not opening up..
An another questions is it possible to track quest relevant items which need to be found in raid ?
Thanks again

**Comment by W1cke4d** [comment]
So if i open up the ingame console and try the track commands with loot enabled it doenst work anyone has any ideas?

**Comment by sailro** [comment]
`track *` is probnably what you want

**Comment by sailro** [comment]
> I figured I should use the track command but the console is not opening up.. An another questions is it possible to track quest relevant items which need to be found in raid ? Thanks again

`quest` command. Please read the docs, everything is explained here.
