### ISSUE TITLE
12.12.16778

### ISSUE THREAD

**Issue by BananaMana211410** [sailro/EscapeFromTarkov-Trainer#221]
I try to run the install for the trainer, but it gives me this message "Unable to compile trainer for version 0.12.12.16778."

**Comment by BladeOfGodSlayer** [comment]
yeah, i had the same issue about that

**Comment by BananaMana211410** [comment]
when is the issue going to be fixed?

**Comment by BladeOfGodSlayer** [comment]
I am still having that pronlem :(

**Comment by BananaMana211410** [comment]
I guess we just wait until there is like a patch or update or something like that.

**Comment by BananaMana211410** [comment]
I will leave the post open until it is fixed or if I find a solution

**Comment by datek11** [comment]
i feel like all 3 of us have the same reason we care about this particular version of the game

**Comment by BladeOfGodSlayer** [comment]
This that bug still there?

**Comment by sailro** [comment]
I do not plan to support those old versions. 

`master` branch can build against `EFT 0.12.12.19428` (tested with [`spt-aki Version 3.2.2`](https://hub.sp-tarkov.com/files/file/6-spt-aki/#versions)). If you are looking for another version, see [`branches`](https://github.com/sailro/EscapeFromTarkov-Trainer/branches) and [`releases`](https://github.com/sailro/EscapeFromTarkov-Trainer/releases).

If the version is not listed (and old), then I will not support it.
