### ISSUE TITLE
Pink textures

### ISSUE THREAD

**Issue by HaxIsGone** [sailro/EscapeFromTarkov-Trainer#222]
Hi there, is there an option to disable Pink textures of NPC's ?
only from time to time they are normal.
Version: SPTAKI 3.0.0

**Comment by ethanjia** [comment]
wallhack feature was disturbed by all bots' Pink Charms Textures
Version: SPTAKI 3.1.1

**Comment by HaxIsGone** [comment]
yep, as soon as i stoped using WH they are normal - thanks :D PS: DLSS was off.

**Comment by gaaxrus** [comment]
Reinstall game client, using Installer.exe and now have the same issue pink texture with WH. DLSS is off. Before this WH warks fine, maybe some trainer update broke WH.

**Comment by gaaxrus** [comment]
ok i find out why its dont work. Universal installer create empty Outline file in EscapeFromTarkov_Data folder. Download it from repository and replace it, now WH works again

**Comment by sailro** [comment]
I'm going to add this to the known issues.
