### ISSUE TITLE
NVG and Thermals

### ISSUE THREAD

**Issue by insanebook** [sailro/EscapeFromTarkov-Trainer#225]
Does anyone have any idea on how to fix the NVG and Thermal glitch? I understand this has been a bug for over a year now, so I'm assuming that it's pretty hard to fix. But I remember when SPT 3.1.0 just dropped the night vision option was gone for a bit and NVG worked fine, so I was wondering if there is a way to remove those options and make the NVGs work. And I know that there is a night vision and thermal option, but I just prefer the in-game one. I am such an illiterate when it comes to anything revolving coding, so it would be great if anyone could help me out.

**Comment by ZhevlakovII** [comment]
While the pull request from Chishiki is being tested, I propose a slightly stupid, but workable solution.
To completely disable NV and Thermal, you need to delete Night Vision.cs and ThermalVision.cs, after which you need to build the project.
I found such a solution a long time ago and it is not correct, but as a temporary measure it will work perfectly.
Sorry for my bad English.

**Comment by sailro** [comment]
I tested the PR and it is not working as expected or I'm missing something.

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/pull/246

This should be fixed now. When wearing a compatible equipment (like NV googles), the trainer will not interact anymore.

**Comment by sailro** [comment]
@ZhevlakovII it should work as expected now, but if needed you can now disable Features on the command line using the new installer:
`Installer -d NightVision -d ThermalVision`
