### ISSUE TITLE
Loot Option not working 

### ISSUE THREAD

**Issue by ZaneVande** [sailro/EscapeFromTarkov-Trainer#232]
First, I want to say I love the work on this. Everything is working as intended except the Loot function.

No matter what I use to try and get it to work, it just doesn't. The command in console doesn't work, the in-game interface shows that it's enabled and color a light blue but doesn't actually work for me, even changing the distance doesn't work. 

This mod was installed with your installer for record.

**Comment by SlurpingHydra** [comment]
Does not seem to work for me either.

**Comment by ZaneVande** [comment]
Ok so turn "Loot" on and then in command type "track *" and then all the loot shows up on screen in light blue (or whichever color)?
