### ISSUE TITLE
auto installer not working

### ISSUE THREAD

**Issue by 3bodi21352** [sailro/EscapeFromTarkov-Trainer#235]
hey! i found this trainer good for my spt tarkov version so i download the auto installer but i get this error message:

Target EscapeFromTarkov (0.12.12.16778) in D:\Escape From Tarkov spt
>> Try #1 Compilation failed for master branch.
>> Try #2 Branch dev-0.12.12.16778 not found.
Unable to compile trainer for version 0.12.12.16778. Please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues

so does manual installation work with this version if yes how can i install it?

**Comment by 3bodi21352** [comment]
i mean if i download for examble dev-0.12.12.16584 version manually will the trainer work successfully?

**Comment by datek11** [comment]
there's already an issue about it: https://github.com/sailro/EscapeFromTarkov-Trainer/issues/221

**Comment by datek11** [comment]
> ignore it i solved the problem

what did you do to fix it?

**Comment by 3bodi21352** [comment]
i simply copied the latest version from my live eft
