### ISSUE TITLE
Version 1.9 "Camera" Feature Issue With Releases of SPT-AKI 3.2.2

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#236]
For me, most all the version 1.9 features were working every SPT-AKI release from game version 0.12.12.15.17107 (11 Mar 2022) *** add SPT-AKI 2.3.0 thru 0.12.12.30.19078 (19 Jul 2022) *** add SPT-AKI 3.2.1.  With the newly released SPT-AKI 3.2.2 for game version 0.12.12.31.19428 (23 Aug 2022), I immediately noticed the "camera" feature was effected.  It still works (you can move and teleport), but as soon as you press the key to activate it, half the "environment" disappears.   Makes it hard to move and select a place to teleport to.  So far with v1.9 and SPT-AKI 3.2.2, that is the only issue I have seen after a few hours of usage and testing.   Thanks.

**Comment by sailro** [comment]
I'm going to have a look

**Comment by underlines** [comment]
SPT-3.2.2-19428
0.12.12.31.19428

Cam feature works without problem. Environment isn't disappearing.
What's more difficult, is the Night Vision / Thermal bug. But I saw there's already a pullrequest. Hope it's updated soon.

**Comment by RogueTech67** [comment]
> nvironment isn't disappearing



> SPT-3.2.2-19428 0.12.12.31.19428
> 
@sailro, thank you sir. 

@underlines , that's a little disconcerning.  I put a clean copy of 0.12.12.31.19428 and SPT-AKI 3.2.2, ran the game once to create the profile, started the game, closed it, and ran the trainer installer.exe again to recompile and download the files.  I'm still seeing the same issue.  As soon as you press the key to activate the camera, most of the structures (over half) disappear.  They reappear as soon as you press the key again to exit camera mode.  I have clean (saved off copies) of the BSG games files from all the way back to 0.12.12.15.17107 (11 Mar 2022) *** add SPT-AKI 2.3.0, and every one has worked fine.  Nothing has changed on my end  (same laptop i5-10300 / 8GB / Nvidia GTX 1660 Ti (6gb)), and always have the latest Nvidia drivers.  The camera worked without having the environment objects disappear up to and thru SPT-AKI 3.2.1.   I hope sailro can reproduce the issue I'm having starting with 3.2.2.  Thanks

**Comment by sailro** [comment]
I confirm it is working properly (tested with spt 3.2.3).

Make sure you are not using key bindings in conflict with something else (like I was using f12 for camera, and now spt-aki is  using f12 with their plugin system)

**Comment by RogueTech67** [comment]
Sailro, Well thanks for verifying it works for you, but it simply is not for me.  I've done the same steps from all the way back to SPT-AKI 2.1.2, and neveer had this issue until SPT-AKI 3.2.2/3.2.3.  I just reinstalled my laptop clean, and still the issue is there.  The only thing I can think of is maybe the issue is due to me only having 8GB of ram.  With only the game running, my laptop usually is around 7.6/8.0GB used when running the game.  I love this trainer and use it mainly because I'm no good remembering maps, and need the exfil locations.   The camera and moving around in the map is just a bonus for me.  Again, all the other Trainer features still workfine, it's just the camera function causes half of the environment (the buildings, tracks, etc) to literally disappear when the camera is activated.  I can still move/fly and land on the buildings even though they are not seen while moving.  Just weird.  I've tried everything I can think of.  If it is working for you, then it has to be my hardware.  Thanks again.

HP Pavilion Gaming Laptop 16-a0032dx
10th Gen Intel Core i5-10300H (Quad-Core, 2.5 GHz Up to 4.5GHz, 8MB Cache)
16.1-inch diagonal FHD, 144 Hz, IPS, anti-glare, micro-edge, WLEDbacklit, 300 nits, 72% NTSC (1920 x 1080)
DDR4-3200 SDRAM 8GB (2x4GB) - 4GB 1Rx16 PC4-3200AA-SC0-11 (** 32GB max)
512 GB Intel SSD + 32 GB Intel Optane memory (Hybrid M.2 2280 NVMe Drive By Intel)
NVIDIA® GeForce GTX 1660 Ti - 6 GB GDDR6 dedicated Memory; Max-Q design

ONLY Did the following:
- Reinstalled Windows 10 Home 21H2 and all updates
- Installed Nvidia Drivers 516.94 (latest)
- Downloaded Battlestate Games - BsgLauncher
- Downloaded and installed current game version 0.12.12.31.19428
- Downloaded and installed/copied SPT-AKI 3.2.3 files
- Ran game setup (Aki.Server.exe) then (Aki.Launcher.exe)
	- Profile: User1 - Edge of Darkness version
- Launched the game and chose USEC
- Ran one PMC raid in [Customs] and died
- Exited the game
- Ran the Trainer (Installer.exe)
- Created the Documents\Escape from Tarkov directory (not created by default)
- Launched the game, pressed [Right-Alt], set the camera key to [Right-Ctrl]
- Ran a PMC raid in [Customs], pressed [Right-Ctrl], and half the environment disappears
- Note:  All EFT default game/key settings, tried different camera keys, nothing worked after SPT-AKI 3.2.1
- Note: My son has a 16GB gaming laptop, will try it on his when I have a chance
