### ISSUE TITLE
Suggestion: Track wishlist option

### ISSUE THREAD

**Issue by ajdrigs** [sailro/EscapeFromTarkov-Trainer#237]
Title, I think it would be super helpful, for building the hideout up.

**Comment by sailro** [comment]
If only a doc was available on the very first page of this website :)

![image](https://user-images.githubusercontent.com/638167/187761235-55fbfae5-c547-436c-bb0b-b64d695c2151.png)

**Comment by ajdrigs** [comment]
> 

Oh I'm sorry, I miss read that command, I got it confused with "list" I thought if I did loadwl it would list my wish list items in the console showing if they were in my raid or not.

**Comment by sailro** [comment]
No worries :)
