### ISSUE TITLE
short GLITCH every few seconds. Any chance to avoid it?

### ISSUE THREAD

**Issue by bleeee** [sailro/EscapeFromTarkov-Trainer#239]
screen a bit freeze every few seconds, data collection and transfer  I suppose.
Any chance to avoid it?

**Comment by sailro** [comment]
All maps or a specific one?

**Comment by ingu88** [comment]
Obviously, the "track item" causes frame drops as the list is updated every few seconds.
so you need some setup your config file (**trainer.ini**) or in-game gui (Default key for in-game GUI is Right-Alt)

check this:
[How to create configuration file](https://github.com/sailro/EscapeFromTarkov-Trainer#sample-trainerini-configuration-file)


if got the trainer.ini open the text editor and change value
```ini
; loot - recommend change it higher
EFT.Trainer.Features.LootItems.CacheTimeInSec=3.0

; quest - recommend change it higher
EFT.Trainer.Features.Quests.CacheTimeInSec=5.0

; if you can't open GUI then change this
EFT.Trainer.Features.Commands.Key="RightAlt"
; key code : https://docs.unity3d.com/ScriptReference/KeyCode.html
```
