### ISSUE TITLE
trouble with installer

### ISSUE THREAD

**Issue by saintz1122** [sailro/EscapeFromTarkov-Trainer#240]
hi. i tried to install this trainer but it didn't work and right now i have no idea how to solve this.
so here is my walkthrough

1. i was using spt-aki. and it said i need to start the eft first. so i start the sp tarkov and original tarkov first

2. and then i start the installer however the installer always choose the original tarkov directory instead spt-aki directory
    and yes when i put the installer in spt-aki folder  it show this message.
--------------------------------------------------------------------------------------------------------------------------------------------     
   (Discovering Escape From Tarkov installations...
      Error: Cannot show selection prompt since the current terminal does not support ANSI escape sequences.. Please file an
      issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues

      Press a key to exit...)
-------------------------------------------------------------------------------------------------------------------------------------------- 
3. so i test the installer in original tarkov directory to find out 'is this installer even working?' and fortunately it install the trainer

4. and i move these files (outline, 0Harmony.dll, NLog.dll.nlog, NLog.EFT.Trainer.dll) to spt-aki directory 
    because installer won't install the trainer program in spt-aki folder directly

5. after install those files, i start the game and when i press the 'right-alt' key to open the trainer menu but it won't work

6. and i tried to find the solutions in trouble shooting, issues sessions. make the trainer.ini manually, check the player.log
  and it still won't work

and i out of ideas how to solve this

[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/9542140/Player.log)
[Player-prev.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/9542141/Player-prev.log)

**Comment by sailro** [comment]
Are you on Win7 ? The error message (Cannot show selection prompt since the current terminal does not support ANSI escape sequences) implies the installer did not even try to install everything.

I fear you have to compile the bits by yourself. See manual installation instructions on the main page

**Comment by saintz1122** [comment]
no i'm using windows 10 pro.

alright. i will try to install the trainer manually again.
