### ISSUE TITLE
install problem again

### ISSUE THREAD

**Issue by saintz1122** [sailro/EscapeFromTarkov-Trainer#241]
well i try to install this trainer with installer and it didn't work.
i try to install it manually with compiling the installer or source files.
but i have no experiences about coding or compile the source files.

can you or somebody please share the trainer files instead source files?

**Comment by sailro** [comment]
Why the installer is not working?

Having binaries to share is a pain because we need to recompile for every EFT version. That's why the installer is here: to compile everything needed directly on your machine.

**Comment by saintz1122** [comment]
first i start the sp tarkov first and use the installer at spt aki directory and it give me this message.
[installer error.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/9561735/installer.error.txt)

and also this
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/9561730/Player.log)

and no, i'm not using windows 7. i'm currently using windows 10 pro.

so i use the installer at live tarkov directory. somehow it installed, so i move the trainer files 
was intalled in live tarkov folder to spt aki directory.
however the trainer didn't work. when i press right-alt it didn't show the Commands or gui or anything.
and none of the trainer console commands work

after this, i try your suggestion compile the bits my self with following manual install instruction
but i dont know how to do this.

so that's why i ask to you or someone who install the trainer successfully with installer, share the installed trainer files.
but after you explain the reason why you can't share the installed trainer files 
and i out of ideas how to solve this problem.

**Comment by sailro** [comment]
For all the CLI stuff we are using Spectre.Console. Some functionality in Spectre.Console, such as some prompts, requires a terminal that knows how to interpret VT/ANSI sequences. Sadly, cmd.exe in versions prior to Windows 10 (build 16257) does not support that.

**Comment by saintz1122** [comment]
that means there is no solution in this problem.

anyway, thank for the answer.
