### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by GMSifi** [sailro/EscapeFromTarkov-Trainer#242]
I accidentally installed it on Live, which files do I remove to restore it back to "unmodified for trainer"?

Thanks :)

**Comment by sailro** [comment]
simply use the installer: `installer uninstall`

**Comment by jebediahtoblerone** [comment]
where do i type installer uninstall

**Comment by solareon** [comment]
> where do i type installer uninstall

Wherever you have the trainer installer located. If you placed it in the root of the tarkov folder then you'd run it from there

**Comment by exdag2** [comment]
run what?

**Comment by exdag2** [comment]
> > where do i type installer uninstall
> 
> Wherever you have the trainer installer located. If you placed it in the root of the tarkov folder then you'd run it from there

run what, exactly?

**Comment by sailro** [comment]
run the _trainer-installer_ with the uninstall argument, everything is explained here:

https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-3.5

In the `Usage examples` section.
