### ISSUE TITLE
Wallhack settings

### ISSUE THREAD

**Issue by slavurus** [sailro/EscapeFromTarkov-Trainer#247]
Извините, мне 63 года, восхищен вашим трейнером. Играть в Тарков с больным сердце просто опасно, а вы предоставили мне возможность насладиться игрой. 
   Теперь вопрос. Можно ли исключить видение сквозь стены и оставить  выделение силуэтов видимых врагов например как в Warface ? 

Sorry, I'm 63 years old, I admire your coach. It is simply dangerous to play Tarkov with a sick heart, and you have given me the opportunity to enjoy the game.
Now the question. Is it possible to exclude the vision through the walls and leave the silhouettes of visible enemies , for example , as in Warface ?

**Comment by sailro** [comment]
Yes you can tweak the settings, using the in-game menu (default key is `RightAlt`), in the `Wallhack` tab:

Try to disable `XRay Vision` and `Show Boxes`.

![Screenshot 2022-02-08 20 38 20](https://user-images.githubusercontent.com/638167/191459042-d9fc2719-77b5-4668-8c9e-ee2651a34dc1.png)

See the difference:

![Screenshot 2022-02-08 20 37 01](https://user-images.githubusercontent.com/638167/191459255-fff4360d-22a1-432f-aa96-f116dbb260a4.png)

![Screenshot 2022-02-08 20 37 35](https://user-images.githubusercontent.com/638167/191459306-5b377c3e-9b15-4c47-b782-5cdcc5ddee68.png)

**Comment by slavurus** [comment]
!!!!!!   Если разберусь - это превосходно !!!!    ВЫ ИЗ ИГРЫ ДЕЛАЕТЕ УНИВЕРСАЛЬНЫЙ ШЕДЕВР .   ОГРОМНОЕ СПАСИБО

**Comment by slavurus** [comment]
Я не богат, но хотел бы хоть чуть чуть проспонсировать. Дайте ссылочку.

**Comment by sailro** [comment]
https://github.com/sponsors/sailro

**Comment by slavurus** [comment]
ЗТО ПРОСТО МЕЧТА ВСЕХ ПОДСЛЕПОВАТЫХ!!!!!  ВЫ ДЕЛАЕТЕ ИГРУ ВОСХИТИТЕЛЬНО УНИВЕРСАЛЬНОЙ. ОГРОМНОЕ СПАСИБО.
