### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by MigSDev5** [sailro/EscapeFromTarkov-Trainer#25]
Hello 
Is it possible to add a god mode system?
thx

**Comment by sailro** [comment]
Yes, well at least something similar. 

I added a feature to disable collisions, so you are immune to enemy fire (bullets will pass through you), grenades, barbwire...

I'm going to push this soon to the repo.

**Comment by sailro** [comment]
Done!

Feature here:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/ea6a6436e7ccdff5f098ba77128e0e2ab8503790

Included in the latest release for EFT `0.12.10.12528` and sptarkov `1.4.1`
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/0.12.10.12528

**Comment by sailro** [comment]
Use `nocoll on` in the console to disable physical collisions
