### ISSUE TITLE
ESP Boxes + aimbot 

### ISSUE THREAD

**Issue by CleanSoftwareSolutions** [sailro/EscapeFromTarkov-Trainer#252]
The ESP Boxes are not rendered over their targets and the informations text is just at the bottom of the screen. maybe a resolutionbug? playing on 1440p borderless. also the aimbot seems not to work for me. tried different keys but no one seems to work.

**Comment by sailro** [comment]
Probably a duplicate of those:

https://github.com/sailro/EscapeFromTarkov-Trainer/issues/149
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/230
