### ISSUE TITLE
UI bug?

### ISSUE THREAD

**Issue by demir-pl** [sailro/EscapeFromTarkov-Trainer#253]
Hello

i don't know if this is the issue (haven't found anything) or just me but my trainer doesn't look like those on screenshots
is this normal?

![image](https://user-images.githubusercontent.com/89728477/197011491-39dec607-4791-44e8-8274-3aaf76417403.png)

**Comment by sailro** [comment]
This screenshot is super old.

**Comment by demir-pl** [comment]
got it so this is the version i understand...
