### ISSUE TITLE
No EscapeFromTarkov installation found, please re-run this installer, passing the installation path as argument

### ISSUE THREAD

**Issue by franky58-coder** [sailro/EscapeFromTarkov-Trainer#255]
![image](https://user-images.githubusercontent.com/66449820/198414398-6737523e-26fa-461c-98dc-03a94c2bed2d.png)
Help pls

**Comment by sailro** [comment]
And so did you try to pass the installation path as argument ?

**Comment by franky58-coder** [comment]
I tried several different things by looking up on youtube but it did not work ... :/ How do I pass the installation path as argument ?

**Comment by sailro** [comment]
Instead of double-clicking on the exe directly. either:
- copy the executable file in the target EFT folder
- or run `cmd` then use `Installer "C:\Battlestate Games\EFT"` to install the trainer, adding C:\Battlestate Games\EFT to the search list for example.
