### ISSUE TITLE
Loot

### ISSUE THREAD

**Issue by AWES0ME1** [sailro/EscapeFromTarkov-Trainer#256]
Is there a current issue with the loot option? It is not working at all.

**Comment by sailro** [comment]
Hello. Did you read the documentation on the main page. Are you aware of `track` and `tracklist` commands?

**Comment by JMMarsh-GoldenAspens** [comment]
I see! Thank you for explaining this, and great work!!


I was banned on my primary, is this detectable by BatteEye?

**Comment by sailro** [comment]
See the main readme:

_I'm not responsible for any consequences that result from using this code. BattleState / BattlEye will ban you if you try to use it 'live'._

The main goal is to use it with sptarkov / offline.
