### ISSUE TITLE
Uninstall command issue (Spectre.Console related issue)

### ISSUE THREAD

**Issue by sxtj** [sailro/EscapeFromTarkov-Trainer#263]
I open a git bash on my desktop and run the following command, ./Installer.exe uninstall "C:/Battlestate Games\EFT", and it gives me the error,  "Error: Cannot see if a key has been pressed when either application does not
have a console or when console input has been redirected from a file. Try
Console.In.Peek.."

**Comment by sailro** [comment]
Indeed the installer is not working from `git bash` please use `cmd.exe` instead as a workaround

**Comment by sailro** [comment]
Nothing more to do on our side.
