### ISSUE TITLE
SSL / TLS

### ISSUE THREAD

**Issue by Krevetka30** [sailro/EscapeFromTarkov-Trainer#266]
![image](https://user-images.githubusercontent.com/91633792/206512694-b84c9cac-1c3e-45df-9a88-880510ff9273.png)
Help to fix it pls.

**Comment by sailro** [comment]
What is your OS and version ?

**Comment by sailro** [comment]
A dupe of https://github.com/sailro/EscapeFromTarkov-Trainer/issues/81
