### ISSUE TITLE
Error for startint installer

### ISSUE THREAD

**Issue by Dragemko** [sailro/EscapeFromTarkov-Trainer#268]
Windows 11. 
Continue with EscapeFromTarkov (0.12.12.20765) in C:\games\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.12.12.20765) in C:\games\EFT.
Error: Could not establish trust relationship for SSL/TLS secure channel.
Error: Could not establish trust relationship for SSL/TLS secure channel.
Unable to compile trainer for version 0.12.12.20765. Please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues   

What problem? :(

**Comment by sailro** [comment]
Using a proxy or somthing intercepting HTTPS traffic? like Fiddler?

**Comment by sailro** [comment]
Closing stale issue.
