### ISSUE TITLE
The trainer is no longer loaded automatically - after 0.13.0.21523

### ISSUE THREAD

**Issue by saiss048** [sailro/EscapeFromTarkov-Trainer#270]
I tried it a day before wipe and it worked fine but as soon as the update happened, the trainer doesn't load.  I press RightAlt and nothing happens and the commands don't work either. I tried looking at the EFT instance and couldn't find anything out of ordinary. Installer works fine but I'm not sure what's wrong.

![Capture](https://user-images.githubusercontent.com/121639870/210118818-8bd2e944-888e-42e8-ac71-1dcd7d45256b.PNG)

**Comment by saiss048** [comment]
^Playing on live tarkov btw

**Comment by ducksquaddd** [comment]
Having this issue as well

**Comment by Vanadier** [comment]
A) The project is not meant for use on live, and will get you banned neigh immediately.

B) The project this code is meant to be used on does not even support patch 0.13 yet, why would you expect this to be updated for said patch?

**Comment by saiss048** [comment]
A) no shit I can read the README

B) idk nobody else commented on it other than me so I asked

**Comment by ducksquaddd** [comment]
A > ive read the documentation 

B > Dont know

**Comment by sailro** [comment]
Thanks @solareon 

I did not had the time to check but I exactly thought of that when I saw this issue.

**Comment by sailro** [comment]
We can probably find a way to write a spt-aki module like discussed [here](https://github.com/sailro/EscapeFromTarkov-Trainer/issues/41) initialy.

It's now probably different given they moved to [BepInEx](https://github.com/BepInEx/BepInEx) during 3.x, but that's a way to load the trainer easily, instead of IL patching assemblies.
