### ISSUE TITLE
How do you build project locally?

### ISSUE THREAD

**Issue by quadlol** [sailro/EscapeFromTarkov-Trainer#272]
Hi, I have tried to build the project locally and create a DLL out of it but the 3rd party libraries are not included. How do I link them? (using VS Studio)
![image](https://user-images.githubusercontent.com/38984247/210243889-ccb6ff23-bc61-4fa3-a33f-fea7bfdc2ade.png)

Thanks :)

**Comment by sailro** [comment]
They are included in your EFT installation,

Update your project file accordingly:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/NLog.EFT.Trainer.csproj#L17
