### ISSUE TITLE
after update, edge of the bot does not glow.

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#278]
Before the update, bot was a glow on the edge like in picture 2(example). But after the update, it doesn't glow like picture 1.

picture 1
![1](https://user-images.githubusercontent.com/85558614/211207508-75229901-39c2-4d68-944e-88437c08686c.png)

picture 2
![2](https://user-images.githubusercontent.com/85558614/211207511-33e905fe-f355-407c-a020-c34b70b6fd37.png)

settings
![3](https://user-images.githubusercontent.com/85558614/211207555-24c6c258-a148-48a1-8d35-968bdf989f12.png)

**Comment by sailro** [comment]
Did you change your `outline` file, indeed the outline width is way bigger than expected (and this parameter is not configurable).

Or perhaps are you using an extra tool?

Here is a screenshot on SPT-AKI 3.4.1 / EFT 12.12.20765

![image](https://user-images.githubusercontent.com/638167/211208632-39a043c7-77f7-48e7-b95a-ef956607459e.png)

Does it change something if you enable Xray Vision ?

**Comment by MongMikng** [comment]
oh, it works well when i enable X-ray vision. But in the past, it worked just by activating the showcharms. I don't use extra tool.
and I just checked, I think the color of the exfil text color is mismatch.
![2023-01-09 02-20 _65 0, -1 2, -35 1_0 1, 0 5, -0 1, 0 9 (0)](https://user-images.githubusercontent.com/85558614/211210287-92f9a407-11f8-4f88-93e7-89ef5d24031d.png)

**Comment by sailro** [comment]
Weird working perfectly on my side:

![image](https://user-images.githubusercontent.com/638167/211211628-5241f0d1-0e38-4b82-9cd8-ddf86e2c8f1d.png)

The only thing is you have to wait `CacheTimeInSec` seconds before seing it updated (because we keep those cached to improve performance).

**Comment by MongMikng** [comment]
It's my mistake. I removed all mods and reinstalled the SPT and checked, and everything works fine. XD
