### ISSUE TITLE
bugs & suggestions - wallhack, skills, sound issues, item/container ESP

### ISSUE THREAD

**Issue by ShadoweCZ** [sailro/EscapeFromTarkov-Trainer#280]
i can split this post if needed .. 

**1) Wallhack** 
since diferent types of wallhack (box / skeleton / charms / infos) have diffewrent impact ont the performance and visibility of the AI would it be possible to split certain setting (xray, max distance) betwen them ? 

RN Xray option only apply to Charms (bug ?) and distance applies to all at once 
also we are forced to use fill color for skeleton/box so its impossible to have ONLY charmy outlines + box visible at the same time, could box/skeleton/info be switched to use outline color instaed of the fill color ?

example how it coould look like: 
ShowBoxes
BoxDistance
BoxThicknes
BoxXray
ShowCharms
CharmsDistance
CharmsXray
etc..

**2) Skills & sounds?**
there seems to be some problems with skills 
it does NOT give mastery 3 to all weapons even after using it multiple times (screenshot)
![image](https://user-images.githubusercontent.com/30881363/211786576-49bd4f50-6b38-474b-b402-373fd1636ac9.png)
sound bug ?? when i get all the skills i become totaly silent, i think it has to do with skill CovertMovement but that one should reduce noise i make by 60% but i dont make any noise at all, i dont hear my steps at all, i dont hear movement/sprint/jumps on any surface ... is it caused by the game (the skill is bugged) or the trainer or am i supposed to be ninja ? 
could there be some additional setting for the "skill" so we can choose what skills to level and how far ? 

EDIT: found it, the  trainer maxes unlisted skills  named BotReload and BotSound,  those should be removed froom the trainer

**3) container ESP**
would it be possible to add under STASH a toggle to show other types of containers ? 
airdrops, toolboxes, jackets, weapon boxes, etc ... 
the idea here is to show all the searchable containers without having to use item tracking (cause that can be realy laggy)

also since those containers dont wanish would it be possible to change the cache for those so it cashes ALL of those at the beginning of raid and only shows it when you are within the maximum distance ? liek to remove the need to refresh cache 

basicly make it like with wallhack, only shows within max distance but thee is no need for aditional cashing (lagging)

**4) loot tracking Xray**
RN tracking loot automaticlyhas Xray on , would it be possible to make it like with wallhack so there is xray setting so we can only track items that are in line of sight ? 

basicly imagine tracking ALL items but only in line of sight (up to max distance), could that reduce the performance impact of tracking all (when i track all within 10m its still noticable 20+FPS drop no matter the cache time) 

**5)** just question in general regarding cache time ... what to set it to for gamestate and wallshot ? what do those actualy do and how often should they be refreshed ? i understand that with items/grenades etc you want to update the ESP as soon as possible but what does gamestate and wallshot caches actualy do ? wallshot especialy gets the game realy lagy so is 30s ok ? is it just to load the armor on enemies so it knows it can bypas it or do i need to refresh it more often (and have laggy experience) ?

**Comment by sailro** [comment]
2) Regarding Skills and noise, indeed it seems `BotReload` and `BotSound` are special cased and not part of displayed skills:

![image](https://user-images.githubusercontent.com/638167/213933570-95120261-c096-4f5a-8b2d-46d14b0cd54d.png)

it does NOT give mastery 3 to all weapons => I guess it's because you have pmc skills and scav skills. Perhaps using the feature on both profiles will do the trick.

**Comment by xVixere** [comment]
For now you can always just use an spt aki profile editor if you really want to change skill levels etc. 

Wallshoot is in the description on the main page 

<html>
<body>


wallshoot | Shoot through wall/helmet/vest/material with maximum penetration and minimal deviation/ricochet.
-- | --



</body>
</html>
