### ISSUE TITLE
More glanular search options for loot

### ISSUE THREAD

**Issue by OOSad** [sailro/EscapeFromTarkov-Trainer#281]
Right now it seems like the only way to track any loot around the map is by using its shortened, icon name. For instance, if you want to find Bottle of water (0.6L), you track [Water]. If you want Iskra ration packs, you track [Iskra].

There's a couple of issues with this:
- Many items can share the same shortened name. For instance, there is more than one 'BP' ammo in the game. There's also multiple 'AP' ammo types in the game. When tracking those, you'll get the whole lot at once without distinction. 
- Since the track function doesn't search for exact keywords but rather 'words containing this sequence of letters', you can get results for items unrelated to the search. For example, searching for 'AP' will also show all 'WeAPon box' and 'APple's in the map. 

In light of this, it'd be nice to have a 'trackid' function that lets you track items based on their in-game IDs. In practice, this would probably look quite hideous on a player's screen, but since every object has a unique ID that you can look up in some way or another, it would knock the two birds out with one stone as there would be no more ambiguity between tracked items and no unrelated results would appear.

**Comment by sailro** [comment]
you can use track either with the `shortname` or with the `id`

**Comment by OOSad** [comment]
I tried putting the ID in there before and it didn't work but I guess I must've messed it up somehow. It does indeed track the one specific item if you use its ID.

Thanks for the help and awesome job on the trainer. Cheers!
