### ISSUE TITLE
track, trackr, tracksr compatiblility

### ISSUE THREAD

**Issue by HanwenZheng** [sailro/EscapeFromTarkov-Trainer#282]
`track *`, `trackr *`, `tracksr *` will not work when one of them is already used.

e.g. `tracksr *` then `trackr *`

use case: when user want to track both rare and super-rare items

Probable cause: When entry is being added by `track(r|sr)`, entry with "Name: *" can only exist once 
> {
>     "Name": "*",
>     "Color": null,
>     "Rarity": "Rare"
> }

**Comment by sailro** [comment]
Fixed, I also fixed the display of `tracklist`, it was not properly displaying the rarity when a dedicated color is not set.

![image](https://user-images.githubusercontent.com/638167/213912613-154afe05-0888-42c6-aa05-d8c538eabebd.png)

**Comment by HanwenZheng** [comment]
noice
