### ISSUE TITLE
I can't see loot 

### ISSUE THREAD

**Issue by boneswift** [sailro/EscapeFromTarkov-Trainer#283]
Actually, this is my problem, tested in different languages, did not help, re-entering the game / raid did not show the results, the function in my case does not work at all

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/273

**Comment by sailro** [comment]
I think I will add a message when the tracklist is empty, for those who never read docs :)

**Comment by boneswift** [comment]
> I think I'll add a post when the tracklist is empty, for those who never read the documentation :)

Sorry, my bad, didn't notice...
