### ISSUE TITLE
trainer gui not working on SPT 3.4.1

### ISSUE THREAD

**Issue by SirBlikk** [sailro/EscapeFromTarkov-Trainer#284]
tried reinstalling multiple times and same problem occurs, trainer loads but cant use gui and can only use a few commands. please let me know what i can do to fix this. thank you for taking time to keep updating the trainer as well.

**Comment by SirBlikk** [comment]
happy to help with whatever is needed to fix the problem

**Comment by SirBlikk** [comment]
let me specify, the gui is there and shows up and is binded to RightAlt. the problem is the buttons do nothing when i click them to change anything or turn anything on

**Comment by SirBlikk** [comment]
https://user-images.githubusercontent.com/123708110/215259496-166693f6-b885-4fd7-9d5a-f5c258b8a26b.mp4

heres a short vid to help understand better

**Comment by toxicspike** [comment]
I had the same bug. Clean re-install of spt fixed that for me.

**Comment by sailro** [comment]
1- Could you share your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log` ? We'll see the exact issue.
2- Are you sure you have run the game at least once before installing the trainer as explained in the installer ?

**Comment by SirBlikk** [comment]
> I had the same bug. Clean re-install of spt fixed that for me.

@toxicspike you were having the same problem as in the video?

**Comment by toxicspike** [comment]
Yes.
Back then I tried doing another install of this trainer on top of my existing game, that didn't help. So I did a clean new install of spt, copied my profile over and installed the trainer there, that worked for me.

**Comment by SirBlikk** [comment]
@toxicspike ok thanks, trying that now. did you just delete the whole folder and make a new one?

**Comment by toxicspike** [comment]
@SirBlikk 

Yes. Before deleting the folder, copy all your mods (from user/mods and from BepInEx/plugins, whatever you installed) somewhere safe. Same for your game profile/s (user/profiles) if you don't want to start all over.
Once you've reinstalled spt, put your mods and profile/s back in place, run once to check if everything works, then install the trainer. That worked for me

**Comment by SirBlikk** [comment]
@toxicspike Okay, running SPT installer right now. Hoping this fixes the problem

**Comment by SirBlikk** [comment]
@toxicspike When you install the Trainer, do you do it manually or with the installer? and if the installer, do you have to put it in the SPT file cause thats the only way it detects SPT for me.

**Comment by SirBlikk** [comment]
![image](https://user-images.githubusercontent.com/123708110/215292600-c335cf73-b503-4497-a802-0574f61e9d44.png)
Does this look like it was installed properly?

**Comment by toxicspike** [comment]
> @toxicspike When you install the Trainer, do you do it manually or with the installer? and if the installer, do you have to put it in the SPT file cause thats the only way it detects SPT for me.

With the installer. I dont quite remember, but I think it only detected spt in the spt folder for me too. 

Regarding the installer output, idk man, sailro will have to take a look.
Sorry to hear that it didn't work.
Are you using Mods? If yes, which ones and have you tried running the game without mods to check if GUI works that way? That might be helpful to sailro figure out the problem

**Comment by SirBlikk** [comment]
> > @toxicspike When you install the Trainer, do you do it manually or with the installer? and if the installer, do you have to put it in the SPT file cause thats the only way it detects SPT for me.
> 
> With the installer. I dont quite remember, but I think it only detected spt from within the spt folder for me too.
> 
> Regarding the installer output, idk man, sailro will have to take a look. Sorry to hear that it didn't work. Are you using Mods? If yes, which ones and have you tried running the game without mods to check if GUI works that way? That might be helpful to sailro figure out the problem

Currently no mods as I was hopeing to get the trainer working before I reinstalled my mods.

**Comment by SirBlikk** [comment]
@sailro Have you found out any information that helps with the problem?

**Comment by sailro** [comment]
@SirBlikk nope unfortunately, the log is ok, I do not reproduce and this is the very first time I'm seeing this. Let me think a bit to see if we find extra infos.

**Comment by SirBlikk** [comment]
> @SirBlikk nope unfortunately, the log is ok, I do not reproduce and this is the very first time I'm seeing this. Let me think a bit to see if we find extra infos.

Thank you, let me know if you need anything or figure anything out. If I edit my config will it change or should I wait.

**Comment by SirBlikk** [comment]
@sailro Got some of the options working thru the trainer.ini but I also have a friend looking in to it for me as well.

**Comment by nekoieye** [comment]
same too. i cant see GUI

**Comment by kalasthrowaway** [comment]
+1, tried updating windows to see if that was the issue, none worked, also reinstalled, gui not showing

**Comment by nekoieye** [comment]
bump

**Comment by sailro** [comment]
I need to be able to repro, so far it is working on my side. So I need logs with errors, exact repro step, etc. Everything that could help to understand what is happening.

**Comment by sailro** [comment]
Like `BepInEx\LogOutput.log` and `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log`.

**Comment by CcRr0** [comment]
Where is trainer.ini? I can't find it

**Comment by sailro** [comment]
The trainer.ini is created when you use the `save` command in the console.

**Comment by SirBlikk** [comment]
recently upgraded my pc from an i7 7700k to a ryzen 7 5800x and it works perfectly now. not sure how we can make that problem happen again

**Comment by sailro** [comment]
Will reopen if we find something then.
