### ISSUE TITLE
Unlimited ammo

### ISSUE THREAD

**Issue by hughz001** [sailro/EscapeFromTarkov-Trainer#285]
not an issue at all but is there a way of adding unlimited ammo only thing this is missing i think also can confirm is still working on latest patch and build 3.5 and patch from today :) great work here

**Comment by hughz001** [comment]
does that mean you will try to add it ?

**Comment by RogueTech67** [comment]
@hughz001, I agree.  One of the only reasons I also use the [SERVPH's Tarky Menu] mod is for its unlimited ammo feature.

**Comment by hughz001** [comment]
yeah same here only reason i have it plus it breaks thought updates this way it will work alot more and it looks like he is trying too :)

**Comment by sailro** [comment]
Made a working prototype thanks to @solareon [here](https://github.com/sailro/EscapeFromTarkov-Trainer/pull/291). Tested with rifles, pistols and special weapons like rhino or mp18.
