### ISSUE TITLE
Suggestion: Semi unlimited health

### ISSUE THREAD

**Issue by toxicspike** [sailro/EscapeFromTarkov-Trainer#287]
Hi Sailro,

First, thanks for this great trainer.
My question:
Would it be possible to add options to health cheat, so we can choose what it applies on? Like choosing which bodyparts are always full, but everything else gets damaged normally?
Alternatively, if that doesn't work or is too much effort, could you add a copy of health that only applies to the vital areas (head and thorax) so the survival is guaranteed but everything else can get damaged/ bleeding/ blacked/ etc?

Lastly a question that you might even want to answer in the instructions: When you update this trainer here, do we just run the installer again or how should we best update? 

Thanks for your time and effort!

Cheers

**Comment by sailro** [comment]
> Lastly a question that you might even want to answer in the instructions: When you update this trainer here, do we just run the installer again or how should we best update?

You just need to re-run your downloaded installer, given it will download the latest snapshot of the trainer sources and compile against your current EFT version.
