### ISSUE TITLE
Unlimited Stamina Staying On Once Set

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#289]
With SPT-AKI 3.4.0 / 3.4.1, I noticed an issue with the [Stamina] option.  Once it's set to (Enabled) and working, setting it back to (Disabled) does NOT restore it.  The feature stays enabled.  What I noticed was the following.  I can't recall if this was happening  in 3.3.0, because I almost always turned the feature on, and always played with it.  I never really turned it off.
    This happens with 3.4.0 (Installer 2.0) no BepInEx .dll
    This happens with 3.4.0 (Installer 2.1) using BepInEx .dll
    This happens with 3.4.1 (Installer 2.1) using BepInEx .dll
Also, I've tried three versions of 3.5.0 BE, and this is happening for those versions as well.  As always, thanks for the great mod, and the support you provide.

1) Clean 3.4.1 game user profile.
2) ONLY the Trainer, NO other mods
3) ONLY all the trainer defaults, nothing initially changed/set
4) Upon spawning in Raid, run a bit.  You see the stamina bar go down, then replenish
5) Enable the Trainer Stamina feature
6) Run a bit.  It is NOT immediately enabled, keeping a full bar.
Note:  Once it then hit full, then it is working from then on
7) Disable the Trainer Stamina feature
Note:  It NEVER goes back to being off.  No matter how many times you toggle the features, once it on, it stays on.

**Comment by sailro** [comment]
Indeed, we should reset parameters to default when disabling the feature

https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Features/Stamina.cs#L57

**Comment by RogueTech67** [comment]
As always, thanks.
