### ISSUE TITLE
only some of the trainer is shown 

### ISSUE THREAD

**Issue by bananananaboooppp** [sailro/EscapeFromTarkov-Trainer#297]
only a few of the options are shown theres no aimbot and no esp customization im using spt and i used the universal installer

**Comment by bananananaboooppp** [comment]
![2023-02-12 16-18  (0)](https://user-images.githubusercontent.com/60619420/218346069-3b0cfa6d-ac25-445e-8ec2-66d4f0cb66de.png)

**Comment by sailro** [comment]
That's because you are using a super old EFT version. sptaki 2.0 rc1 so around sep 2021...

**Comment by bananananaboooppp** [comment]
how do i update it ?

**Comment by bananananaboooppp** [comment]
> how do i update it ?
i tried using the automatic and doing the manual install to update it but it didnt work i ended up haveing to unistall and reinstall tarkov compleatly
