### ISSUE TITLE
no loot at all

### ISSUE THREAD

**Issue by sayrex2009** [sailro/EscapeFromTarkov-Trainer#298]
No matter how I try to set it up. there is no loot at all. does not show containers and what is in them. Doesn't show anything at all.

**Comment by nekoieye** [comment]
aki 3.4.1 is LAST.

**Comment by hughz001** [comment]
not true im on the newest one 3.5 and its all working you must be doing something wrong. all working on latest build

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/273
