### ISSUE TITLE
Wallhack request

### ISSUE THREAD

**Issue by Grafias8** [sailro/EscapeFromTarkov-Trainer#299]
Hi,

1. Could you separate the wallhack infos from the body color? When I change the opacity for the color, it also changes the infos. Example:
![image](https://user-images.githubusercontent.com/125357026/219382731-a06959d6-5fa0-47b7-8cc0-b3957827fce3.png)

2. Could you make an option to disable the body color so only the border color shows? Example:
![image (1)](https://user-images.githubusercontent.com/125357026/219382877-8f2207e1-eca5-4440-8e2b-4653d551df30.png)

3. Could you add an option to when an enemy is shootable, the border, body, box and skeleton color changes to an another with option to choose that color. Example: 
Red body - not shootable
Blue box - not shootable
Green body - shootable
Red box -shootable
![image (2)](https://user-images.githubusercontent.com/125357026/219382953-25436bd5-6eee-4ada-9f2b-07ca9b5340b6.png)

4. When zooming in with the weapons, the wallhack boxes and the skeletons behave weirdly. The charms work well with zoom, but the boxes and the skeletons remain the same when zoomed in. Example: The charm shows where the bot standing.
![image (3)](https://user-images.githubusercontent.com/125357026/219383139-c9af83ad-657b-4397-bdef-017f95024755.png)

Thanks for your work! This trainer is very useful!

**Comment by sailro** [comment]
@solareon for the zoom we can do:

```csharp
			var weaponAnimation = player.ProceduralWeaponAnimation;
			if (weaponAnimation == null)
				return;

			var aimingMod = weaponAnimation.CurrentAimingMod;
			if (aimingMod == null)
				return;

			var zoom = aimingMod.GetCurrentOpticZoom();
```

For the aiming test:

```csharp
			var handsController = player.HandsController;
			if (handsController == null)
				return;

			var isAiming = handsController.IsAiming
```

**Comment by toxicspike** [comment]
> I can add a ShowNotShootable toggle that will flip the colors between the not shootable and original color.

That would be awesome, thank you!
