### ISSUE TITLE
Clearer Instructions?

### ISSUE THREAD

**Issue by FrameKixrr** [sailro/EscapeFromTarkov-Trainer#30]
I am using the right version, latest download have put all the files in the places they should be via the readme and nothing happens when I execute a command.

**Comment by sailro** [comment]
- Could you give your exact EFT/sptarkov versions ?
- Could you summarize what you copied exactly and where ?
- Do you see any error in `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt` ?

**Comment by FrameKixrr** [comment]
I sorted it, seems to be a problem with the spt tarkov nlog file you provide and tell to replace. I just copy pasted the code into the nlog file spt aki gives you and it worked fine!

**Comment by sailro** [comment]
Perfect!
