### ISSUE TITLE
im bad at pc stuff please help

### ISSUE THREAD

**Issue by drachedachte1** [sailro/EscapeFromTarkov-Trainer#301]
![image](https://user-images.githubusercontent.com/65346683/219991152-579aa8c3-0ec5-4369-9537-c5def01707d4.png)

**Comment by nekoieye** [comment]
live server : BAN.

**Comment by sailro** [comment]
Yes this is expected, given you are trying to compile against a 'live'/unpatched version.

Please use this trainer with a spt-aki compatible installation. Going forward it will be the only supported scenario.
Thanks

**Comment by dragonGRaf1312** [comment]
> Yes this is expected, given you are trying to compile against a 'live'/unpatched version.
> 
> Please use this trainer with a spt-aki compatible installation. Going forward it will be the only supported scenario. Thanks

hmm and how do i do that

**Comment by sailro** [comment]
https://dev.sp-tarkov.com/SPT-AKI/Stable-releases/releases
