### ISSUE TITLE
loot tracking  bugged! and question about aimbot

### ISSUE THREAD

**Issue by ItsYaBoyRandy** [sailro/EscapeFromTarkov-Trainer#305]
Loot Track seems to be bugged for me i can't use /trackr * and /tracksr * , at the same time or add any item to the /track while i have one of the /trackr or /tracksr on.
So what happends is legit nothing when 1 of the mentioned commands is active, when i try to use them both or try to add an item nothing shows up noting new even tho the item is right in front of me.
I've tried reinstalling the trainer but that doesnt seem to do anything, is anyone able to help me with this.

About the aimbot im kinda confuised on how it works maybe thats also bugged for me because that also seems to do nothing for me. I bind it and then use the configured them for my liking but it does neither lock or smootly goes towads it. so idk what do to do :D

**Comment by xVixere** [comment]
Configure aim time and distance and hold the key and it will lock onto nearby targets 
I put mine as middle mouse button

**Comment by ItsYaBoyRandy** [comment]
> Configure aim time and distance and hold the key and it will lock onto nearby targets. It doesn't work for certain keys due to some interactions.
> 
> I put mine as middle mouse button
> 
> Try it out Config:
> 
> ```
> Mouse 2
> 500
> 1
> 400
> 1
> 0
> 10
> ```

ty alot man this actually works :D

**Comment by Fox7535** [comment]
> 

where do i put this?

(Im really new to this)

**Comment by ItsYaBoyRandy** [comment]
> > 
> 
> where do i put this?
> 
> (Im really new to this)

open the trainer with right alt or the button that u binded 

go to the aimbot section

mouse 2 = the bind instead of slash or bind it to your liking 

500 = distance 

1 = smoothness

400  = fov 

turn on silent aim if u want it to to shoor for u when u hold your button

settings for the silent aim.

0 = bullet time 

10 = (can't remember whats this is called)

**Comment by Fox7535** [comment]
another question.
Why does it only work on st tarkov what would I have to change to make it work on tarkov or is it that I need to find a battleye bypass because I would get insta banned?
