### ISSUE TITLE
PlayerPing feature

### ISSUE THREAD

**Issue by duyphamvu47** [sailro/EscapeFromTarkov-Trainer#306]
Hi, I appreciate your work here. 
I've read the trainer.ini and noted that there was a feature called "EFT.Trainer.Features.PlayerPing". I've tried to enable it (F5 by default) but it didn't seem to work. Can you explain or give some detail about this feature ?

Thanks

P/s: I like this trainer a lot but I don't want it to show the specific position of the enemy cause it's gonna ruin all the fun. I just want the trainer to show me their direction not where they're standing xD. Is there any way to do this ?

**Comment by xVixere** [comment]
At the moment, the features listed is what you get 
You're using a full fledged cheat for an offline version of the game. 
And you're worried about ruining the fun of the game ?

Don't use the trainer and play vanilla instead 

If you want to get a radar hack with general directions get a 2D radar and a DMA card

**Comment by duyphamvu47** [comment]
> 

Nice suggestion, thanks

**Comment by sailro** [comment]
Sorry but there is no `PlayerPing` in the trainer.ini. Could you share this file ? Perhaps a fork of the repo ?

**Comment by duyphamvu47** [comment]
I've just checked again. It was an mistake from my side. Sorry about this
