### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Toshkento** [sailro/EscapeFromTarkov-Trainer#308]
can you elaborate? which .dll file to copy to BepInEx\plugins. SPT-AKI version 3.5.0, I'm having trouble translating ,

**Comment by sailro** [comment]
You have nothing to copy. Everything is handled by  the installer. BepInEx is a dependency installed by spt-aki, so if you don't run the installer against a compatible installation: EFT+spt-aki, this will not work.

**Comment by Toshkento** [comment]
can be more detailed? Instructions ?

**Comment by sailro** [comment]
Everything is already documented, you just need to read:
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-2.1
