### ISSUE TITLE
No Such Command

### ISSUE THREAD

**Issue by daaaaanisssssh** [sailro/EscapeFromTarkov-Trainer#31]
HELP. 
Versions for this trial:
SPTarkov: 1.4.4
EFT: 12.10.12646

I followed the steps in the readme;

1. Copy all files in your EFT directory like C:\Battlestate Games\EFT:
EscapeFromTarkov_Data\Managed\NLog.EFT.Trainer.dll (this is the compiled code for the trainer)
EscapeFromTarkov_Data\outline (this is the dedicated shader we use to outline players [wallhack])

Copied, both into respective folderes. How about other files and folders i.e. EFTTarget.cs etc etc? As of now, I copied them into main game folder (EFT-live equivalent)

2. Edited the NLog as below:

```
<xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<targets>
        <target name="EFTTarget" xsi:type="EFTTarget" />
        <target name="Aki.Loader" xsi:type="Aki.Loader" />
<targets>
</nlog>
```

Game launched perfectly however commands are not working. Help :(

**Comment by sailro** [comment]
If you use a release, you don't need the source code (cs files).  So do not worry about 'other files and folders'

Given you are using `sptarkov`, your `NLog.dll.nlog` should be like that:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<targets>
		<target name="Aki.Loader" xsi:type="Aki.Loader" />
		<target name="EFTTarget" xsi:type="EFTTarget" />
	</targets>
</nlog>
```

**Comment by daaaaanisssssh** [comment]
My bad, point 2 was supposed to show my edited lines in Nlog.dll.nlog. The outcome was still the same; "No Such Command"

**Comment by daaaaanisssssh** [comment]
I have made 2 fresh installs, however the trainer fail to load via console. Let me just update you with the files:

1. NLog.dll.nlog location:

![Nlog](https://user-images.githubusercontent.com/85711945/121823000-fb871880-ccd4-11eb-89fa-a3c4c45d015b.png)

2. NLog.dll.nlog
![image](https://user-images.githubusercontent.com/85711945/121823011-15286000-ccd5-11eb-806d-331411dcdfae.png)
or
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<targets>
		<target name="Aki.Loader" xsi:type="Aki.Loader" />
		<target name="EFTTarget" xsi:type="EFTTarget" />
	</targets>
</nlog>

3. trainer.ini folder location:
![image](https://user-images.githubusercontent.com/85711945/121823081-7e0fd800-ccd5-11eb-8d11-d0019a33a457.png)

Is there any step missing? I believe I have followed your readme steps as it is. :(

**Comment by sailro** [comment]
1- There is no need to create `trainer.ini` yourself.

2- In your screenshot I cannot see the bits of the trainer in `EscapeFromTarkov_Data\Managed`:

![image](https://user-images.githubusercontent.com/638167/121825411-1753d580-cc67-11eb-9586-68a58c1a4149.png)

And you need the `outline` file in `EscapeFromTarkov_Data`

![image](https://user-images.githubusercontent.com/638167/121825444-3c484880-cc67-11eb-8da6-9d9246f910e1.png)

All of this is clearly indicated in the docs, why is it so hard to read :)

**Comment by daaaaanisssssh** [comment]
Ah found it. I overlooked the NLog.EFT.Trainer.dll, all i see is the .csproj. Sorry my bad. :(

**Comment by daaaaanisssssh** [comment]
Hi Sebastien, it is unfortunate that with all the steps above, I still cant use the commands. I have followed similarly as per your screenshots above, made 2 fresh installs as well.

**Comment by sailro** [comment]
Hey @daaaaanisssssh, I've just published an Installer:
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-1.0

Could you try with this one?

**Comment by sailro** [comment]
Important: if you are using SPT-AKI, please make sure you have run the game at least once before installing the trainer. SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries. If you install this trainer on stock binaries, the game will freeze at the startup screen.

**Comment by daaaaanisssssh** [comment]
Hi Sebastien! Made another fresh install and the installer works just fine! Thank you very much!

![image](https://user-images.githubusercontent.com/85711945/122052682-86bcf700-ce18-11eb-85a4-c3f3b2689e7c.png)

**Comment by sailro** [comment]
Perfect !
