### ISSUE TITLE
Silent Aim issues/improvement idea

### ISSUE THREAD

**Issue by JustinShoaf** [sailro/EscapeFromTarkov-Trainer#310]
Idk what is directly causing it, but silent aim either rarely works, or it auto-fires.
Should have options of whether you want it to fire automatically or not.
One option for Silent Aim, another to tick w/ auto fire
Silent aim should work just by spraying and it hitting whatever is in the FOV (it does not do it currently, unless I am missing an option).

The biggest bug is that I get hit with my own bullets when using Silent Aim. I don't know if it's caused by a ricochet, or what; but my wallshoot is turned off so ricochet should be off.

**Comment by sailro** [comment]
It works fine on my side. We often saw users reporting "I get hit with my own bullets" using extra mods doing incompatible stuff. Is it the case on your configuration ?

**Comment by xVixere** [comment]
> We often saw users reporting "I get hit with my own bullets" using extra mods doing incompatible stuff. Is it the case on your configuration ?

I"ve had that issue whilst turning out the FOV for aimbot to an absurdly high number

**Comment by sailro** [comment]
> I"ve had that issue whilst turning out the FOV for aimbot to an absurdly high number

ah interesting

**Comment by sailro** [comment]
Just thought of that, but you just need to tweak `SilentAimNextShotDelay`, the lower it is the faster the aimboit will re-shoot.
