### ISSUE TITLE
crashing while deploying

### ISSUE THREAD

**Issue by Velikan-17** [sailro/EscapeFromTarkov-Trainer#317]
SPT-AKI 3.5.0
Tarkov version: 0.13.0.21734
Very simple.. when the timer before deploy starts the game crashes without any sort of exit code or error message, inside the game I can only play factory, thats the only map where the game wont flinch.

**Comment by Velikan-17** [comment]
sure!
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/10884499/Player.log)

**Comment by sailro** [comment]
So in the log we can spot a hard mono crash (which is the script engine used by Unity).

Inspecting the callstack it seems related to your NVidia drivers (you have a RTX 2070). I don't think it is related to this trainer tough. That's weird. 

```
========== OUTPUTTING STACK TRACE ==================

0x00007FFBCCB654D3 (nvwgf2umx) NVDEV_Thunk
0x00007FFBCCC758F5 (nvwgf2umx) NVDEV_Thunk
0x00007FFBCCA361A9 (nvwgf2umx) NVENCODEAPI_Thunk
0x00007FFBCCA08549 (nvwgf2umx) NVENCODEAPI_Thunk
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentativo di accedere ad un indirizzo non valido.' (Address: 00007FFBCC89C62A)
0x00007FFBCC89C62A (nvwgf2umx) (function-name not available)
0x00007FFBCCC308E5 (nvwgf2umx) NVDEV_Thunk
0x00007FFBCCC30698 (nvwgf2umx) NVDEV_Thunk
0x00007FFBCCD4F87C (nvwgf2umx) NVDEV_Thunk
0x00007FFBCDAC8D58 (nvwgf2umx) OpenAdapter12
0x00007FFC46DE7614 (KERNEL32) BaseThreadInitThunk
0x00007FFC474826A1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========
```

Perhaps you should:
- update your drivers (are you using a VM or something?)
- do not use any OC tool 

You can try to search `nvwgf2umx crash` on google.

**Comment by Velikan-17** [comment]
I'll try to update my drivers,  thank you for the immediate response, I'll let you know as soon as possible

**Comment by Velikan-17** [comment]
I've reinstalled the drivers, that was the problem, thank you so much! Now everything works as intended (just with some spike lags)
