### ISSUE TITLE
Unable to Locate SPT Install

### ISSUE THREAD

**Issue by sean0705** [sailro/EscapeFromTarkov-Trainer#322]
Running the Installer.exe, it can't seem to locate my SPT-AKI install, it just locates the normal EFT install.
I have ran SPT, and am running the Installer as Admin.
Further, as detailed in point 1 of the Universal Installer's page, i can't seem to enter any commands in this CMD window to specify a custom installation path.
![image](https://user-images.githubusercontent.com/50700406/224073729-7375a6e8-14a7-431f-a1a3-2422116a3dea.png)

**Comment by sailro** [comment]
Try to copy the installer.exe in your SPT-AKI install, then run it.

**Comment by sean0705** [comment]
> Try to copy the installer.exe in your SPT-AKI install, then run it.

Ok I am quite possibly the biggest of idiots, sorry to waste your time, honestly not sure why I hadn't tried that! :]
