### ISSUE TITLE
Radar -> ShowMap Not Scaling With RadarPercentage - v2.1 - SPT-AKI 3.5.2

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#323]
With the RadarPercentage at the default value of 10, selecting the ShowMap option displays the map perfectly.  However, when you change the RadarPercentage say to 50, the map display stays the same and does scale up.  If this is by design, then fine.  I tried looking through the ISSUES before posting this.  Thanks
![2023-03-09 11-45 _346 0, 1 4, -130 1_0 1, -0 6, 0 0, 0 8_12 05 (0)](https://user-images.githubusercontent.com/100148335/224095815-f1e1da5e-41a1-4353-8997-8079f534c1b7.png)

**Comment by sailro** [comment]
Indeed I see why. We have a refactoring in progress. Will fix that after we finish.

As a workaround, disable `Showmap`, then re-enable it. This should do the trick.

**Comment by sailro** [comment]
Fixed here: https://github.com/sailro/EscapeFromTarkov-Trainer/pull/320/commits/9db5297b38b7db420ae6a99bfa3c6ca468d8f62d
