### ISSUE TITLE
Loot tracking issue also wall esp issue

### ISSUE THREAD

**Issue by psycojoe1986** [sailro/EscapeFromTarkov-Trainer#324]
I have loot on, I have gone into console and user either tracksr * or trackr *.  Nothing ever shows in game except some of the options under the loot tab (corpses etc.)  I have tried to reinstall I have also tried to create a track save file and load that still same outcome.

wall esp for enemies seems to completely disappear when using certain weapons.

**Comment by sailro** [comment]
which map?

**Comment by psycojoe1986** [comment]
I was having issues on factory and customs as those were the only maps I was playing on this morning

**Comment by sailro** [comment]
Could you share your %LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log

**Comment by psycojoe1986** [comment]
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/10935169/Player.log)

**Comment by sailro** [comment]
Wall ESP should be fixed, could you use the `save` command after your tracklist is set, and share your `Documents\Escape from Tarkov\trainer.ini`

**Comment by psycojoe1986** [comment]
wouldn't let me paste as a .ini so I copied the contents to .txt

**Comment by NanoNM** [comment]
> 

It works for me

**Comment by psycojoe1986** [comment]
works now.  Thank you

**Comment by sailro** [comment]
I'm going to check if something regressed regarding this. If we save full transparent colors it's weird.
