### ISSUE TITLE
Multiple issues under weird criteria 

### ISSUE THREAD

**Issue by Razatop** [sailro/EscapeFromTarkov-Trainer#326]
ESP is turning off visually when I swap to a grenade, any drinking/eating/healing or any other animations, and when using a new weapon that I picked up in raid, but it seems weapons I go into raid with it works.

Will post any information you need from me, love this lil project :D

Everything else is working perfect withno issues it seems.

**Comment by Razatop** [comment]
Update: Nevermind ESP is just not working with certain weapons? Doesn't seem like there is a theme but I will keep this updated with what I find.

**Comment by kafuuchino-desu** [comment]
+1 wallhack is working with a m700, but not with a shotgun or my melee weapon

**Comment by kafuuchino-desu** [comment]
i guess the cause of this problem is here: https://github.com/sailro/EscapeFromTarkov-Trainer/blob/8ca024e08ec5c6c59d323de0e6a4676b0d7027d1/Features/Players.cs#L152

**Comment by kafuuchino-desu** [comment]
and also the colors are broken too, all npcs are labeled with the same color

**Comment by kafuuchino-desu** [comment]
> Let me take a look at how we can better check if the weapon has an optic and skip if needed.

maybe I'm reading the code wrong, but will esp work if you have a healing item out?
