### ISSUE TITLE
Possible to blacklist container names from showing

### ISSUE THREAD

**Issue by TestyTest-oss** [sailro/EscapeFromTarkov-Trainer#33]
Would be nice to blacklist some container names from showing up but still allowing items inside to be tracked.

For example trying to track "t" ammo will show all containers with the letter t in them and they won't disappear when looted, jacket toolbox etc.

Another example would be the duffle bag you can wear and the duffle bag you can loot both are treated the same by tracking

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/124#issuecomment-1031937651

For more control over tracked items, you can now use `ID`
