### ISSUE TITLE
No xray features without an optic

### ISSUE THREAD

**Issue by xRage420** [sailro/EscapeFromTarkov-Trainer#338]
Having an issue where AI Boxes, charms or skeletons will NOT*** show when you have a gun with no optic on it or if you are healing, surgery, eating etc. Have messed with a bunch of settings with no change. When using gun with optic all features work as intended.

**Comment by sailro** [comment]
I believe we fixed that quite recently:
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/327

Could you try to update the trainer ?
