### ISSUE TITLE
how do i fix clear tracking on the dll 

### ISSUE THREAD

**Issue by DragonBreath1104** [sailro/EscapeFromTarkov-Trainer#341]
im using the newest version of spt so i have to use the dll version of this trainer and all the fixes i see i cannot figure out for the dll version of the trainer. the only things i can track through walls is gphones using the loot tab with R.Alt so i have tried and looked but i cant seem to fix the clear tracking issue that everyone else seems to have on the nlog version

**Comment by sailro** [comment]
The fix was merged yesterday : https://github.com/sailro/EscapeFromTarkov-Trainer/pull/335

So make sure you re-run the installer to compile the latest sources.

bepinex/nlog loader is just a detail for loading, it is the exact same trainer code.
