### ISSUE TITLE
Suggestion/Question, Noclip/Flying possible?

### ISSUE THREAD

**Issue by ajdrigs** [sailro/EscapeFromTarkov-Trainer#342]
So, I was using the speed hack and fell through the world cause I ran through a rock, Would it be possible to add noclip? Cause I was just stuck at the underworld and lost all my progress, Cause I had to ALT+F4.

**Comment by sailro** [comment]
That's the danger of the speed hacking :). When falling you can toggle the `FreeCamera` feature, and teleport.

With practice, it is usually enough to aim at the sky and use the speedhack to return to a safe position.

**Comment by ajdrigs** [comment]
> That's the danger of the speed hacking :). When falling you can toggle the `FreeCamera` feature, and teleport.
> 
> With practice, it is usually enough to aim at the sky and use the speedhack to return to a safe position.

Oh my god, I completely forgot about free cam, DAMN IT. lmfao
