### ISSUE TITLE
Installer 2.1 for SPT-AKI 3.4.1 No Longer Finds/Uses BepInEx and aki-efttrainer.dll ?

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#344]
@Sailro.  Hello.  I went to redownload / compile the trainer 2.1 against a clean 0.12.12.32.20765 (04 Dec 2022) *** add SPT-AKI 3.4.1.  It is now showing "Compilation failed for the master branch.".  It is ONLY creating the [NLog.EFT.Trainer.dll] and [NLog.dll.nlog] files for use. On 01/29/2023 is compiled against the master branch and succeeded in finding BepInEx and created the "newer"  aki-efttrainer.dll file.  Is the Trainer installer simply no longer supporting BepInEx and (aki-efttrainer.dll) for older SPT-AKI versions as it did a month ago?  Thanks in advance.

![EFT-Trainer-341](https://user-images.githubusercontent.com/100148335/225133834-4f8abaff-19cd-40b0-b293-499969b3b597.jpg)

**Comment by sailro** [comment]
We added `BepInEx` support quite recently, so when using the `dev-0.12.12.32.20765`  branch, it is not yet included.
It will be available with all version >= 0.13.0.21531, which should not be an issue given the ` NLog`  loading trick is still working with those.
