### ISSUE TITLE
Suggestion/Question about some function

### ISSUE THREAD

**Issue by struemuhu** [sailro/EscapeFromTarkov-Trainer#345]
hello,I'm not a English speaker but here to say thank you for your project!
I'm wondering is it possible to show those power button for exit on screen? that will be a great help for a rookie like me.
Another one is , can the airdrop case be sort into stash console because I can set the stash to max distance and still easy to find because they are scatter, but loot can't, will blow my computer ;)
All the best,Love from China!

**Comment by sailro** [comment]
AirDrops are now visible from the `stash` command.
