### ISSUE TITLE
Spt 3.5.3 wont recognize the dll 

### ISSUE THREAD

**Issue by DragonBreath1104** [sailro/EscapeFromTarkov-Trainer#347]
i have the trainer installed and i used the universal installer for it but for some reason my spt doesn't see it and wont run it i press right alt which is my mapped key for the popup menu and nothing happened i checked in the trainer.ini file and right alt is the mapped key, however it worked just fine on 3.5.2 but i cant figure out how to roll back to that version

**Comment by sailro** [comment]
It is working fine on my side:

![image](https://user-images.githubusercontent.com/638167/225283834-5cb3815f-aee5-4956-bbf0-1a144acc9c92.png)

And everything is working as expected in-game.

if you updated your spt-aki installation from 3.5.2 to 3.5.3, you need:
- to remove the trainer (installer uninstall)
- to run the game once with 3.5.3
- to re-install the trainer
