### ISSUE TITLE
The Loot ESP is not working

### ISSUE THREAD

**Issue by Starbok1994** [sailro/EscapeFromTarkov-Trainer#354]
I don't know if i did something wrong, everything works, except ESP Loot, the options is turn on, I put range at 300 all the options are on and nothing... is it bugged right now?

**Comment by sailro** [comment]
What is your `trackist` ? Did you use `track` at least to track something?

**Comment by solareon** [comment]
There are multiple ways to add loot to the tracker. The easiest option is to enable the TrackWishlist feature under the loot option and then add items to track with the games built in wishlist by right clicking items and then clicking on 'Add to W-List'

The other options are to open the console and type 'track *' or 'trackr *' or 'tracksr *'. This will cause all of the items in the raid to be shown depending on rarity. You can also issue 'track <partial short name>' to track items as well.

**Comment by Starbok1994** [comment]
OMG Thank you mates, I'm an idiot, I should have led with that :D!
