### ISSUE TITLE
Installer doesn't create aki-efttrainer.dll in SP-Tarkov 3.5.4

### ISSUE THREAD

**Issue by SereneVirus** [sailro/EscapeFromTarkov-Trainer#358]
Have you run the game after installing SPTarkov? - Yes
I get the following message when I target the SPTarkov folder:

```
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.0.22173) in D:\Games\BSG Offline\EFT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Compilation failed for dev-0.13.0.22173 branch.
Trying to disable faulting feature(s): Hits, Quests, Health, Ammunition.
>> Try #2 Compilation succeed for master branch.
We found a fallback! But please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues
Created NLog.EFT.Trainer.dll in D:\Games\BSG Offline\EFT\EscapeFromTarkov_Data\Managed.
Created outline in D:\Games\BSG Offline\EFT\EscapeFromTarkov_Data.
Warning: EscapeFromTarkov 0.13.0.21531 or later prevent this trainer to be loaded using NLog configuration.
It is now mandatory to use SPT-AKI/BepInEx, or to find your own way to load the trainer. As is, it will not work.
Already patched NLog.dll.nlog in D:\Games\BSG Offline\EFT\EscapeFromTarkov_Data\Managed.

Press a key to exit...
```

**Comment by solareon** [comment]
Did you run SPT-AKI one time before? If it doesn't patch the binaries and deobfuscate some of the assemblies we can't create the trainer against them

**Comment by SereneVirus** [comment]
Yup, I stated that at the top of the issue message =)

**Comment by solareon** [comment]
Okay my apologies I didn't see that bit on the phone build. Let me try on a clean spt 3.5.4 install

**Comment by sailro** [comment]
Either sptaki is not installed in this case (are you sure you don't have several instances? + we do not see the `[SPT-AKI] detected.`) or the installer was not able to detect it (but still we should be able to compile).

Those errors are common if you use the installer on a vanilla installation.

**Comment by SereneVirus** [comment]
You are right, completely my bad. I mixed up the native EFT and the SPTarkov installation folder order! Working like a charm now. Thanks a lot for this masterpiece!
