### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by Virt-env** [sailro/EscapeFromTarkov-Trainer#36]
I'm getting 57+ errors trying to compile
I would try fixing them myself but i know 0 c#
if you get a moment, could you please upload a precompiled version somewhere
Im on the latest build using SPTarkov

**Comment by sailro** [comment]
Latest EFT is `0.12.10.2.12646`, and we already have a release for that:
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/0.12.10.12646

**Comment by Virt-env** [comment]
god im sorry i was being so dumb, thank you it all works perfectly

**Comment by sailro** [comment]
No worries!
