### ISSUE TITLE
SilentAim glitch

### ISSUE THREAD

**Issue by java-redeemer** [sailro/EscapeFromTarkov-Trainer#360]
**Pre-condition:**
SPT-AKI 3.5.3 (patch 22173).
Used installer.
Default trainer configurations.

**STR:**
1. Die in session
2. Start another session

**AR:** SilentAim kills actor when shoot in any enemy (scav/pmc/boss)

At first I thought that the problem was in the ammo/weapon "Found in raid" - but after reinstalling spt-aki and trainer SilentAim works good with "Found in raid" ammo/weapon and it does not kill the actor. Turning off/on SilentAim does not help. Changing default values in aimbot config or re-loading configuration does not help too. Issue reproduces on all maps, all ammo/weapons, any kind of actor (scav/pmc). [Same issue in #249](https://github.com/sailro/EscapeFromTarkov-Trainer/issues/249)

**Comment by java-redeemer** [comment]
I will further investigate the possible causes of the errorю I'll let you know if find more accurate steps to reproduce.

**Comment by sailro** [comment]
ah interesting

**Comment by OrionAF** [comment]
Do you have the FOV circle radius enabled?  I only got killed when I had it enabled, and after disabling the FOV circle radius it didn't happen to me again

**Comment by java-redeemer** [comment]
> Do you have the FOV circle radius enabled? I only got killed when I had it enabled, and after disabling the FOV circle radius it didn't happen to me again

I use default settings. FovRadius is 0, ShowFovCircle is disabled.

**Comment by Darkelf2k3** [comment]
Hello, I would like to add to this discussion, I am using the latest version of Tarkov and SPT version 3.5.7, I manage to recreate the bug using an m9 pistol with pst ammo also the Mosin with LPS ammo. I have the video for the m9 pistol here https://youtu.be/p6ZsqprKJmg , also there is a bug when the FOV is above 20 my weapon keeps shooting wildly without hitting anything after toning it down as can you see in this other video it behaves normally https://www.youtube.com/watch?v=ZUU478cFC9s

**Comment by Kogzu** [comment]
a few notes from me:
sometimes when shooting manually with silent aim enabled bullets dont go where your aiming and hit ground or wall behind you when you turn off silent aim it shoots fine, im pretty sure this affecting bots because somtimes bots shots at me from 1 meter and cant hit me, about "shooting myself" bug all bolt action rifles working fine for me most often it happens with 545x39 guns and im pretty sure this bug affects bots to because i often see bot shoting at target and drop dead

**Comment by S2cottish** [comment]
i also have an issue where silent aim somehow steals my kills and i really wish it would shoot through fences its super inconvenient that i cant shoot thru fences in reserve.

**Comment by sailro** [comment]
I believe this can be linked to the previous implementation of `wallshoot`. 

https://github.com/sailro/EscapeFromTarkov-Trainer/pull/459

Could you try with the latest version to see if you can repro ?

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/468
