### ISSUE TITLE
Compilation Failed For Master Branch - Branch dev-0-13-0-22617 Not Found

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#361]
Tried running the latest 2.1 Installer against the new Apr 9, 2023 SPT-AKI 3.5.5 and Tarkov (0.13.0.22617).  It said to file an issue, so I did.  Thanks.

-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.13.0.22617) in C:\NoScan\Games\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.13.0.22617) in C:\NoScan\Games\EFT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.0.22617 not found.
Trying to disable faulting feature(s): Ammunition.
>> Try #2 Compilation succeed for master branch.
We found a fallback! But please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues
[SPT-AKI] detected. Please make sure you have run the game at least once before installing the trainer.
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries.
If you install this trainer on stock binaries, the game will freeze at the startup screen.
Continue installation (yes I have run the game at least once) ? [y/n] (y):

**Comment by sailro** [comment]
Fixed. They changed a bit the call signature to add bullets (for infinite ammo)

**Comment by RogueTech67** [comment]
@Sailro, just retried it, works without an error, and ammo is working now.  Thanks again.
