### ISSUE TITLE
Radar and Map not working in SPT-AKI 3.5.5

### ISSUE THREAD

**Issue by paulsnoops** [sailro/EscapeFromTarkov-Trainer#362]
Radar and map no longer working for me. See screenshots below. I have upgraded (fresh install) from SPT 3.5.0 to 3.5.5 and fresh Trainer today. Running no mods.

Radar:
![EscapeFromTarkov_DLqfRhq9ZW](https://user-images.githubusercontent.com/18243520/231164273-3e378d0b-18c1-4ccd-8142-495e4748ae84.png)

Map:
![EscapeFromTarkov_90cindJ86m](https://user-images.githubusercontent.com/18243520/231164327-33cc63ba-7fe4-4d21-8b1f-4dc56fa37463.jpg)

**Comment by sailro** [comment]
I repro. We cannot see the real map as background (ShowMap option for Radar feature). Enemy position / markers are still working though.

**Comment by sailro** [comment]
I think I found the culprit:

https://github.com/sailro/EscapeFromTarkov-Trainer/commit/45fcd4652860139bd117f001244b844ed178ab90

It is working properly now on my side.
