### ISSUE TITLE
Quickthrow sometimes throws 2 grenades

### ISSUE THREAD

**Issue by OrionAF** [sailro/EscapeFromTarkov-Trainer#364]
As the title says.  If I have multiple grenades in my inventory, it will sometimes throw two.  90% of the time, after you throw the first two, it stays normal, but once in a while, it starts throwing 2 grenades again.

**Comment by sailro** [comment]
Are you sure you are not using the same key binding "twice" like `G`:
- in the trainer for the quickthrow ?
- in the game for launching a grenade ?
