### ISSUE TITLE
Some bots not getting charm effect

### ISSUE THREAD

**Issue by Tkdmaster** [sailro/EscapeFromTarkov-Trainer#367]
I've noticed some bots do not get the charm effect for some reason. In the picture, I was on reserve in the bunker. After turning on the power, a wave of Raiders spawned and got the charm effect, but, another group spawned in as well and did not, you can see them all dea don the ground, half have charms, half do not. This is very reproducible for me, as this seems to happen jsut about every time I go to the reserve bunker.

![EscapeFromTarkov_eJdRbv2nBM](https://user-images.githubusercontent.com/8647574/235389388-1c6e0238-7dc6-4169-9389-43b6ddccecdf.png)

**Comment by solareon** [comment]
This looks like it might be the bots being identified as a different type than what we have accounted for. Do you have any errors on the console when it occurs?

https://github.com/sailro/EscapeFromTarkov-Trainer/blob/ed8babfc2a27a6d0f0086aeed3cc9f8b2f9547ce/Features/Players.cs#L312-L340

**Comment by Tkdmaster** [comment]
As far as I can tell, no, I'm not seeing anything at all in logs when this happens. Just had it happen right as I spawned in on customs, but no errors in any log files.

**Comment by sailro** [comment]
I just fixed the issue with flickering/disappearing chams
