### ISSUE TITLE
game lags every 5 seconds.

### ISSUE THREAD

**Issue by Trakovmani** [sailro/EscapeFromTarkov-Trainer#368]
Hello, sailro!
After installing the trainer, it seems to be lagging.
Remove the trainer and its be fine. 

can u help me?

**Comment by Trakovmani** [comment]
Found the reason why the game is lagging

It's because of the quest trainer. If you turn it off, there is no lag.

**Comment by EdiLung** [comment]
Stuttering issue specially in a big map like Street of Tarkov, Costums etc.

**Comment by RomulusHeidi** [comment]
[Exception] : NullReferenceException
UnityEngine.Renderer.get_material () (at <85d1d3e7744a4a47b5f51883bf40bba2>:0)
EFT.Trainer.Features.Players.ResetShaders (System.Collections.Generic.Dictionary`2[TKey,TValue] cache) (at <8e92675741524e7d82a4f525fe26ae7f>:0)
EFT.Trainer.Features.Players.OnGUI () (at <8e92675741524e7d82a4f525fe26ae7f>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class312:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

![error spam](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/48508664/4d04859b-79a8-4afd-8187-1eec9a60e7cb)


error spams at least 5 times per second
