### ISSUE TITLE
"Gingy keychain" not appearing as loot in raids when wishlisted

### ISSUE THREAD

**Issue by goestohollywood** [sailro/EscapeFromTarkov-Trainer#371]
Using SPT-AKI 3.5.2 and the latest version of this trainer. Everything shows up when wishlisted in raids except the Gingy keychain. I've compelted over 100 raids and haven't come across it once.

Thanks for your help.

**Comment by solareon** [comment]
I just made a fresh profile and installed to test. The item shows in the tracklist in the console. Unfortunately I don't have a mod to allow me to drop a key chain in raid to see if it shows. If you issue a `tracklist` in the console do you see something similar to this?

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/769465/e0f4a8aa-7c1a-4433-9dc5-5ea32be736ed)

**Comment by solareon** [comment]
Edit: I forgot the the SVM mod can disable that. I just tested and it tracks just as expected. Perhaps its just extremely bad luck =/

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/769465/9fe9475f-7e2a-4910-863b-44aff9fc0da8)

**Comment by sailro** [comment]
Technically this item is a container, so make sure you enabled the `SearchInsideContainers` option in the loot section. Else we'll just skip it.

**Comment by goestohollywood** [comment]
I have `SearchInsideContainers` enabled and still haven't seen it. I'll try `tracklist` suggestion.

**Comment by goestohollywood** [comment]
So I do see "Gingy (Wishlist)" when I open console and input `tracklist` but still have yet to come across it. I've noticed if items are in, let's say a Scav's inventory that's still alive, I won't see the item until that Scav is dead, at which point the loot message will pop as "X (in corpse)" or whatever. Is there a way to see loot that's wishlisted in alive Scav/PMC inventories?

**Comment by sailro** [comment]
Closing this one. We only search inside static containers (so only dead scav). That's because we cache the position several seconds for better performance. If we start tracking on live scavs, we'll see not-up-to-date values.
