### ISSUE TITLE
Some bots not showing on map/radar

### ISSUE THREAD

**Issue by paulsnoops** [sailro/EscapeFromTarkov-Trainer#373]
I noticed I was getting hit by some bots that didn't show up on map/radar even with all the settings enabled (players/scavs/bosses etc.) I had just killed Reshala, who was showing fine but none of his followers were. I done some testing and found that it wasn't limited to a specific type of bot, it happened in the next raid with a PMC (though some of them were showing up, one of them wasn't). I posted a gif below where you can see his muzzle flash. I confirmed I still had the correct settings enabled.

![EscapeFromTarkov_EHnAZkGAtP](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/18243520/0a44839f-a08e-42a0-82c9-cf16934e3148)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/18243520/519c0851-7762-47e2-9cf8-e05ebe284c32)

**Comment by sailro** [comment]
I think this should be fixed now:
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/474/files
