### ISSUE TITLE
Error SSL/TLS

### ISSUE THREAD

**Issue by Hasji** [sailro/EscapeFromTarkov-Trainer#375]
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.13.0.23399) in D:\Rodj\games\Escape From Tarkov ? [y/n] (y): y
Target EscapeFromTarkov (0.13.0.23399) in D:\Rodj\games\Escape From Tarkov.
Error: Базовое соединение закрыто: Не удалось установить доверительные отношения для защищенного канала SSL/TLS.
Error: Базовое соединение закрыто: Не удалось установить доверительные отношения для защищенного канала SSL/TLS.
Unable to compile trainer for version 0.13.0.23399. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

Press a key to exit...

**Comment by sailro** [comment]
See #81

**Comment by Hasji** [comment]
.NET Framework 4.8 или более позднее обновление уже установлены на этом компьютере.

**Comment by Hasji** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/81190903/437061a7-8e44-435e-b335-4ca52201312c)
