### ISSUE TITLE
Installer Fails for Branch dev-0.13.1.25206

### ISSUE THREAD

**Issue by RogueTech67** [sailro/EscapeFromTarkov-Trainer#379]
Was asked by the Installer to file and issue, so I did.   Thanks

-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.13.1.25206) in C:\NoScan\Games\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.13.1.25206) in C:\NoScan\Games\EFT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.1.25206 not found.
Trying to disable faulting feature(s): GameState, Hits, WallShoot.
>> Try #2 Compilation failed for master branch.
Unable to compile trainer for version 0.13.1.25206. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

Press a key to exit...

**Comment by solareon** [comment]
@sailro I just tried this on a clean install of SPT-AKI-3.6.0 and it failed to compile.

```PS D:\EFT - SPT 3.6.0> .\Installer.exe
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.1.25206) in D:\EFT - SPT 3.6.0.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.1.25206 not found.
Trying to disable faulting feature(s): Hits, Quests, Health, GameState, Ammunition, QuickThrow, WallShoot.
>> Try #2 Compilation failed for master branch.
Unable to compile trainer for version 0.13.1.25206. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues
PS D:\EFT - SPT 3.6.0> .\Installer.exe
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.1.25206) in D:\EFT - SPT 3.6.0.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.1.25206 not found.
Trying to disable faulting feature(s): Hits, GameState, WallShoot.
>> Try #2 Compilation failed for master branch.
Unable to compile trainer for version 0.13.1.25206. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues
PS D:\EFT - SPT 3.6.0>```

First run was without having run SPT once, second is after running SPT. It seems like the installer isn't detecting that it's in an SPT-AKI install. I am getting my Visual Studio environment set back up again.

**Comment by sailro** [comment]
ah okay. my bad.

**Comment by solareon** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/769465/f9326997-88cf-4ffd-a086-c8def491bdf7)
This is the first run of errors from the build.

**Comment by sailro** [comment]
I'm having a look

**Comment by sailro** [comment]
Fixed https://github.com/sailro/EscapeFromTarkov-Trainer/pull/380

**Comment by RogueTech67** [comment]
> I think it's similar to #377.
> 
> You need spt-aki. We are not supporting the live version anymore.

@Sailro, thanks for looking at it.  Not sure what to tell you.  I had 0.13.1.3.25206 downloaded and "copied" to C:\NoScan\Games\EFT, the new SPT-AKI 3.6.0 installed, and ran the game once like I always do.  I tried it twice in a row and it failed with that error.  Now, without touching a thing, I ran the install right now (on the same untouched dir structure from the other day), and it compiled normally.  Not sure what else to tell you, but it's working now.  Thanks again, and this is a wonderful thing for lousy players like myself :-)

**Comment by sailro** [comment]
> 

Yes @RogueTech67, you were right, it was not working with the latest spt-aki 3.6. We fixed that and thanks to the installer infrastructure it was just a matter of re-running the installer :)

**Comment by RogueTech67** [comment]
> > 
> 
> Yes @RogueTech67, you were right, it was not working with the latest spt-aki 3.6. We fixed that and thanks to the installer infrastructure it was just a matter of re-running the installer :)

@Sailro, thanks.  I just noticed starting in SPT-AKI 3.6.0 the they are now putting their plugins in \BepInEx\plugins\spt.  Yours went to just \BepInEx\plugins.  Assuming they just separated theirs out, and modders are still using \BepInEx\plugins
