### ISSUE TITLE
Is there to control the opacity of the Wallhack glow?

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#38]
Hello, Thank you always.

Is there to control the opacity of the Wallhack glow?

Or can make sure that only the borders of the target are visible?

**Comment by sailro** [comment]
Yes, in the `%USERPROFILE%\Documents\Escape from Tarkov\trainer.ini` file:

```ini
EFT.Trainer.Features.Players.BearColor=[0.0,0.0,1.0,1.0]
EFT.Trainer.Features.Players.BossColor=[1.0,0.0,0.0,1.0]
EFT.Trainer.Features.Players.ScavColor=[1.0,0.921568632,0.0156862754,1.0]
EFT.Trainer.Features.Players.UsecColor=[0.0,1.0,0.0,1.0]
```

Colors are stored as an array of 'RGBA' floats. 

See:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/13

**Comment by sailro** [comment]
So you can use 0.0 for Alpha to remove the filling and only keep the borders

**Comment by MongMikng** [comment]
Thank you. but, I applied the alpha value of 0.0 and the opacity is the same as before, and all AIs look red.

**Comment by TestyTest-oss** [comment]
You can remove the red with material.SetColor("_FirstOutlineColor", Color.clear); in players. 

It won't give you an outline but you can change the opacity all the way to 0 if you want

**Comment by sailro** [comment]
```csharp
public static Color clear => new Color(0f, 0f, 0f, 0f),
```
 so using `[0.0,0.0,0.0,0.0]` should works as well in the config.

**Comment by sailro** [comment]
Perhaps I need to remove this hardcoded color.red and expose it in the config.

**Comment by sailro** [comment]
Done here:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/89bcaf4d9ea9265783d0970a9b524d041208424f

The border color is not hardcoded anymore.

```ini
EFT.Trainer.Features.Players.BearBorderColor=[1.0,0.0,0.0,1.0]
EFT.Trainer.Features.Players.BearColor=[0.0,0.0,1.0,1.0]
EFT.Trainer.Features.Players.BossBorderColor=[1.0,0.0,0.0,1.0]
EFT.Trainer.Features.Players.BossColor=[1.0,0.0,0.0,1.0]
EFT.Trainer.Features.Players.ScavBorderColor=[1.0,0.0,0.0,1.0]
EFT.Trainer.Features.Players.ScavColor=[1.0,0.921568632,0.0156862754,1.0]
EFT.Trainer.Features.Players.UsecBorderColor=[1.0,0.0,0.0,1.0]
EFT.Trainer.Features.Players.UsecColor=[0.0,1.0,0.0,1.0]
```

You can use `save` to re-create the proper `%USERPROFILE%\Documents\Escape from Tarkov\trainer.ini`. Update it then use `load` to refresh settings in-game.
