### ISSUE TITLE
spt aki 3.5.8?

### ISSUE THREAD

**Issue by ByYasin** [sailro/EscapeFromTarkov-Trainer#383]
The menu doesn't come up and there's nothing in the console?

win 11 22h2

**Comment by sailro** [comment]
EFT/AKI versions?

Are you sure you have run the game at least once before compiling/installing the trainer ?

**Comment by ByYasin** [comment]
@sailro 

yes, I ran the game once and then I installed the trainer.
If the version is: SPT AKI 3.5.8 - 0.13.0.5.23399

**Comment by sailro** [comment]
I'm sure I tried this one and it was working.

Could you share you `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\Player.log` ?

**Comment by ByYasin** [comment]
[Player.log](https://github.com/sailro/EscapeFromTarkov-Trainer/files/12262742/Player.log)

**Comment by sailro** [comment]
I can see that the trainer is loaded:

`[Info   :   BepInEx] Loading [AKI.EftTrainer 1.0.0]`

Weird. 

Any chance you can try with latest 3.6.0 and associated build ?

**Comment by ByYasin** [comment]
It's using a different version of the game, and unfortunately at the moment. 3.6.0 :(

**Comment by sailro** [comment]
Well, no error in the log, the trainer is loaded. Did you try to re-run the installer to see? Or to double-check your `trainer.ini`

**Comment by solareon** [comment]
Have you changed monitor resolutions? I've had issues where the settings menu can get hidden off screen due to my trainer.ini having it set to a resolution outside the render resolution.

@sailro maybe we can add a check for if the trainer window is outside the render resolution on startup?

**Comment by ByYasin** [comment]
> Have you changed monitor resolutions? I've had issues where the settings menu can get hidden off screen due to my trainer.ini having it set to a resolution outside the render resolution.
> 
> @sailro maybe we can add a check for if the trainer window is outside the render resolution on startup?


If you're talking about the game resolution, yes I changed it, no solution?

**Comment by ByYasin** [comment]
> Well, no error in the log, the trainer is loaded. Did you try to re-run the installer to see? Or to double-check your `trainer.ini`

yes i tried, no solution.

trainer.ini In what position exactly?

**Comment by solareon** [comment]
```
EFT.Trainer.Features.Commands.Key="RightAlt"
EFT.Trainer.Features.Commands.X=2579.0
EFT.Trainer.Features.Commands.Y=401.0
```

Those lines show what key opens the trainer and what position the box is in. If you clear them it should rebuild to safe defaults of right alt and mid screen.

**Comment by ByYasin** [comment]
> ```
> EFT.Trainer.Features.Commands.Key="RightAlt"
> EFT.Trainer.Features.Commands.X=2579.0
> EFT.Trainer.Features.Commands.Y=401.0
> ```
> 
> Those lines show what key opens the trainer and what position the box is in. If you clear them it should rebuild to safe defaults of right alt and mid screen.

In what directory exactly do I edit this?

**Comment by sailro** [comment]
`%USERPROFILE%\Documents\Escape from Tarkov\trainer.ini`

**Comment by ByYasin** [comment]
Thank you very much for the answers that worked. Have a nice day all of you.

**Comment by sailro** [comment]
Great, I'm going to create a PR to fix this issue.
