### ISSUE TITLE
Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

### ISSUE THREAD

**Issue by jrgago11** [sailro/EscapeFromTarkov-Trainer#387]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/73812484/c170446d-a070-4d2c-9c10-de6b1cb78ed5)

**Comment by solareon** [comment]
Do you have a proxy or some other SSL mitm inspection device or antivirus/firewall running? This looks to be an error with an overzealous firewall blocking traffic

**Comment by jrgago11** [comment]
I tried this trainer before and it works,then i uninstalled the game and downloaded a updated 3.6.0 then tried to install this trainer again,but now thats the issue
On the antivirus/firewall, i also tried turning them off but nothings change
Thanks for the reply btw

**Comment by solareon** [comment]
@jrgago11 you can try using something like this in powershell to verify that your powershell can access github. The installer simply downloads the code from github and then performs the compilation against your local SPT-AKI install.

`Invoke-WebRequest -Uri https://github.com/sailro/EscapeFromTarkov-Trainer -Method Head`

**Comment by jrgago11** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/73812484/e213c42d-c74f-48cb-a51c-2a933c24ae47)

**Comment by solareon** [comment]
It looks like there is a firewall issue just targeting the installer application. This is beyond the scope of the trainer as it successfully works on multiple other computers.

Additionally I noticed that you might be trying to install this against the live version of Tarkov? This is not supported after BSG removed the NLog method we use to inject the trainer into the EFT code space. We currently only support SPT-AKI.
