### ISSUE TITLE
it doesn't work for version 12.9.10988

### ISSUE THREAD

**Issue by Zenon-ed** [sailro/EscapeFromTarkov-Trainer#39]
I don't have any knowledge in programming so i could be wrong but mine is not working for the JET 0.12.9.10988.
The erro that the command prompt displays for me is:
Compilation failed for master branch.
Branch dev-0.12.9.10988 not found.
Unable to compile trainer for version 0.12.9.10988. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by sailro** [comment]
Hello,

Two things:

- 12.9.x series are quite old now, and I cannot even see a matching 12.9.10988 in the EFT changelog (so perhaps it is specific to `JET`)
- I do not use `JET`, only sptarkov so I have no clue about the possible issue. From my understanding `sptarkov` is fully legal, but I'm not sure for `JET`, so I do not plan to support this scenario with the trainer.

Thanks!
