### ISSUE TITLE
Doesn´t work on new wipe.

### ISSUE THREAD

**Issue by ScottyOnBS** [sailro/EscapeFromTarkov-Trainer#390]
Just says that it is patched. Any ideas how to run it now? Current game version: 0.13.5.0.25725

**Comment by solareon** [comment]
We only support spt-aki currently due to bsg patching nlog a couple wipes back. Please wait for a new spt-aki release and we'll see what needs fixing for the new release.

**Comment by zzj0402** [comment]
> Just says that it is patched. Any ideas how to run it now? Current game version: 0.13.5.0.25725

wow dude what are you trying to do?
