### ISSUE TITLE
map and silent problem 

### ISSUE THREAD

**Issue by noise87** [sailro/EscapeFromTarkov-Trainer#391]
i m8, thx for ur good work. i have 2 issue..
1st. is the silent aim, only on automatic weapons (set in single too) i die, i try to see down setting but nothing work, can u help me ?
2nd. is the map, in map mode don0t see map in background, how i can fix this?

**Comment by solareon** [comment]
We are still researching the silentaim issue under #360 . As for the map issue is this on Streets/Labs/Factory? For streets bsg has some weirdness related to culling on this map that hasnt been a priority fix. For labs and factory they need to have the correct culling level set which there really isn't any documentation for so the overhead view also won't work on those two maps.

**Comment by noise87** [comment]
1st of all thx, for silent is ok, i just use mk-18 and all is ok XD.... for the map, is on all maps, no one show

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/468
