### ISSUE TITLE
Q: how does the ammo cheat work in regards of mixed ammo in magazines ? 

### ISSUE THREAD

**Issue by ShadoweCZ** [sailro/EscapeFromTarkov-Trainer#392]
title

if i load multiple types of ammo and use the ammo cheat, will it just shoot the first ammo loaded or will it cyrcle thru the whole magazine (using all the ammo types in order as they are stacked in the magazine) ? 

if it dosnt cyrcle thru all the ammo would it be possible to implement it ?

**Comment by solareon** [comment]
It currently takes whatever is loaded in the chamber and adds it to the magazine after firing. I'm not entirely sure how tarkov internally counts the added round if it goes at the top or bottom. Might be able to test this with mixing tracers and non tracers in a gun. If you can do that test and report back we can look at rearranging the logic for it if needed. My recommendation would be 1 tracer then like 5 non tracers to test and see if the tracer comes every shot or every 6th shot

**Comment by leonardovac** [comment]
Ammo is added to the bottom, and it cycles through everything as it usually would.
No changes are needed.
