### ISSUE TITLE
0.13.1.3.25206 No quests?

### ISSUE THREAD

**Issue by aierxiya** [sailro/EscapeFromTarkov-Trainer#393]
I download SPT

**Comment by solareon** [comment]
@aierxiya Do you have any errors in the console? Also quest objectives are only shown for stuff like planting items, visit a spot, or looting a particular quest item. Quests that need random loot to be turned in or kill x number of enemies don't show in the tracker.

**Comment by aierxiya** [comment]
No,also I haven't health and hit
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/86341129/78e9a244-28d2-45c1-bd07-7e54122dd001)

**Comment by solareon** [comment]
@aierxiya can you please re run the installer and post the logs from that here please? This would assist in troubleshooting.

**Comment by aierxiya** [comment]
Where is the log file path

**Comment by solareon** [comment]
You will need to open a command prompt window and then run the installer in that and it'll give you the log on the screen

**Comment by aierxiya** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/86341129/c70c7140-88d0-4eb6-be56-c6b039803656)

**Comment by aierxiya** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/86341129/bbb799a3-4331-446f-bc6a-081282673ad6)

**Comment by solareon** [comment]
@aierxiya it looks like like it's not detecting the installation of SPT. The installer should look like this https://github.com/sailro/EscapeFromTarkov-Trainer/issues/377#issuecomment-1646919385

Could you try re running the SPT installer, launching the game once and then running the trainer installer?

**Comment by aierxiya** [comment]
I tried, but still

**Comment by solareon** [comment]
Do you get the prompt in the trainer installer that says SPT-AKI detected?

**Comment by aierxiya** [comment]
No

**Comment by sailro** [comment]
I'm quite sure you don't have spt-aki installed. I repro the exact same behavior on the 'stock' game.

Please make sure ton install spt-aki properly. You will not be able to play 'live' with this trainer anymore.

**Comment by solareon** [comment]
Yeah that is not a supported configuration. SIT's online mod doesn't deobfuscate in the same manner as SPT-AKI which means some of the methods we use to get the classes to modify won't work.

**Comment by aierxiya** [comment]
OK
