### ISSUE TITLE
About aimbot

### ISSUE THREAD

**Issue by CARROT114514** [sailro/EscapeFromTarkov-Trainer#394]
aimbot seems to aim at a target behind an obstacle, sometimes even a mountain

**Comment by sailro** [comment]
That's quite weird because the aimbot is doing a `Physics.Linecast` to detect if the target is "visible" (without something blocking the shot). That's why currently the aimbot is not firing when a target is behind bared wire fence.

**Comment by CARROT114514** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer/assets/142997130/aeb9dd03-2855-46ba-8a54-c2d821f1fa6b

**Comment by CARROT114514** [comment]
> 202308280949.mp4

Maybe it's because I used the  mod reshade-shaders and my graphics settings 
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/142997130/95f3c1ce-739a-4948-9664-b24b7e712f5a)

**Comment by CARROT114514** [comment]
> 这很奇怪，因为瞄准器正在检测目标是否“可见”（没有东西阻挡射击）。这就是为什么目前瞄准器在目标在带刺铁丝网后面时不会开火的原因。`Physics.Linecast`
> 
> 您是否有更多信息，以便我们可以尝试重现？也许瞄准机器人能够用1px发现头部，而你无法用自己的眼睛看到它。

Like this 

https://github.com/sailro/EscapeFromTarkov-Trainer/assets/142997130/502de3c1-2aa9-4fda-b027-367dab7cfea1

**Comment by sailro** [comment]
Ah good catch @leonardovac. I was thinking of the SilentAim, not the manual aimbot. But not sure we want to change that though. It can be quite useful to follow an enemy and then shoot as soon as he's visible.

**Comment by Billybishop** [comment]
> Ah good catch @leonardovac. I was thinking of the SilentAim, not the manual aimbot. But not sure we want to change that though. It can be quite useful to follow an enemy and then shoot as soon as he's visible.

Hi team, this is actually a long standing issue that I designed a solution for a while back, which can be found in the issue linked here:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/75

We don’t currently have a consensus on that implementation though, and as Sebastian mentioned, being able to track an enemy through cover is particularly useful— which I hadn’t considered when designing that solution. 

Maybe we can continue the discussion there and explore adding a subfeature toggle for the proposed visibility checking with the non-silent aiming mode?

**Comment by leonardovac** [comment]
Hi @Billybishop, I saw it after commenting on the issue, On my local repo I've added a **toggle** on the menu _(which works only for normal Aimbot)_ already.
The only downside of the visibility check (with the current method): only the head bone works as intended.
Check below:
![Control-V](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/37460201/83b53a01-df7b-408c-9cd9-f3e571c924e1)
