### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Ra1nyVirth** [sailro/EscapeFromTarkov-Trainer#395]
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.13.5.25837) in C:\Battlestate Games\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.13.5.25837) in C:\Battlestate Games\EFT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.5.25837 not found.
Trying to disable faulting feature(s): Ammunition, Health, Quests, Hits, QuickThrow.
>> Try #2 Compilation succeed for master branch.
We found a fallback! But please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues
Created NLog.EFT.Trainer.dll in C:\Battlestate Games\EFT\EscapeFromTarkov_Data\Managed.
Created outline in C:\Battlestate Games\EFT\EscapeFromTarkov_Data.
Warning: EscapeFromTarkov 0.13.0.21531 or later prevent this trainer to be loaded using NLog configuration.
It is now mandatory to use SPT-AKI/BepInEx, or to find your own way to load the trainer. As is, it will not work.
Already patched NLog.dll.nlog in C:\Battlestate Games\EFT\EscapeFromTarkov_Data\Managed.

Help me

**Comment by solareon** [comment]
This trainer does not work on Live anymore or with SIT's online coop mod. Based on your log output you are not running SPT-AKI therefore the trainer will not work.
