### ISSUE TITLE
Disabled features.

### ISSUE THREAD

**Issue by yeetmans** [sailro/EscapeFromTarkov-Trainer#396]
When compiling the source using the universal installer, is there a way to get it to *not* disable features on a failed compilation? id like to get every feature here, as im using it for testing, but i cant verify if the feature does what i need it to do because it automatically disables hits, quests, health, ammunition, and quickthrow.

i understand im using a more recent version of SPT than what is currently supported, but it is working for me and im not having any glaring issues reguarding the software.

would I have to compile it on my own and remove the flags for disabled features being pulled to compile without having it automatically diable these "faulting features" 
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/123055118/296a98af-78df-4bac-b6bd-f0207338f97c)

**Comment by solareon** [comment]
Yeah you would need to install Visual Studio and compile that way to see why each feature is being disabled. When you do this though visual studio is just going to fail compilation for whatever the errors are. Unfortunately I'm away from my main development machine so I can't do too much testing on the new spt but I should have better access in about a week or so.

**Comment by sailro** [comment]
The installer is disabling features because we are not even able to compile them. It is thanks to the way we try to keep each feature self-contained.

Often this is caused by obfuscated types/properties/methods. `spt-aki` is patching EFT assemblies to restore proper names and we are using this to keep a consistent source code, trying to avoid all those risky obfuscated members.

When we cannot, and we really need access to those members, we use Reflection.

**Comment by yeetmans** [comment]
Amazing, ill try to reinstall visual studio today and see if i cant compile it and see what its saying, if it fails trying to find methods for altering them, could i theoretically update the offsets or structs to them to update them to the most recent version?

**Comment by solareon** [comment]
Yep you can try and fix them to get it to compile with all features. Next week I should be back at my main pc and I can troubleshoot it further to see why it's not detecting the SPT-AKI install and to fix the missing features.

**Comment by yeetmans** [comment]
Youre the best, ill see what i can do on my end in the mean time, thank you!
