### ISSUE TITLE
How to uninstall 

### ISSUE THREAD

**Issue by 3pound** [sailro/EscapeFromTarkov-Trainer#399]
How do i uninstall the trainer fully so i am able to play live eft without getting banned? I tried to user the installer and it installed some files to the battlestate games folder. I wish to get rid of all the file related. Thank you in advance. Also is not working for 13.5

**Comment by solareon** [comment]
Run `Installer uninstall "C:\Battlestate Games\EFT"` replacing the path to where your live folder is and it will remove files installed by the trainer. To be 100% safe though you should just delete your BSG folder and reinstall live.
