### ISSUE TITLE
Can't turn wallhack (seeing enemy silhouette through walls)

### ISSUE THREAD

**Issue by UprootedSeeker** [sailro/EscapeFromTarkov-Trainer#40]
Even though in the menu I have every setting set to off the wallhack (enemy silhouettes through walls) won't shut off.

Is there any way to fix this problem?

**Comment by sailro** [comment]
Once enemies have been "outlined", they will stay like that until the next raid. New spawns should respect the current setting though.

**Comment by ShadoweCZ** [comment]
adding other forms of wallhack would be helpfull workaround
it should be able to turn it off and even if not, its not that bad looking :)

**Comment by sailro** [comment]
Fixed here:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/42a51a4e24c2985f2139d78223d2ff3114d59b0a
