### ISSUE TITLE
Can't find download button for Universal installer. I click zip and get no exe..

### ISSUE THREAD

**Issue by DuRaK228339** [sailro/EscapeFromTarkov-Trainer#401]

**Comment by solareon** [comment]
[This is the release page](https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-2.2)
and then you download this zip
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/769465/20d56b3b-13dc-44af-8917-10fdb2ce9ea6)
And when you unpack this zip you don't have an executable? Sounds like your virus scanner is eating it.

**Comment by DuRaK228339** [comment]
I have infinite loading of "Assets"...
