### ISSUE TITLE
Error: Unable to connect to the remote server

### ISSUE THREAD

**Issue by nol1q** [sailro/EscapeFromTarkov-Trainer#403]
![Untitled](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/145984080/fd7ee589-9d86-4b85-a929-998bfc8c8923)
![Untitled1](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/145984080/6d043e6c-0919-4d95-b6a6-c63674816e25)
i don't no what causing this but i tried turning off antivirus and firewall even installing vpn nothing helped.
p.s. im from russia mb this causing problems cuz for downloading files from github i am using vpn addon.

**Comment by solareon** [comment]
It would appear that your VPN isn't covering command line applications.  I don't think there is anything we can do to help you on that one. Maybe try a different vpn that covers all the traffic on your computer not just a vpn extension in your browser.
