### ISSUE TITLE
spt 3.7.0

### ISSUE THREAD

**Issue by Kogzu** [sailro/EscapeFromTarkov-Trainer#404]
just reporting that spt is updatet to 3.7.0, ammunition, quests, hits and health feature are faulting.

**Comment by sailro** [comment]
I'm going to fix that given 3.7.0 was released. Thanks

**Comment by sailro** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/d9b9a9c2-c175-4a9f-b103-7cff876ab078)
