### ISSUE TITLE
takes away things

### ISSUE THREAD

**Issue by charlessnapp7** [sailro/EscapeFromTarkov-Trainer#405]
it takes away ammo hits health and quest wich i use all so kinda of a problem idk how to fix it is it just bc im on the newest version of spt?
![spt](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/114387467/3b033f61-e7fe-4ddc-897a-c2e633703f10)

**Comment by sailro** [comment]
Dupe as #404
