### ISSUE TITLE
Loot Esp Not Working

### ISSUE THREAD

**Issue by Victorsena1347** [sailro/EscapeFromTarkov-Trainer#407]
Hello i'm using 3.6.1 and the loot Esp doesn't show the items, i've tried using no mods, putting all possible names for the item, when i put "tracklist" it shows is looking for my wishlist tracked items, all loot options are enabled but nothing happens and have this error on console

[Exception] : NullReferenceException: Object reference not set to an instance of an object
EFT.Trainer.Features.LootItems.FindItemsInContainers (EFT.GameWorld world, System.Collections.Generic.List`1[T] records) (at <1b4003a3e7fc405aa87bec9c929f23f2>:0)
EFT.Trainer.Features.LootItems.RefreshData () (at <1b4003a3e7fc405aa87bec9c929f23f2>:0)
EFT.Trainer.Features.CachableFeature`1+<RefreshDataScheduler>d__6[T].MoveNext () (at <1b4003a3e7fc405aa87bec9c929f23f2>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <85d1d3e7744a4a47b5f51883bf40bba2>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class312:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
EFT.Trainer.Features.<RefreshDataScheduler>d__6:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by solareon** [comment]
Please upgrade to 3.7.0 as it is now available. We do not support anything except the current release of SPT-AKI. You could try building from branch `dev-0.13.1.25206` but beyond that I'd just upgrade to the latest release as the trainer works with that version.

**Comment by Victorsena1347** [comment]
it was build in  Try #1 Compilation succeed for dev-0.13.1.25206 branch.
