### ISSUE TITLE
Loot sometimes wrongly indicated in containers and corpses

### ISSUE THREAD

**Issue by toxicspike** [sailro/EscapeFromTarkov-Trainer#408]
Hey guys,
Playing on spt 3.7:
Sometimes Loot is indicated to be in containers, but not actually there. Had this happen with Salewa that were supposedly inside medical bags, as well as ammo and similar in corpses.
Today I caught it with thermite not actually being present in a cache as well as ammo / items i looted myself still being shown as inside a corpse.

[screen-capture.webm](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/10299219/6cefa644-7bb2-49ac-83e8-380e5d3db8ca)

[screen-capture (2).webm](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/10299219/4109e498-18a9-46d7-b899-806cce657dc8)

I already tried unselecting and reselecting "track wishlist", as well as disabling and re-enabling the loot function, that didn't help.

**Comment by solareon** [comment]
Yeah that is definitely something broken there. I'll try to take a look and see if maybe there was some change in 3.7 that moved how loot was presented to the trainer.

**Comment by k0les0** [comment]
Please write a correct, working example of searching for loot on the example of a gold chain. I can't figure it out

**Comment by sailro** [comment]
Ok I had a look at the issue. 

We are doing something stupid :)

So in the loot feature we have:

`SearchInCorpse`: to allow to search tracked items in corpses.

And we have 

`ShowCorpses`: to show all corpses without condition. (this is the stupid one).

To optimize thing we have this:

https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Features/LootItems.cs#L94

So if nothing is tracked we do nothing (so we do not even show corpses)

As soon as you track something, we'll show corpses (we'll display `Corpse`). But this is not the same thing as when we find the tracked loot in a corpse (we'll display `XXX in Corpse`).

So I'll remove this `ShowCorpses` options in the `loot` feature, I move it to the `Lootable Container` feature where we can display stashes, airdrops, etc. With checkboxes select what we want to display: Corpses, Airdrops, ....
