### ISSUE TITLE
wallhack not work

### ISSUE THREAD

**Issue by hayder189** [sailro/EscapeFromTarkov-Trainer#409]
when I reach character level 15-20, my wallhack partially or completely disappears, everything is displayed on the map and radar, but there are no chams in the game

**Comment by hayder189** [comment]
https://imgur.com/a/zxyf9tL

**Comment by hayder189** [comment]
sometimes it loads after 10 minutes

**Comment by hayder189** [comment]
![Безымянный](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/77511287/96010a07-7abf-4c0b-9a2b-aef58dd97238)

**Comment by hayder189** [comment]
Here are the errors that the console shows when I turn on the input function, sometimes it loads within 5-10 minutes, and sometimes it doesn’t

**Comment by FeN1X1945** [comment]
> ![Безымянный](https://user-images.githubusercontent.com/77511287/277098434-96010a07-7abf-4c0b-9a2b-aef58dd97238.png)


I have the same error, but only when I change weapons to another, my character freezes, input disappears

**Comment by sailro** [comment]
This callstack is definitively interesting to double check.

Thanks!

**Comment by sailro** [comment]
@FeN1X1945 @hayder189 I think I fixed the issue here: https://github.com/sailro/EscapeFromTarkov-Trainer/commit/cdfd115e75ab1a75ae167e39d191f705f9702e52

Could you try to re-install the trainer? It should be good now.
