### ISSUE TITLE
Missing features 

### ISSUE THREAD

**Issue by ELGithubUser9000** [sailro/EscapeFromTarkov-Trainer#411]
trainer works perfectly, however im missing some features like Radar and map...any ideas?

**Comment by hayder189** [comment]
you'll probably be shocked, but these functions exist

**Comment by ELGithubUser9000** [comment]
> you'll probably be shocked, but these functions exist

where
![sshot-002](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/119786554/2eb8e4d8-bc18-4ce8-8ff7-7d355da10dc8)

**Comment by yuyuds** [comment]
> > you'll probably be shocked, but these functions exist
> 
> where
> ![sshot-002](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/119786554/2eb8e4d8-bc18-4ce8-8ff7-7d355da10dc8)
> 

![IMG-20231020-WA0009.jpg](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/104011028/22673a67-0107-4c87-a1b1-22e54566e51e)

What are you on about mate?

**Comment by ELGithubUser9000** [comment]
> > > you'll probably be shocked, but these functions exist
> > 
> > 
> > where
> > ![sshot-002](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/119786554/2eb8e4d8-bc18-4ce8-8ff7-7d355da10dc8)
> 
> ![IMG-20231020-WA0009.jpg](https://user-images.githubusercontent.com/104011028/276997348-22673a67-0107-4c87-a1b1-22e54566e51e.jpg)
> 
> What are you on about mate?

Sir if you compare your menu to mine you can clearly see mine doesn't include some features yours already have like weather/quickthrow and im here asking why thats what im on about

**Comment by WoodenGlaze** [comment]
SPT-AKi updated, thats probably why.

This is what the universal installer more than likely would've said:
`-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.5.26535) in G:\3. Games\SingleplayerTarkov.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.5.26535 not found.
Trying to disable faulting feature(s): Quests, Hits, Ammunition, QuickThrow.
>> Try #2 Compilation succeed for master branch.
We found a fallback! But please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues
[SPT-AKI] detected. Please make sure you have run the game at least once before installing the trainer.
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries.
If you install this trainer on stock binaries, the game will freeze at the startup screen.
Continue installation (yes I have run the game at least once) ? [y/n] (y):`

**Comment by sailro** [comment]
Yes, make sure that:

1- you are using EFT with SPT-AKI
2- re-run the installer to get the latest features

Thanks!
