### ISSUE TITLE
Unable to compile trainer for version 0.13.5.26535.

### ISSUE THREAD

**Issue by Guenther4** [sailro/EscapeFromTarkov-Trainer#412]
D:\Games\SPT-AKI\EFT 13.5>installer.exe
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.5.26535) in D:\Games\SPT-AKI\EFT 13.5.
Error: Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine
Vertrauensstellung hergestellt werden..
Error: Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine
Vertrauensstellung hergestellt werden..
Unable to compile trainer for version 0.13.5.26535. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

Translation of the german part:
Error: The underlying connection was closed: No connection could be made for the protected SSL/TLS channel
trust can be established.

**Comment by sailro** [comment]
Please see this one:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/81

**Comment by Guenther4** [comment]
None of the Options provided solved the issue.

Am Di., 24. Okt. 2023 um 20:42 Uhr schrieb Sebastien Lebreton <
***@***.***>:
