### ISSUE TITLE
Null reference exception, memory leak

### ISSUE THREAD

**Issue by PandoExpress** [sailro/EscapeFromTarkov-Trainer#415]
**SPT Version** - spt-3.7.1
**Trainer version** - Latest (installer-2.2)

**Other mods installed:**
AmandsGraphics.1.5.3
BigBrain-0.3.1
Waypoints-1.3.2
EFTApi
GamePanelHUD
Priscilu_2.5.1
SAIN.2.1.5
LootingBots-1.1.4
SWAG-Donuts-v3.2.2

Hi,
Seeing an issue where in a raid, toggling "wallhack off" will cause floods of null reference exceptions, FPS drops to very low, and memory spikes. After a few minutes the game crashes out to a black screen (due to 100% 32gb memory usage).

I've replicated it on Shoreline, Streets, and Customs but it doesn't happen as soon as you load in, it can take a few minutes or 10 minutes. I also have "loot on" with a custom tracklist if that matters. All other trainer settings are as default.

Screenshots attached - the last few times I've tracked this, the guid in the message has been the same
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/150540224/25ab65ee-4d47-46bf-9ca7-b3baa8454aa5)
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/150540224/69904359-3e86-48be-b0ac-dacdf6dfda93)
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/150540224/6dd2ccf8-559f-42e5-8408-9761f0c12e07)

Happy to test/uninstall mods if it helps find some conflicting mod

**Update:** It seems like toggling "wallhack on" again stops the exceptions, but does not release memory in use. And again, "wallhack off" will start the errors flooding again

**Comment by sailro** [comment]
I just fixed the exception, but I think is probably related to #296 regarding memory.

Closing as dupe.

**Comment by PandoExpress** [comment]
Thanks for the quick fix! Played two full raids on customs, toggling the setting on/off, and did not see this issue 👍
