### ISSUE TITLE
Night Issue

### ISSUE THREAD

**Issue by TwistedSkar** [sailro/EscapeFromTarkov-Trainer#416]
When i use the night trainer option my screen just turn black, i was able to use it before this i dont know what changes.

Just tested using night vision with ingame item fix it, but when i remove nightvision screen turns to black. able to open inventory

**Comment by sailro** [comment]
Just tried with woods, and it is working properly. spt-aki 3.7.3.

Which map/spt-aki are you on?

**Comment by TwistedSkar** [comment]
every map and spt aki 3.7.1 but previously on 3.6.2 (last spt before 3.7.0) it started failing too when i add more mod so i think its due to mod conflict, ill try to findout more which mod is conflicted.
