### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by kolimatro** [sailro/EscapeFromTarkov-Trainer#420]
I use sptarkov. 
1. I didn't find the NLog.dll.nlog file in it
2. when using the installer, it gives this:
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/101217219/13315cf6-660e-4d14-8020-c4d61a62664e)

**Comment by kolimatro** [comment]
And where can I download aki-efttrainer.dll ?

**Comment by kolimatro** [comment]
The Bradmower is off.
During installation .NET Framework says that a newer version is installed.

**Comment by sailro** [comment]
See #81
