### ISSUE TITLE
what is the dotnet sdk version?

### ISSUE THREAD

**Issue by sovzzz** [sailro/EscapeFromTarkov-Trainer#421]
in the code, it says that is .NET framework 4.7.1
and in readme, it's csharp 9, it means at least .NET 5
so ,does this means i should dismiss the TargetFrameworkVersion in csproj and choose the latest .NET? But how to do it? VS forced me to choose .NET from framework 2.0 to 4.8.1, even I have installed .NET 8 SDK
<img width="428" alt="image" src="https://github.com/sailro/EscapeFromTarkov-Trainer/assets/60016107/6e6de9dc-2926-4b32-9abb-d69e54671975">

**Comment by sailro** [comment]
Use VS 2022 17.8, because we need language support for C# 12.

Do not worry about the target framework. We can perfectly keep .NET FW 4.7.x. It is just compiler stuff.
