### ISSUE TITLE
Doesn't work. alot of yapping about errors

### ISSUE THREAD

**Issue by ArnuxPro** [sailro/EscapeFromTarkov-Trainer#422]
the twainer doesnt work pwease hewp 
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/152339588/cd236613-5710-4f7b-8805-c14f48fbd987)

**Comment by solareon** [comment]
SPT-AKI doesn't support 0.13.9 yet. Once it supports that we can fix the issues with the trainer compiling.
