### ISSUE TITLE
Force Enable Faulty Features

### ISSUE THREAD

**Issue by TormundBF** [sailro/EscapeFromTarkov-Trainer#423]
Is there a way we can force these if they are disabled? I have tried enabling them in the trainer.ini to no avail.

Most of it work via the Stay In Tarkov framework, but I think the issue is that the game version is 27050.

Thanks

![Screenshot_1](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/152425773/7271a1ff-91fd-4d2b-9bd8-992c1c906af7)

**Comment by solareon** [comment]
Same issue as #422. You can't force a feature to compile that won't compile as is. SPT doesn't support this version yet so we can't do anything until they upgrade to the latest release.
