### ISSUE TITLE
Unable to compile - 0.13.5.26535

### ISSUE THREAD

**Issue by cptcl** [sailro/EscapeFromTarkov-Trainer#424]
Used installer as usual (did it like that since SPT 3.6.x or longer)
Folder as usual i use "C:\Games\Z_SPT_AKI_373" where the last digits is the version.
now installer window shows

```
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Target EscapeFromTarkov (0.13.5.26535) in C:\Games\Z_SPT_AKI_373.
>> Try #0 Compilation failed for master branch.
>> Try #1 Compilation failed for dev-0.13.5.26535 branch.
Unable to compile trainer for version 0.13.5.26535. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

Press a key to exit...
```
Any idea? Thx in advance

**Comment by sailro** [comment]
Yes, please download the latest installer.

**Comment by sailro** [comment]
Let me double check.

**Comment by sailro** [comment]
Here is a debug version of the latest installer:
https://www.dropbox.com/scl/fi/sj178e8ad1qifankrjo07/Installer-2.3-debug.zip?rlkey=j231jiup5khntiivaeekgmpes&dl=1

Perhaps we'll be able to spot something with it.

On my end:
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/9485c60b-cc39-418c-8e79-1ed6519730ca)

**Comment by cptcl** [comment]
> Here is a debug version of the latest installer: https://www.dropbox.com/scl/fi/sj178e8ad1qifankrjo07/Installer-2.3-debug.zip?rlkey=j231jiup5khntiivaeekgmpes&dl=1
> 
> Perhaps we'll be able to spot something with it.
> 
> On my end: ![image](https://private-user-images.githubusercontent.com/638167/287007673-9485c60b-cc39-418c-8e79-1ed6519730ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjUwMTMsIm5iZiI6MTcwMTM2NDcxMywicGF0aCI6Ii82MzgxNjcvMjg3MDA3NjczLTk0ODVjNjBiLWNjMzktNDE4Yy04ZTc5LTFlZDY1MTk3MzBjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxNzE4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzVmMTJkMDE1NTYwN2IyNDBiNGIzNWYzMmJhZjk2NDlmMTk5YTc3NGIxYzYyOWE4NzUwNTg4MDdjMzJlMTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sanQrghWb0Vj9ErNh-Ig4KcL5yGCsmTxFWM7t6icIZs)

Downloaded debug version.. and it worked right out of the box. Dont know what was the problem
But as u can see in my first post, the installer didnt even ask me if i have started the game once. wierd

**Comment by sailro** [comment]
Are you sure you really used the latest installer and not an old one sitting in your download folder ? :)
