### ISSUE TITLE
Loot function not working

### ISSUE THREAD

**Issue by asdkevinasd123** [sailro/EscapeFromTarkov-Trainer#425]
I tried to track down airdrop and downed pmc via the loot function.  Below is the config I tried to use. 
```
EFT.Trainer.Features.LootItems.Enabled=true
EFT.Trainer.Features.LootItems.Key="Keypad7"
EFT.Trainer.Features.LootItems.CacheTimeInSec=3.0
EFT.Trainer.Features.LootItems.Color=[0.0,1.0,1.0,1.0]
EFT.Trainer.Features.LootItems.MaximumDistance=2000.0
EFT.Trainer.Features.LootItems.SearchInsideContainers=true
EFT.Trainer.Features.LootItems.SearchInsideCorpses=true
EFT.Trainer.Features.LootItems.ShowCorpses=true
EFT.Trainer.Features.LootItems.ShowPrices=false
EFT.Trainer.Features.LootItems.TrackedNames=["Sealed weapon case","Weapon (sealed)","Dogtag BEAR","Dogtag USEC"]
EFT.Trainer.Features.LootItems.TrackWishlist=true
```

I want to track Sealed Weapon Case and Dogtag to track down airdrop and downed pmc respectively but so far it did not seems to work. Nothing is displayed on screen. I tried to set the Max Distance as 0 or 2000 and both does not seems to work. Am I doing something wrong here? Is there any log I can provide you with? Thanks!

**Comment by sailro** [comment]
You have to use short names (which is what you see in your inventory), or even IDs, not long names like you are doing.

You can use https://db.sp-tarkov.com/search

Like for the Sealed weapon case, the valid shortname is `Weapon (sealed)`. You can even use a partial match when needed. The id `64897ffc3656831810043165` should work as well.

**Comment by asdkevinasd123** [comment]
I used the shortname as well for Sealed Weapon Case, it is the 2nd element in the array. I guess that means airdrops are no good? Side question: can you have a function that just mark the airdrop location on screen like stash?

**Comment by asdkevinasd123** [comment]
["GoldChain"] should work.

**Comment by asdkevinasd123** [comment]
> You have to use short names (which is what you see in your inventory), or even IDs, not long names like you are doing.
> 
> You can use https://db.sp-tarkov.com/search
> 
> Like for the Sealed weapon case, the valid shortname is `Weapon (sealed)`. You can even use a partial match when needed. The id `64897ffc3656831810043165` should work as well.
> 
> Now the good question is, are we able to look into airdrops. This is something I need to check.

It worked now after I recompile the code somehow. And I managed to get airdrop to be shown on screen like stash. Thanks you for your incredible codes!

**Comment by sailro** [comment]
Could you create a PR so I can have a look on your changes?

**Comment by k0les0** [comment]
> > You have to use short names (which is what you see in your inventory), or even IDs, not long names like you are doing.
> > You can use https://db.sp-tarkov.com/search
> > Like for the Sealed weapon case, the valid shortname is `Weapon (sealed)`. You can even use a partial match when needed. The id `64897ffc3656831810043165` should work as well.
> > Now the good question is, are we able to look into airdrops. This is something I need to check.
> 
> It worked now after I recompile the code somehow. And I managed to get airdrop to be shown on screen like stash. Thanks you for your incredible codes!

please share the dll

**Comment by sailro** [comment]
> > > You have to use short names (which is what you see in your inventory), or even IDs, not long names like you are doing.
> > > You can use https://db.sp-tarkov.com/search
> > > Like for the Sealed weapon case, the valid shortname is `Weapon (sealed)`. You can even use a partial match when needed. The id `64897ffc3656831810043165` should work as well.
> > > Now the good question is, are we able to look into airdrops. This is something I need to check.
> > 
> > 
> > It worked now after I recompile the code somehow. And I managed to get airdrop to be shown on screen like stash. Thanks you for your incredible codes!
> 
> please share the dll

There is no dll to share, you just have to use the installer. It's mandatory to compile against your own installation.

**Comment by sailro** [comment]
Closing, after merge. Thanks again for your contribution.
