### ISSUE TITLE
 Branch dev-0.13.9.27622 not found.

### ISSUE THREAD

**Issue by baratan1** [sailro/EscapeFromTarkov-Trainer#427]
Target EscapeFromTarkov (0.13.9.27622) in C:\Battlestate Games\SIT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.13.9.27622 not found.
Trying to disable faulting feature(s): Ammunition, Quests, QuickThrow.
![image_2023-12-11_195712258](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/153551345/c2f3d745-ce11-4025-ad61-e32940b4cc21)

**Comment by solareon** [comment]
SPT-AKI 3.7.5 has not been released yet. Once it is released we will work on fixing the issues. As mentioned in the readme we only support SPT-AKI.
