### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by AboPiPs** [sailro/EscapeFromTarkov-Trainer#431]
Could you please update for current version? Seems like trainer is looking for elder master file. Thanks a lot for a great work. 
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/154736154/1dbba14e-f9f4-4d45-85ac-6a554aeb9e36)

**Comment by solareon** [comment]
SPT-AKI doesn't support beyond 0.13.5.3.26535. Once they update then we can update the trainer
