### ISSUE TITLE
Outdated.

### ISSUE THREAD

**Issue by AboPiPs** [sailro/EscapeFromTarkov-Trainer#432]
2nd day in row thread gets deleted. All I mentioned trainer is outdated. If big sweats knows the ways around how to launch please let me know instead of deleting post. 
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/154736154/dbd03e4d-7b62-4c35-8779-2d0b97a8e3ad)

**Comment by toxicspike** [comment]
Check the reply on your previous post:
_SPT-AKI doesn't support beyond 0.13.5.26535. Once they update then we can update the trainer_

26535 is what current spt aki uses:
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/10299219/4cca3e6a-8fec-4674-b8b9-d8482745d7ed)
On 3.7.5 the trainer works perfectly fine

**Comment by AboPiPs** [comment]
A latest version SPT-AKI 3.7.5 v2.25.0 (19Dec) runs fine with latest Tarkov 0.13.9.27928. However unable to install trainer for it, unless I am doing something serious wrong.

**Comment by sailro** [comment]
I'm going to have a look

**Comment by sailro** [comment]
Just tried with latest spt-aki 3.7.6:

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/bb97675a-a49b-4864-91d6-c8d7f52adb62)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/f11978a4-7d71-4382-aeed-eb161627eff5)

So everything is working as expected.

Closing
