### ISSUE TITLE
Errors or im dumb

### ISSUE THREAD

**Issue by ArnuxPro** [sailro/EscapeFromTarkov-Trainer#433]
yea im tryna download the trainer for 3.75 spt and it just yapps about real eft. either im stupid or is there no way to download it for spt-aki now? its weeird
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/152339588/c4449dcc-fa16-4e18-a8e3-db05c31f03ec)

**Comment by solareon** [comment]
Try placing the installer where you have spt-aki installed at and then running it.

**Comment by sailro** [comment]
0.14.0.28333 is not supported by spt-aki yey
