### ISSUE TITLE
a doubt

### ISSUE THREAD

**Issue by ConnorMAD** [sailro/EscapeFromTarkov-Trainer#434]
Hi, this might be a silly question, but I'm new and I have some questions.
I noticed that memory capture is not done through offsets and pointers, am I right?
So how do you capture addresses and write them down?

**Comment by solareon** [comment]
There isn't a need to reference a specific address or offset when you can call the class names directly. Spt-aki provides consistent names for almost all of the methods we use and in cases where it isn't we can use reflection to find the class name. A lot of spt aki mod devs don't use reflection and instead call the various gclass names hence why they break with each version update as bsg's obfuscation shifts the class names around during compilation .
