### ISSUE TITLE
I have a real tarkov and spt-aki

### ISSUE THREAD

**Issue by MKS1750** [sailro/EscapeFromTarkov-Trainer#435]
how can I install trainer so that it installs on spt-aki and not on real tarkov

**Comment by solareon** [comment]
Place the trainer in the root of the spt-aki folder and run it from there. Sometimes the SPT-AKI path is not detected especially if the installer is run from a different drive than the spt-aki folder.

**Comment by MKS1750** [comment]
Can you send me aki-efttrainer.dll? I am very worried about my Tarkov account as it is very updated and I bought the EOD version.

**Comment by sailro** [comment]
We have a dedicated installer for compiling everything. If you are worried that's fine, but then do not use third party trainers.
