### ISSUE TITLE
change directories

### ISSUE THREAD

**Issue by ArnuxPro** [sailro/EscapeFromTarkov-Trainer#436]
i got sptarkov 3.7.5 and i got real tarkov in the new 1.40 patch or whichever. ive tried to run the installer in every place in the sptarkov folder but keeps redirecting it to the real tarkov. any fix?

**Comment by MKS1750** [comment]
same situation

**Comment by MKS1750** [comment]
sailro, could you make a separate dll file for the BepInEx plugins?

**Comment by solareon** [comment]
Do you have any console output? Did you place the installer in the sptarkov folder?

**Comment by sailro** [comment]
And what about using `Installer "path/to/eft-sptaki"` to install the trainer in a specific path ?.

**Comment by ArnuxPro** [comment]
i mean i ran the installer in every single sptarkov folder and place, but it just automatically made it connect to the real tarkov. didnt even let me change directories nothing. just auto tarkov

**Comment by ArnuxPro** [comment]
yo nvm thx i figured it out 🗡️
