### ISSUE TITLE
X-ray highlight issue

### ISSUE THREAD

**Issue by BushmanG** [sailro/EscapeFromTarkov-Trainer#438]
So when I use the wallhack option on SPT, it used to show people in the correct colour and when you turned it off, it all worked perfectly. Now after I have updated the game and redownloaded the trainer, the wallhack makes everyone the same colour and when you turn it off, they all stay highlighted in the same colour. 

Does anyone know why this is happening? The picture included for the wallhack settings and my general settings are also attached.

![eft](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/28630532/65ddb6ac-651c-45c2-8ec7-650861c58b63)

[trainer - Copy.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/13828754/trainer.-.Copy.txt)

**Comment by solareon** [comment]
Are they being highlighted in pink? If so try and add the two files from [Files](https://github.com/sailro/EscapeFromTarkov-Trainer/tree/8e252c6e7bc2574d933003ec77b18a4ee6fea9b2/Files) to the managed folder and see if that clears it up.

**Comment by BushmanG** [comment]
> Are they being highlighted in pink? If so try and add the two files from [Files](https://github.com/sailro/EscapeFromTarkov-Trainer/tree/8e252c6e7bc2574d933003ec77b18a4ee6fea9b2/Files) to the managed folder and see if that clears it up.

Can you please run me through it? I'm a noob at this stuff and would appreciate a quick instruction.

**Comment by solareon** [comment]
Does the wallhack look like this image?
![](https://user-images.githubusercontent.com/638167/222186879-a88a267e-16ba-4532-85ec-8cb385737947.png)

If so you need to go to that link I sent above and download the file named outline and put it inside your sptarkov folder. I don't have the latest spt-aki installed on my pc so I don't know the exact path but that file will show the outlines and colors properly

**Comment by BushmanG** [comment]
I put the file inside what I believe to be the right folder, but it didn't seem to make a difference. 

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/28630532/00ac30e2-d63d-4b4b-8d54-d7d14c8c534d)

All scavs, players and bosses are all lit up like this and stay that way even when the hack is off. I don't know what to try next.

**Comment by solareon** [comment]
Okay. I don't remember exactly where that file has to go but try and put it in the folder with the dlls. I don't have sptarkov installed on this machine but I'll try and test it when I get home in a few days.

**Comment by BushmanG** [comment]
> Okay. I don't remember exactly where that file has to go but try and put it in the folder with the dlls. I don't have sptarkov installed on this machine but I'll try and test it when I get home in a few days.

Thanks, mate. Appreciate your time

**Comment by sailro** [comment]
The `outline` file should be in the `EscapeFromTarkov_Data` folder. (But this should be done automatically by the installer).

**Comment by BushmanG** [comment]
It had done it automatically. Upon deleting the file and replacing it with the one from the linked page, it is now fixed, for whatever reason. Thank you very much to both @solareon and @sailro for the assistance.

As for why this happened, I have no idea. Maybe an older file? I truly don't know. Thanks again!!
