### ISSUE TITLE
 I didn’t understand how to specify my own installation path on the command line

### ISSUE THREAD

**Issue by MKS1750** [sailro/EscapeFromTarkov-Trainer#439]
where should I enter let settings? I tried to write to the installer and he told me to press either y or n
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/155352495/08741435-69c7-4399-8bb1-668ff23ce49b)

**Comment by solareon** [comment]
@MKS1750 it is where you run the executable. So open a terminal and then specify like [this](https://github.com/sailro/EscapeFromTarkov-Trainer/issues/436#issuecomment-1876763342)

**Comment by MKS1750** [comment]
@solareon how can I open a terminal? I'm very unfamiliar with this

**Comment by solareon** [comment]
by clicking on the start menu and typing powershell. You can go to the folder where you downloaded the installer and hold the shift key and right click in the white space and then there should be an option to open in powershell similar to this
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/769465/c2650c5d-2c1e-4f37-9d79-2adc36a5c7da)

**Comment by MKS1750** [comment]
I did everything according to the instructions, he writes me that the name Installer.exe not recognized. 
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/155352495/4c34eae7-86f7-49ab-b8fd-4f7b16cbab3b)

**Comment by solareon** [comment]
what did you name the installer file as? Try typing install and then pressing the tab key to let it autocomplete

**Comment by MKS1750** [comment]
as the file was downloaded, it remained the same, did not change the name

**Comment by MKS1750** [comment]
if you just run the installer through the terminal, then everything will work; he will want to download the trainer for Life Tarkov

**Comment by solareon** [comment]
okay so move the installer into your sptarkov folder and run it from there.

**Comment by MKS1750** [comment]
what happens if the trainer is accidentally installed on Tarkov Life?

**Comment by MKS1750** [comment]
Thanks for the help, I was able to install the trainer
