### ISSUE TITLE
Run the latest version?

### ISSUE THREAD

**Issue by Spambustas** [sailro/EscapeFromTarkov-Trainer#44]
Can the latest game version be used?

**Comment by sailro** [comment]
Yes it should work, the Universal Installer will try to compile against current binairies, and if it cannot compile, it will display an error.

**Comment by asalvi0** [comment]
@sailro it doesn't compile, since the installer it's looking for a new branch matching the EFT binaries version: 
![image](https://user-images.githubusercontent.com/775410/124678284-d460d880-de87-11eb-8e7e-496f96e2fea2.png)

**Comment by sailro** [comment]
Ah ok interesting. I'm going to have a look.

**Comment by sailro** [comment]
Ok fixed, this is working now with latest `0.12.11.13160`:

![image](https://user-images.githubusercontent.com/638167/124817065-25bba700-df1e-11eb-8373-b92837c0317d.png)

You just need to run the installer again (no need to re-download it).

I advise you to not use this trainer with the 'live' version (only with `spt-aki`). BattleState / BattlEye will ban you if you try to use it 'live'.
