### ISSUE TITLE
Loot Not Working

### ISSUE THREAD

**Issue by G28X0Y0** [sailro/EscapeFromTarkov-Trainer#440]
<img width="1583" alt="Screenshot 2024-01-05 125957" src="https://github.com/sailro/EscapeFromTarkov-Trainer/assets/13813795/4b6af322-5afe-496a-bbf4-6fb9cad1521b">

**Comment by sailro** [comment]
You have to add something to track with the `track` command. See the documentation here:
https://github.com/sailro/EscapeFromTarkov-Trainer?tab=readme-ov-file#configuration
