### ISSUE TITLE
console errors

### ISSUE THREAD

**Issue by Warzone848** [sailro/EscapeFromTarkov-Trainer#444]
whenever I put a command on the console like health for full health, or ammo for full ammunition, or nocll for no collision I always get a message error, for every command I put.

**Comment by sailro** [comment]
Did you read the documentation ?

https://github.com/sailro/EscapeFromTarkov-Trainer?tab=readme-ov-file#configuration

Like you have parameters to pass.

like `health on`

**Comment by Warzone848** [comment]
Yes I put for instance health on or and other command on but always says
error invalid "0" string

**Comment by Warzone848** [comment]
i'm using spt version 2.27.0

**Comment by Warzone848** [comment]
sorry using spt-aki 3.7.6

**Comment by Warzone848** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/156860153/6ee204b8-3fd6-4074-930a-ceef8668b56f)

**Comment by Warzone848** [comment]
i put health on loot on but get same messages

**Comment by sailro** [comment]
it's working on my side, so I guess you do not even have the trainer installed.

**Comment by Warzone848** [comment]
a restart of my computer fixes it weirdly enough. but some
commands don't work like speed, aimbot, silent aim, loot, and no collision.
I get the error no such command message.

**Comment by sailro** [comment]
Could you show us the output of the installer?

**Comment by sailro** [comment]
See #446
