### ISSUE TITLE
Some functions are not displayed

### ISSUE THREAD

**Issue by theeelove** [sailro/EscapeFromTarkov-Trainer#446]
like Quests quest
like stash LootableContainers

**Comment by sailro** [comment]
Could you show us the output of the installer?

**Comment by theeelove** [comment]
![1](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/157230472/883cd0e5-8196-4318-a3ff-7a9c11355a29)
wow some functions is red 
why

**Comment by sailro** [comment]
Because we only support versions along with spt-aki. So EFT 0.13.5.26535 for now.
