### ISSUE TITLE
trackr * and tracksr * color question

### ISSUE THREAD

**Issue by paulsnoops** [sailro/EscapeFromTarkov-Trainer#448]
Hey, is there a way to track _any_ rare and _any_ superrare items at the same time with different colors? Currently the below commands throw an error so I assume I'm using the wrong command or it's not supported. Tracking both * at the same time shows them all in one default color, it would be nice if you could separate them

For example:
trackr * yellow
tracksr * red

**Comment by sailro** [comment]
use:
`trackr "* yellow"`
and
`tracksr "* red"`

**Comment by paulsnoops** [comment]
Thanks! They seem to work individually but I can't get them to both show at the same time even though they are both tracked.

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/18243520/ecc1c68e-2edf-44f4-a131-f99fe368c992)

**Comment by sailro** [comment]
We should be good now. Please re-install using the intaller.

Thanks!
