### ISSUE TITLE
Error logging in to the game

### ISSUE THREAD

**Issue by DuMoH4uK35** [sailro/EscapeFromTarkov-Trainer#451]
Hello. Such a problem: when entering the game, such an error pops up( Everything is done according to the instructions, I entered the game, created a character, went on a raid, came out with the status "survived". I quit the game, installed the trainer using the universal installer, started logging into the game and started giving this error( The game version is 14.0.1.28476. Server version 3.8.0
![1707589675154](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/34032748/9eaadca9-3177-4205-be69-42a292d2f48c)

**Comment by RodneyGER** [comment]
As the Bleeding Edge realease says, it dont support client or server mods.

**Comment by solareon** [comment]
As the notes in the SPT-AKI Discord mention the only way to use mods with the Bleeding Edge version is to compile the client and server yourself. The ready made downloads will not work with ANY mods. Once the 3.8.0 version is fully released we can work on getting the trainer working for that version.
