### ISSUE TITLE
Error The mod (EscapeFromTarkov-Trainer-master) is missing package.json

### ISSUE THREAD

**Issue by Pyost** [sailro/EscapeFromTarkov-Trainer#452]
![изображение_2024-02-17_010553651](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/160288458/d108b91c-876e-4042-8383-5c6e3e368e7f)

**Comment by sailro** [comment]
We do not maintain this nor support EmuTarkov. You have to find and ask those who made the fork.
