### ISSUE TITLE
wallhack issue

### ISSUE THREAD

**Issue by thaer1994** [sailro/EscapeFromTarkov-Trainer#453]
some times especially in factory the charm behind some obstacles disappears and doesn't work and it comes back again when i change my position  , did anyone have the same problem ?

another quick question can i make a filter for the info tap to show only distance without the other information's ?

**Comment by sailro** [comment]
Yes I spotted the same issue in Factory. Tried to switch our shader and still repro.

Regarding displaying info: for now it's everything or nothing.
