### ISSUE TITLE
compiling error (installer 2.3)

### ISSUE THREAD

**Issue by DemShadowZ** [sailro/EscapeFromTarkov-Trainer#455]
![Unbenannt](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/162726944/0b572847-539c-454d-ac16-6f1553f78927)

Tested on multiple partitions
No problems with admin rights etc.

**Comment by sailro** [comment]
Yes this is expected, main is meant to compile with the latest released spt-aki versions.

That's why the installer tried to fallback to the proper branch after. And this was successful.
