### ISSUE TITLE
Branch dev-0.14.1.28965 not found.

### ISSUE THREAD

**Issue by beastcomov** [sailro/EscapeFromTarkov-Trainer#456]
![Installer_o4A5LTF7Tj](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/121089151/e2f43ed1-7b86-4835-a2dc-bd9d3499ad5b)
Please update to the new version EFT and fix features.

**Comment by sailro** [comment]
We plan to upgrade when spt-aki 3.8.0 will be released.
