### ISSUE TITLE
problems with Universal Installer

### ISSUE THREAD

**Issue by PepeChillua** [sailro/EscapeFromTarkov-Trainer#458]
Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Unable to compile trainer for version 0.13.5.26535.

**Comment by PepeChillua** [comment]
Is there any way I can fix this?

**Comment by sailro** [comment]
See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/81
