### ISSUE TITLE
CMD Error

### ISSUE THREAD

**Issue by Macwarswas** [sailro/EscapeFromTarkov-Trainer#46]
Hello all!

Once the cmd is opened, I get this error in the cmd for some reasons "No EscapeFromTarkov installation found, please re-run this installer, passing the installation path as argument.". Any clue on how to tackle this?

Thank you :)

**Comment by sailro** [comment]
Where is your EFT installed?

**Comment by Macwarswas** [comment]
On my D drive (I don't have space on the SSD)

**Comment by sailro** [comment]
I give up, we'll never make it with such answers

**Comment by Macwarswas** [comment]
The best help I've received lol xd
