### ISSUE TITLE
Target EscapeFromTarkov (0.14.1.28965) - disabled faulting feature(s): QuickThrow, NoRecoil, NoSway, Quests.

### ISSUE THREAD

**Issue by eeandee** [sailro/EscapeFromTarkov-Trainer#464]
Please help:
Target EscapeFromTarkov (0.14.1.28965)
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.14.1.28965 not found.
Trying to disable faulting feature(s): QuickThrow, NoRecoil, NoSway, Quests.
>> Try #2 Compilation succeed for master branch.

These are no longer functional in-game:
****QuickThrow, NoRecoil, NoSway, Quests**.**

**Comment by solareon** [comment]
Once SPT 3.8.0 is released we will update. From their Discord they are waiting on BSG to fix bugs that they can't fix before they have a release version

**Comment by eeandee** [comment]
Thank you!

**Comment by eeandee** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/152650233/ded49649-de80-4804-9262-e9beac8b41f1)

Hi, 

Any update related to this?
I'm currently using 3.8.0
