### ISSUE TITLE
TRACKING LOOT ISSUE AGAIN (SOLVED)

### ISSUE THREAD

**Issue by LeooM99** [sailro/EscapeFromTarkov-Trainer#467]
Hey there, first and foremost, I want to extend my gratitude to the creator and all the contributors of this trainer; it's truly top-notch. Now, onto the issue at hand. As it has occurred previously due to changes by the Tarkov devs (gotta love Nikita, haha) or some other unforeseen issue, certain items tend to be incorrectly tagged within containers or on corpses. And now, it's not just that; every time I try to track a specific type of ammunition, without fail, it always shows up as being on PMC corpses, when obviously, out of the eight PMC corpses in the raid, only one, or maybe none, actually has it. This happens with most types of ammunition, at least from what I've noticed—I haven't tested each one, just the top-tier ones. Hoping for a fix soon. Thanks a bunch in advance.

**Comment by sailro** [comment]
Are you using the latest version? I thought we already fixed this one.

**Comment by LeooM99** [comment]
I have SPT-AKI 3.8.0 and this tarkov version:

![tarkovVersion](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/139915588/14fcb08c-69ed-4d74-a1ec-80035979be87)

**Comment by sailro** [comment]
that's probably why. For now we support the latest stable, so spt-aki 3.7.6. (We will support 3.8.0 as soon as it is released as stable). When compiling the trainer with this unsupported 3.8.0 we have a lot of broken or incompatible features (and spt-aki has bugs as well). Let's wait for the final 3.8.0 to see if we still repro.

**Comment by LeooM99** [comment]
Oh, I see now. Apologies for bothering you with this nonsense. Didn't realize it. Looks like I'll have to downgrade the game. Thanks a bunch for everything.
