### ISSUE TITLE
SPT 3.8.0 New Installer Trainer spawns 0KB outline File.

### ISSUE THREAD

**Issue by ethanjia** [sailro/EscapeFromTarkov-Trainer#471]
SPT 3.8.0 New Installer Trainer spawns 0KB outline File.

Wallhack show Pink Charms. Replaced Github's 12KB outline Flie and then take correct color Wallhack.

**Comment by sailro** [comment]
Yes I spotted that as well, but not sure it is the installer yet.

**Comment by sailro** [comment]
I hit the issue once and since then, I'm unable to repro. It does not seem to be linked to the installer.

**Comment by sailro** [comment]
Found it, it was tricky. I'm going to release a new installer.
