### ISSUE TITLE
Not compiling 

### ISSUE THREAD

**Issue by Boss235798** [sailro/EscapeFromTarkov-Trainer#472]
Installer Fails to compile in Master Branch

Fresh install
SPT-AKI 3.8.0 
0.14.1.29197

![Screenshot 2024-04-06 204638](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/100441287/a6bbd25b-75ff-4b19-9322-7000bcc2a6fb)

**Comment by solareon** [comment]
Did you run SPT-AKI first?

**Comment by Boss235798** [comment]
Ups my fault......
It works now

**Comment by Boss235798** [comment]
@solareon I forgot to run SPT-AKI but it works now so i close this Thread....
Sorry for wasting your time
