### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by AidenHusky** [sailro/EscapeFromTarkov-Trainer#475]
I am unable to turn on quests and the command doesnt show in the command console or the gui. Where would I find the config file to change this manually?

**Comment by sailro** [comment]
Hello,

Please show us the installer output. I bet you are trying to install the trainer in a unsupported/non-spt-aki version

**Comment by AidenHusky** [comment]
I am on the latest one. I assumed that it would show the old quests and just not anything new. My apologies
