### ISSUE TITLE
Windows Defender blocks Installer 2.4 with a virus warning

### ISSUE THREAD

**Issue by tkaiser** [sailro/EscapeFromTarkov-Trainer#478]
**Describe the bug**
I downloaded the latest installer (2.4) from https://github.com/sailro/EscapeFromTarkov-Trainer/releases/download/installer-2.4/Installer-2.4.zip. Windows Defender on Windows 11 is blocking me from accessing the file and reports this threat as detected: `Trojan:Script/Wacatac.B!ml`

**Comment by sailro** [comment]
Indeed I repro with VirusTotal. It seems to come from the `ILRepack` tool we use to bundle several dll/exe in one files. If I build without this bundling method, it's all clear.

We recently bumped the version:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/b01ec9c4bd3330e7a505bae6c1f4ad3a5da6dd7d#diff-7935a83b23cd131410e038528704ea223d73a1447a0754afaa0b42feb67dfea0R47.

I'm going to go back to the previous version to see if it changes something.

**Comment by sailro** [comment]
I created a new release:

https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-2.5

And changed the installer technology (now standalone):
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/480

**Comment by sailro** [comment]
https://www.virustotal.com/gui/file/d37cb216a5ee578a8f541ae1c28d9d3e9eec05cc4f7bdb2f4063b5c28b12abd1

**Comment by sailro** [comment]
And I just added a workflow to automatically build the Installer from github actions.

So you are 100% sure it is built from this repo source without any alteration.

Going forward releases will be populated by github actions.
