### ISSUE TITLE
dev-0.14.1.29351

### ISSUE THREAD

**Issue by ImSophi** [sailro/EscapeFromTarkov-Trainer#479]
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.14.1.29351 not found.
Unable to compile trainer for version 0.14.1.29351. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by solareon** [comment]
Did you run sptaki one time before trying the installer?

**Comment by ImSophi** [comment]
I have many times

**Comment by sailro** [comment]
This is not expected to work, given we do not support this version. You can try to re-run the newest installer it will try to disable faulting features like this:

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/fcf6063d-1bf7-4350-bd7d-5bb83b2fac73)
