### ISSUE TITLE
Infinite loading spt-aki 1.6.0

### ISSUE THREAD

**Issue by TestyTest-oss** [sailro/EscapeFromTarkov-Trainer#48]
Currently doesn't work for the latest spt-aki version and causes infinite loading.

**Comment by sailro** [comment]
Which version ? 1.6.0 ? I tried 1.5.1.

Important: if you are using SPT-AKI, please make sure you have run the game at least **once** before installing the trainer. SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries. If you install this trainer on stock binaries, the game will freeze at the startup screen.

**Comment by TestyTest-oss** [comment]
Ah yeah that'll be it, I went and rebuilt from the latest just to make sure I wasn't missing anything only to find it then worked. Thanks!

**Comment by sailro** [comment]
Perfect !
