### ISSUE TITLE
Error: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by NotAnAdm1nHelloWorld** [sailro/EscapeFromTarkov-Trainer#485]
spt-aki 3.8.0 no mods, no addons or smth like that

**Describe the bug**
Error: The SSL connection could not be established, see inner exception.

**To Reproduce**
start the installer (both with cfg or with not)

**Expected behavior**
install trainer)))

**Screenshots**
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/66140854/7252decb-a39f-49a9-930a-ec092a6e6a99)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/66140854/ec4e011c-d4c9-48e2-af21-d02da0da37dd)

**Additional context**
tried 2 turn off all security proxy etc, tried to use ot with vpn or disable the vpn

**Comment by NotAnAdm1nHelloWorld** [comment]
upd: default hosts help me

C:\Windows\System32\drivers\etc\hosts

https://support.microsoft.com/ru-ru/topic/как-восстановить-содержимое-файла-hosts-по-умолчанию-c2a43f9d-e176-c6f3-e4ef-3500277a6dae

**Comment by sailro** [comment]
ah interesting. So you restored default hosts and it was ok ?
