### ISSUE TITLE
Run Installer Release 2.5  "Error: Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by ethanjia** [sailro/EscapeFromTarkov-Trainer#487]
Run Installer Release 2.5  "Error: Object reference not set to an instance of an object."

Release 2.4 is OK.  

Admin CMD
.NET Framework 4.7.2
.NET 8.0 Desktop Runtime (v8.0.2)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/1684482/de6d6e9b-b287-494e-8213-f0d68e768f18)

Could you provide Installer Release 2.4 link? Thanks.

**Comment by sailro** [comment]
Weird, I do not repro.

What is your CPU ? your OS ? Are you using a 32 bits OS ?

**Comment by ethanjia** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/1684482/a778c95c-8c44-4244-9370-00f2e07e4d4a)
64 bits Win 11, i7-12700KF

**Comment by ethanjia** [comment]
I solved this problem. 
I moved Installer.exe from D:\ to C:\games. My SPT-EFT is in C:\games\EFT.

Thanks.
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/1684482/9871c63a-9ecc-4241-a477-768453bd7f56)

**Comment by sailro** [comment]
Okidoki found it.

Indeed we had an issue when running the installer from any root folder.

Fixed

**Comment by sailro** [comment]
Released a new one:

https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-2.6

Thanks!
