### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nianfeng233** [sailro/EscapeFromTarkov-Trainer#489]
Same game entity. When I use MPT to start, I can compile the trainer, but when I switch to SIT, it will tell me that the compilation has failed. The game version is 29197. This is the link to SIT.
https://drnotdq.net/d/284-0315-%E8%BF%99%E4%B8%AA%E6%A1%A3 -Spt-380-29197-% E7% 89% 88% E6% 9C% AC% E6% 9B% BF% E6% 8D% A2% E5% 8C% 85--% E6% B8% B8% E6% 88% 8F% E6% 9C% AC% E4% BD% 93

**Comment by sailro** [comment]
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries. If you install this trainer on stock binaries (so even for this exact same version), you'll hit issues.

**Comment by sailro** [comment]
Ah sorry I think I misunderstood your issue.

Please have a look at #490 

You should just need to rerun the installer
