### ISSUE TITLE
0.14.1.3.29351 Plans

### ISSUE THREAD

**Issue by Stonewallx** [sailro/EscapeFromTarkov-Trainer#490]
Is there any plans to support 0.14.1.3.29351 as that's what SIT is on, or only SPT?

**Comment by sailro** [comment]
The plan is to support stable SPT versions as always. It seems SIT is using a newer EFT versions for now. I'm going to setup a SIT install to understand what's going on.

**Comment by sailro** [comment]
What is the easy way to get a beta spt-aki build for 0.14.1.3.29351 ?

**Comment by sailro** [comment]
SPT to start, I think this error is just related to the beta SPT version as usual. And SIT is just an extra mod to SPT in my understanding.

**Comment by sailro** [comment]
Yes thanks but I was seeking for something more technical :)

Anyway @Stonewallx @tslpy1, could you try this `installer` compiled in Debug mode, so we'll have exact errors:
https://github.com/sailro/EscapeFromTarkov-Trainer/actions/runs/8868730772/artifacts/1454650703

**Comment by sailro** [comment]
@Stonewallx perfect. Could you retry to run the installer? (I changed the sourcecode). I suspect a type name conflict with SIT. Let's see if we are able to remove previous errors.

**Comment by sailro** [comment]
> Am I supposed to use the same debug installer right?

Yes. The installer is downloading latest source from this repo before compiling.

Another try with the installer? 

I confirmed the issue:

`Namespace '<global namespace>' contains a definition conflicting with alias 'LootItems'.trainer`
