### ISSUE TITLE
You Do Not Have Permission To Access

### ISSUE THREAD

**Issue by serlise** [sailro/EscapeFromTarkov-Trainer#491]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
2024/04/30 3.8.0 (29197)

**Describe the bug**
You Do Not Have Permission To Access

**To Reproduce**
Run with administrator privileges or run regular double-click.

**Expected behavior**
Steps to reproduce the behavior: I can't, so I'm fixing the security system.
ex) https://youtu.be/pl59ODaP6no?si=LrXOg4Z3-eW8hyzj

**Screenshots**
N/A

**Additional context**
In version 3.6.0, the trainer 2.1 was used well.

**Comment by sailro** [comment]
Perhaps your antivirus is blocking the installer from running? Did you try to add an exception ?

**Comment by serlise** [comment]
> Perhaps your antivirus is blocking the installer from running? Did you try to add an exception ?

Yes, that's right. I tried running it after shutting down the Internet and rebooting, but that .exe is blocked.

**Comment by serlise** [comment]
> Perhaps your antivirus is blocking the installer from running? Did you try to add an exception ?

I removed the Windows security update KB5036892 from the control panel and it worked. 
Maybe something went wrong with every latest update. I just came across it from your hint. 
Thanks!
