### ISSUE TITLE
Unable to compile trainer for version 0.14.1.29197.

### ISSUE THREAD

**Issue by Shalyapin2008** [sailro/EscapeFromTarkov-Trainer#492]
01.05.2024

Game version - 0.14.1.29197
SPT-AKI version - 3.8.0

Downloaded installer -> Located it in my SPT version folder -> Launched it (both with and without admin rights).
Right after choosing the installation folder (path "C:/EFT_PVE/EFT") got red text: 
"
Error: The SSL connection could not be established, see inner exception.
Error: The SSL connection could not be established, see inner exception.
Unable to compile trainer for version 0.14.1.29197. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues
"
I have a couple of mods installed, but considering that the error appeared even before the download stage, I don't believe that this matters.

**Comment by Shalyapin2008** [comment]
> I believe you have an issue with your firewall blocking the installer talking to GitHub to get the files for compilation. Try disabling it and running the installer again.

Disabling firewall didnt help.

**Comment by sailro** [comment]
Check this where it seems to be solved: https://github.com/sailro/EscapeFromTarkov-Trainer/issues/485

**Comment by Shalyapin2008** [comment]
Did not work for me. Perhaps you could upload a pre-compiled version.

**Comment by sailro** [comment]
You definitively have an issue on your side preventing SSL connections to work properly. Do you use a proxy or something like that? You should have a look at other issues related to SSL. Make sure you are using an up-to-date OS.

And we use the universal installer especially so we don't have to bother with precompiled versions, breaking for every update.

**Comment by MRReaper43** [comment]
!
![bandicam 2024-05-03 17-58-43-157](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/110355164/5d2188d5-6b6b-46b7-bacf-ceb0c244e627)
 
i dont know what im doing wrong any suggestions?

**Comment by solareon** [comment]
> !
> 
> ![bandicam 2024-05-03 17-58-43-157](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/110355164/5d2188d5-6b6b-46b7-bacf-ceb0c244e627)
> 
>  
> 
> i dont know what im doing wrong any suggestions?

@MRReaper43 You are trying to compile for live which is not supported. The current trainer release only works for SPT-AKI 3.8.0 and similar forks which are on 0.14.1.29197.

**Comment by sailro** [comment]
@Shalyapin2008, could you try with this installer:
https://github.com/sailro/EscapeFromTarkov-Trainer/actions/runs/8972308184/artifacts/1477128334

I disabled SSL validation in this one (but we'll be able to see what's wrong).
Code Changes here:
https://github.com/sailro/EscapeFromTarkov-Trainer/pull/499/files

**Comment by Shalyapin2008** [comment]
Got this message

![Снимок экрана 2024-05-07 115706](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/55088406/35fd1ec9-0318-4ec9-86b0-55e5aecc33d1)

**Comment by Shalyapin2008** [comment]
Funny enough, I cannot download it with the link provided as well. Google error "NET::ERR_CERT_COMMON_NAME_INVALID", has something to do with an insecure connection and suspicious link. Same thing when I try to download ANY GitHub .zip archive. Maybe it is my ISP blacklisting GitHub or something of sorts. I will try to look into it.
 Any advice will be appreciated).

**Comment by solareon** [comment]
@sailro  what user agent string does the installer present when downloading from GitHub? That user agent might be tripping some security block in their router to prevent malicious code from being downloaded.

**Comment by sailro** [comment]
> @sailro what user agent string does the installer present when downloading from GitHub? That user agent might be tripping some security block in their router to prevent malicious code from being downloaded.

The default hander for HttpClient in C# is not setting any header I think (so no default user-agent). But indeed we can mimic an existing user-agent if we want.

**Comment by sailro** [comment]
And what about connecting your pc to your phone portable WiFi hotspot (with the phone really using mobile network) ? Just to check if it's ISP based (then it should work) or if it's something on your PC or personal network ? (it should fail).

**Comment by DiDrobyshev** [comment]
> Получил это сообщение
> 
> ![Снимок экрана 2024-05-07 115706](https://private-user-images.githubusercontent.com/55088406/328457719-35fd1ec9-0318-4ec9-86b0-55e5aecc33d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzYyMjMsIm5iZiI6MTcxNTQzNTkyMywicGF0aCI6Ii81NTA4ODQwNi8zMjg0NTc3MTktMzVmZDFlYzktMDMxOC00ZWM5LTg2YjAtNTVlNWFlY2MzM2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTg2NjIyMWFiNjk3MDBkMmE2ZGU1MWQzZmE5ZTg1YmUzYzJkNjRhMzFjMzE0ZjljYWYyZDQyZTZiNmM2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gM1Ti9pimIt-GHKjL-aB_M_KIphHeC0BrfoxJ00uBRM)

The same error occurs. Did you manage to find a solution?

**Comment by sailro** [comment]
> > Получил это сообщение
> > ![Снимок экрана 2024-05-07 115706](https://private-user-images.githubusercontent.com/55088406/328457719-35fd1ec9-0318-4ec9-86b0-55e5aecc33d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzYyMjMsIm5iZiI6MTcxNTQzNTkyMywicGF0aCI6Ii81NTA4ODQwNi8zMjg0NTc3MTktMzVmZDFlYzktMDMxOC00ZWM5LTg2YjAtNTVlNWFlY2MzM2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTg2NjIyMWFiNjk3MDBkMmE2ZGU1MWQzZmE5ZTg1YmUzYzJkNjRhMzFjMzE0ZjljYWYyZDQyZTZiNmM2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gM1Ti9pimIt-GHKjL-aB_M_KIphHeC0BrfoxJ00uBRM)
> 
> The same error occurs. Did you manage to find a solution?



> > Получил это сообщение
> > ![Снимок экрана 2024-05-07 115706](https://private-user-images.githubusercontent.com/55088406/328457719-35fd1ec9-0318-4ec9-86b0-55e5aecc33d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzYyMjMsIm5iZiI6MTcxNTQzNTkyMywicGF0aCI6Ii81NTA4ODQwNi8zMjg0NTc3MTktMzVmZDFlYzktMDMxOC00ZWM5LTg2YjAtNTVlNWFlY2MzM2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZTg2NjIyMWFiNjk3MDBkMmE2ZGU1MWQzZmE5ZTg1YmUzYzJkNjRhMzFjMzE0ZjljYWYyZDQyZTZiNmM2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gM1Ti9pimIt-GHKjL-aB_M_KIphHeC0BrfoxJ00uBRM)
> 
> The same error occurs. Did you manage to find a solution?

The "solution" is on your side. You have something to fix.

Same as the other user, you can use the test installer to see what's wrong:
https://github.com/sailro/EscapeFromTarkov-Trainer/actions/runs/8972308184/artifacts/1477128334

**Comment by sailro** [comment]
I added the SSL diagnostics in the latest installer to help users solving their own issues.
