### ISSUE TITLE
some things are broken for me.

### ISSUE THREAD

**Issue by ENGJack7** [sailro/EscapeFromTarkov-Trainer#493]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support. 

**Describe the bug**
it seems like all of the stuff thats supposed to track where things are, like the boxes, skeletons, and info for wall hack and the exfil locations are all super offset, but get closer to where they're supposed to be when you get closer to it. 

**To Reproduce**
i dont really know how to reproduce it. everything was working just fine until it just randomly started happening. 

**Screenshots**

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/168590919/c81cfca7-7610-4048-8bc9-fabc1cc994a9)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/168590919/d37f05f1-cb2e-4ca5-8e0a-23deb1755c40)

**Additional context**
i have no mods installed, and never messed with any files before any of this started happening. I've noticed that the charms for wallhack along with everything else, other than the things that i mentioned are broken, work just fine. I'm also using playing on version v0.12.12.32.20243 because that's what i prefer, but when i first installed this menu, everything was working perfectly. appreciate any help.

**Comment by sailro** [comment]
There is a known issue when resampling <> 1x. See https://github.com/sailro/EscapeFromTarkov-Trainer/issues/149

I guess you changed your graphics settings.

**Comment by ENGJack7** [comment]
I did fix the problem, but it wasn't the resampling that caused it. i never used it. I don't know what caused it. I've tested every other setting other than the ones that are known to break it and nothing happened. I know it was something in the graphics settings, because I reset the graphics settings and the problem went away. Thanks for the help.
