### ISSUE TITLE
[Question] Is there a way to hide the esp from game capture ?

### ISSUE THREAD

**Issue by ARROGANT7** [sailro/EscapeFromTarkov-Trainer#494]
Just wondering if there's a way to hide things like loot esp or bots from game capture on discord, sorry if this is not allowed to ask

**Comment by sailro** [comment]
It's not possible with this kind of Trainer, given the way it works (internal).

The only possible scenario that could work is using a DMA based Trainer on another machine with an HDMI fuser (combining two screens into one).

This way you'll see the game + ESP on your screen, but discord will only capture the regular game.
