### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 999Cashcat666** [sailro/EscapeFromTarkov-Trainer#497]
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.14.6.29862) in C:\Battlestate Games\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.14.6.29862) in C:\Battlestate Games\EFT.
-Try #0 Compilation failed for master branch.
- Try #1 Branch dev-0.14.6.29862 not found.
Trying to disable faulting feature/command: Aimbot, Ammunition, Feature, Hits, LootableContainers, NoSway, Quests,
QuickThrow, Spawn, Template.
- Try #2 Compilation failed for master branch.
Unable to compile trainer for version 0.14.6.29862. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

Press a key to exit...

**Comment by sailro** [comment]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/1b32cfb8-7f3c-448a-aa53-393156e1db65)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/fbf5aea5-7d88-4308-af12-e0a6bcbf2cca)

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/55d986d5-f14c-4b43-8989-a1a9ce1047f3)
