### ISSUE TITLE
Unable to compile trainer (Ver. 0.14.6.29862)

### ISSUE THREAD

**Issue by VPL91** [sailro/EscapeFromTarkov-Trainer#498]
I'm currently using SPT-Aki (latest version - 3.8.0) and tried to compile the trainer (as I've done before with previous versions), by using the _automatic installer_. However, this time, I keep getting the following error(s):

- Compilation failed for master branch
> Trying to disable faulting feature/command
- Compilation failed for master branch

Also, I've already checked and my firewall is disabled, so it should not be the issue here.

Other notes:
- I've tried compiling **only** after running the game once.
- I've tried compiling after having reinstalled SPT-AKI, with no mods. (Running the game with no mods, then compiling)
- I've tried compiling after having reinstalled SPT-AKI, with mods. (Running the game with some previously used - and 3.8.0 compatible - mods, then compiling)

Nothing worked.

Screenshot of the error:
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/168882374/450a41bb-1b54-44e0-b96f-5ced1c535b26)

**Comment by solareon** [comment]
Did you try running the installer from the folder where you have SPT installed? From your screen capture it looks like you aren't picking up the SPT folder and instead it's trying to build for live
