### ISSUE TITLE
Installer.exe immediately closes

### ISSUE THREAD

**Issue by finlleyl** [sailro/EscapeFromTarkov-Trainer#50]
when I run the installer, command appears and immediately closes

**Comment by sailro** [comment]
try running the installer from a command prompt. My guess is that the installer was not able to find EFT location.
So you need to run it like `installer.exe "path\to\EFT"`

Everything is already documented in the release.

**Comment by finlleyl** [comment]
> try running the installer from a command prompt. My guess is that the installer was not able to find EFT location.
> So you need to run it like `installer.exe "path\to\EFT"`
> 
> Everything is already documented in the release.

Thanks a lot, it works
