### ISSUE TITLE
Unable to compile trainer for version 0.14.6.29862. 

### ISSUE THREAD

**Issue by 1esheng** [sailro/EscapeFromTarkov-Trainer#501]
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/91392822/8b249b88-0cd0-492e-aa88-24e2956237d5)
Hi, I'm using Universal Installer 2.7, SPT version is 3.8.1.
How can I fix it?

**Comment by solareon** [comment]
Are you running the installer from within the SPT-AKI folder? It looks like you are trying to patch the live game which isn't supported

**Comment by 1esheng** [comment]
Hi, yes I am running in the SPT-AKI folder
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/91392822/c302c27f-e040-4b76-b7ba-a013666f977a)

**Comment by solareon** [comment]
Try launching it as administrator. It may not have permissions to that folder for some reason.

**Comment by 1esheng** [comment]
Hi, thanks so much for replying. But I have been running it as administrator but this doesn't work.

**Comment by solareon** [comment]
If you try running it from a powershell/command prompt does it find the right folder? You should be able to hold shift and right click in the SPT folder and it will give you an option for Powershell/Terminal

**Comment by 1esheng** [comment]
Hi, it found the correct folder, but again it won't run.

> If you try running it from a powershell/command prompt does it find the right folder? You should be able to hold shift and right click in the SPT folder and it will give you an option for Powershell/Terminal

Hi, it found the correct folder, but again it won't run.

**Comment by 1esheng** [comment]
> If you try running it from a powershell/command prompt does it find the right folder? You should be able to hold shift and right click in the SPT folder and it will give you an option for Powershell/Terminal

Hi, it found the correct folder, but again it won't run.

**Comment by sailro** [comment]
@1esheng are you sure this EFT version is supported by SPT-AKI ? Could you show us the server output ? Did you run the game once so that all assemblies are already patched ?

**Comment by 1esheng** [comment]
Hi, I'm sure I've run the game once and had no problems. Here is my server output
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/91392822/e7a03683-7be9-4d28-8919-b08193175dce)
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/91392822/4cda5fc1-2823-43ef-9971-6d6331114048)

**Comment by sailro** [comment]
Yes so we can see that the installer is not using the proper directory. It seems you are installing in your live folder and not in the spt one.

Normally you can ty to copy the installer to the spt folder and run it from there, but you can also run the installer from a command prompt like this:

`Installer "C:\path\to\your\SPT"`

**Comment by 1esheng** [comment]
> Yes so we can see that the installer is not using the proper directory. It seems you are installing in your live folder and not in the spt one.
> 
> Normally you can ty to copy the installer to the spt folder and run it from there, (I see this is what you are doing) but you can also run the installer from a command prompt like this:
> 
> `Installer "C:\path\to\your\SPT"`
> 
> Do you have several folders listed by the installer when you run it ? Make sure to select the SPT one.

Yes, you are correct, I installed into the wrong folder. Thank you very much for your help.
