### ISSUE TITLE
Can you write a more detailed manual on how the Track, Tracklist, list and loot commands work?

### ISSUE THREAD

**Issue by SsertesS** [sailro/EscapeFromTarkov-Trainer#503]
I don't quite understand how to add items for tracking.

**Comment by sailro** [comment]
Examples:

Open your command prompt while in raid, then use:

`track roler` to track the Roler Submariner gold wrist watch

this will update your tracklist, and display it's location (make sure the loot feature is on)

you can also use `track *` to track everything.

`untrack roler` to stop tracking

You have to use the loot shortname or a part of the shortname.

You can also use custom colors, and filter by rarity, but try to play with the system before.

**Comment by sailro** [comment]
@SsertesS were you able to use the tracking?
