### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by TheFluffiestFox** [sailro/EscapeFromTarkov-Trainer#504]
The trainer is out of date and needs an update.

**Comment by solareon** [comment]
We currently only support SPT running on 0.14.1.29197. I see from the SPT announcements that they have posted an update to version 3.8.3. If the trainer is not compiling for this version please post the output from the installer.

**Comment by Parker6614** [comment]
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.14.1.29197) in F:\Game\Escape from Tarkov offline ? [y/n] (y): y
Target EscapeFromTarkov (0.14.1.29197) in F:\Game\Escape from Tarkov offline.
>> Try #0 Compilation failed for master branch.
>> Try #1 Compilation failed for dev-0.14.1.29197 branch.
Trying to disable faulting feature/command: Aimbot, Ammunition, Feature, Ghost, Hits, LootableContainers, NoSway,
Quests, QuickThrow, Spawn, Template.
>> Try #2 Compilation failed for master branch.
Unable to compile trainer for version 0.14.1.29197. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

Press a key to exit...

Could you please check the output from installer? Thank you so much

**Comment by solareon** [comment]
> -=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-
> 
> 
> 
> Continue with EscapeFromTarkov (0.14.1.29197) in F:\Game\Escape from Tarkov offline ? [y/n] (y): y
> 
> Target EscapeFromTarkov (0.14.1.29197) in F:\Game\Escape from Tarkov offline.
> 
> >> Try #0 Compilation failed for master branch.
> 
> >> Try #1 Compilation failed for dev-0.14.1.29197 branch.
> 
> Trying to disable faulting feature/command: Aimbot, Ammunition, Feature, Ghost, Hits, LootableContainers, NoSway,
> 
> Quests, QuickThrow, Spawn, Template.
> 
> >> Try #2 Compilation failed for master branch.
> 
> Unable to compile trainer for version 0.14.1.29197. Please file an issue here :
> 
> https://github.com/sailro/EscapeFromTarkov-Trainer/issues
> 
> 
> 
> Press a key to exit...
> 
> 
> 
> Could you please check the output from installer? Thank you so much

@Parker6614 I believe you have not run spt aki one time before the installer. This is needed because of patches the spt makes to the binary that we rely on.

**Comment by FeN1X1945** [comment]
> На моей стороне:
> 
> ![изображение](https://private-user-images.githubusercontent.com/638167/331890957-0be26568-7ee6-44da-b15d-27d295145221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDgzMDEsIm5iZiI6MTcxNjMwODAwMSwicGF0aCI6Ii82MzgxNjcvMzMxODkwOTU3LTBiZTI2NTY4LTdlZTYtNDRkYS1iMTVkLTI3ZDI5NTE0NTIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNjEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjdjMGMzODcyOTU2ZjJkMjcyMmM3YzZkMjBkZDI0ZGEwNmZlODk0MDhiMDA4MDBjMjg1ZjI4NDIzM2QwMWI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CXwqh7W9kYmGrRji5PAV2Vo11p63yHCSEcRfzvQ-F3g)
> 
> ![изображение](https://private-user-images.githubusercontent.com/638167/331890990-0f7458c1-acc9-4d0e-b04f-d92ec3a7e61d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDgzMDEsIm5iZiI6MTcxNjMwODAwMSwicGF0aCI6Ii82MzgxNjcvMzMxODkwOTkwLTBmNzQ1OGMxLWFjYzktNGQwZS1iMDRmLWQ5MmVjM2E3ZTYxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNjEzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjZkYmExNmUzNmRhZjVmZjMwZDE5ZmNlNTUyNmNiNjlhYmQ3OWVmMjZhYTIxMTY1NWQ0YTA4MTMxZWEyYzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MDnN3Ecx3WXJAlADQuypzkGTZKi5ZCaFzfZHgQdy4po)
> 
> Так@solareonвсе верно, игру нужно запустить один раз.

I have the same thing, it won’t install, although I even played 2 raids

**Comment by solareon** [comment]
@FeN1X1945 can you post the output of the installer?

**Comment by FeN1X1945** [comment]
> @FeN1X1945можешь опубликовать вывод установщика?

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/40298006/9a3ea610-9e83-4648-8e8e-1fbf098c0341)

**Comment by solareon** [comment]
> > @FeN1X1945можешь опубликовать вывод установщика?
> 
> ![image](https://private-user-images.githubusercontent.com/40298006/332509702-9a3ea610-9e83-4648-8e8e-1fbf098c0341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTE5MTcsIm5iZiI6MTcxNjMxMTYxNywicGF0aCI6Ii80MDI5ODAwNi8zMzI1MDk3MDItOWEzZWE2MTAtOWU4My00NjQ4LThlOGUtMWZiZjA5OGMwMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE3MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTJjZDFlZGRkNjA0N2I4NmZhOTFjNzVhYmYyODVlNzFhYzliNTJjMDczZmYwMWU3YWVlYzc1NTJiNWRiODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t41C4AkBeRQnFjG87lWSJlRijPMz7kMcRAuPBdNyVxg)

@FeN1X1945 this is due to an issue with your connection that is not providing the correct SSL certificate. Unfortunately there isn't anything we can do about that and you may need to use a different connection such as tethering to your phone.

**Comment by FeN1X1945** [comment]
> > > @FeN1X1945можешь опубликовать вывод установщика?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/40298006/332509702-9a3ea610-9e83-4648-8e8e-1fbf098c0341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTE5MTcsIm5iZiI6MTcxNjMxMTYxNywicGF0aCI6Ii80MDI5ODAwNi8zMzI1MDk3MDItOWEzZWE2MTAtOWU4My00NjQ4LThlOGUtMWZiZjA5OGMwMzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE3MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNTJjZDFlZGRkNjA0N2I4NmZhOTFjNzVhYmYyODVlNzFhYzliNTJjMDczZmYwMWU3YWVlYzc1NTJiNWRiODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t41C4AkBeRQnFjG87lWSJlRijPMz7kMcRAuPBdNyVxg)
> 
> @FeN1X1945 this is due to an issue with your connection that is not providing the correct SSL certificate. Unfortunately there isn't anything we can do about that and you may need to use a different connection such as tethering to your phone.

It seems to me that this is on your part. because all my programs work correctly and yours worked too

**Comment by solareon** [comment]
@FeN1X1945 can you run the following command from a powershell prompt and paste the output here?
```ps
Invoke-WebRequest -Uri "https://github.com/sailro/EscapeFromTarkov-Trainer/archive/refs/heads/master.zip" -OutFile "master.zip" -Verbose
```

**Comment by FeN1X1945** [comment]
> @FeN1X1945 can you run the following command from a powershell prompt and paste the output here?
> 
> ```postscript
> Invoke-WebRequest -Uri "https://github.com/sailro/EscapeFromTarkov-Trainer/archive/refs/heads/master.zip" -OutFile "master.zip" -Verbose
> ```

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/40298006/f9c81c1b-d506-47ef-8f04-6d77d75dd64a)

**Comment by solareon** [comment]
You should have gotten something like this. I can't translate your error but it is related to your SSL problem. We can't fix problems with someone intercepting your SSL traffic.
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/769465/21c53cf7-d766-42f9-a73f-94827d05ec06)

**Comment by FeN1X1945** [comment]
> У вас должно было получиться что-то вроде этого. Я не могу перевести вашу ошибку, но она связана с вашей проблемой SSL. Мы не можем решить проблемы, связанные с перехватом вашего SSL-трафика. ![изображение](https://private-user-images.githubusercontent.com/769465/332537427-21c53cf7-d766-42f9-a73f-94827d05ec06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMTgzNzMsIm5iZiI6MTcxNjMxODA3MywicGF0aCI6Ii83Njk0NjUvMzMyNTM3NDI3LTIxYzUzY2Y3LWQ3NjYtNDJmOS1hNzNmLTk0ODI3ZDA1ZWMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxOTAxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDVkNWZlYzA5YWU3MzlhNDQ3YzIwOWZlYWI5ODNlZmNlYTg4ZGIyOWUwODk5NjRlN2U2MWI4MjlmYmI0M2UzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.odKmt7HUkm4Kl_R6YUSdjaBIhkX_u0kTIi2eRHbCVYw)

the problem is in the site's ssl, the browser sees it as hostile and not reliable

**Comment by FeN1X1945** [comment]
codeload.github.com typically uses encryption to protect your data. However, the credentials we received from codeload.github.com now are different from what it usually sends. It's likely that a malicious site is trying to impersonate codeload.github.com or the Wi-Fi connection page has lost its connection. Your information is still safe because Chrome terminated the connection before any data exchange took place.

The website codeload.github.com uses the HSTS mechanism. The site cannot be opened at this time. The failure could be caused by a network error or the actions of attackers. Most likely, the site will be up and running after some time.

**Comment by FeN1X1945** [comment]
can you upload the file to another source?

**Comment by solareon** [comment]
The installer is coded to only pull from github for the trainer code to compile. I created a feature requester under #507 to support providing the bundle as a zip for folks who have some SSL issue preventing the code from being downloaded.

**Comment by sailro** [comment]
discussed here https://github.com/orgs/community/discussions/49655

I'm quite sure this is related to a security software / antivirus / vpn / proxy / etc trying to man in the middle the SSL connection.

**Comment by FeN1X1945** [comment]
> The installer is coded to only pull from github for the trainer code to compile. I created a feature request under #507 to support providing the bundle as a zip for folks who have some SSL issue preventing the code from being downloaded.



> discussed here https://github.com/orgs/community/discussions/49655
> 
> I'm quite sure this is related to a security software / antivirus / vpn / proxy / etc trying to man in the middle the SSL connection.

Thank you for your advice and participation, everything turned out to be quite simple. caught the virus. Now I cleaned everything and everything works.
