### ISSUE TITLE
Feature suggestion : Fast Search

### ISSUE THREAD

**Issue by MongMikng** [sailro/EscapeFromTarkov-Trainer#506]
Hello,

Could you please add a fast search feature? For example, it would be great if we could search boxes or corpses instantly.

Thank you.

**Comment by sailro** [comment]
Yep. We already hook all the `examine` thing so all loot is already known, so I think it should be doable.

**Comment by sailro** [comment]
Done, I added "Instant Search" to the `examine` feature. So this one feature will do:
- have all items examined (known).
- instant search, you do not need to click search anymore.

You just need to update the trainer and make sure `examine` is enabled.

**Comment by sailro** [comment]
@MongMikng is it working for you?

**Comment by MongMikng** [comment]
@sailro Everything is perfect! I am using version 3.8.0, and it works well. Thank you.
