### ISSUE TITLE
Feature Suggestion : Add support for local bundle loading

### ISSUE THREAD

**Issue by solareon** [sailro/EscapeFromTarkov-Trainer#507]
It appears there is a number of users who are unable to run the installer due to various SSL issues preventing grabbing the repository bundle for the installer. A useful feature would be to enable a user to download the zip through another means (web browser, other device, etc.) and supply the bundle via an option to the installer. The installer could also support pointing to a local uncompressed copy of the repository as well.

Example providing bundle via zip:
`installer.exe -bundle EscapeFromTarkov-Trainer-master.zip`

Example providing bundle via path:
`installer.exe -bundle c:\EscapeFromTarkov-Trainer\`

**Comment by sailro** [comment]
I fully understand the intention, but in all cases so far we've seen that it's a user-side problem. So with such a feature, they won't try to understand and will put us back in the situation we wanted to avoid with the installer: using obsolete sources and coming to see us because it doesn't compile :)

**Comment by solareon** [comment]
Also a fair assessment. I was thinking about it last night how to best help point folks in the right direction. I think updating the message with the SSL error to be an error and tell the user that they need to examine their internet connection would be a little more descriptive than just throwing a warning since GitHub uses HSTS and it won't connect with SSL issues anyway.

**Comment by sailro** [comment]
Yep fully agree, I had the same thought. I'm going to update the installer with a more actionnable wording.

**Comment by solareon** [comment]
Completed via #508
