### ISSUE TITLE
Installer loads correctly but menu doesn't appear once SPT-AKI is launched. 

### ISSUE THREAD

**Issue by DeathLotus72** [sailro/EscapeFromTarkov-Trainer#509]
I ran the server and launcher once before trying to run the Installer, put in in spt file directory, and it showed as the normal universal download to be correct. Everything was the same but when I tried to load SPT the menu wasn't populating. What is the other file on the downloads that includes many directories and info documents? Need to install to certain places in SPT files?

**Comment by sailro** [comment]
Can you show us your installer output please ?

**Comment by SoojongK** [comment]
> Can you show us your installer output please ?

I have a same problem, Although some features work on command line, I cannot get access to GUI(Alt key does not work).
Installer output is same as your screenshot on instruction

**Comment by SoojongK** [comment]
> > Can you show us your installer output please ?
> 
> I have a same problem, Although some features work on command line, I cannot get access to GUI(Alt key does not work). Installer output is same as your screenshot on instruction

Nevermind, I was using non US keyboard and switching to US(QWERTY) keyboard fixed the problem with Alt key

**Comment by sailro** [comment]
Default key for in-game GUI is `Right-Alt`. So not the `Left-Alt`, it is not the same thing :)

You can try the following:

Use `save` to save your configuration to disk. (you'll see the fullpath to this file).

Open this file and tweak the key:

`EFT.Trainer.Features.Commands.Key="RightAlt"`

For available keys, use https://docs.unity3d.com/ScriptReference/KeyCode.html

**Comment by jstii7** [comment]
for me it says this  C:\Users\tifui\OneDrive\Documents\Escape from Tarkov\trainer.ini not found!

**Comment by sailro** [comment]
Any news?

**Comment by austinjames51** [comment]
I know this is an old thread, but I'm not sure where the installer installs the trainer.ini. I can get the commands to work but the GUI doesn't come up by pressing Right-Alt.
