### ISSUE TITLE
I have installer issues

### ISSUE THREAD

**Issue by Pegenator** [sailro/EscapeFromTarkov-Trainer#517]
I want to install but when i run installer I have this error
![Discord_wTiWIinc0v](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/130087884/17467509-3b73-405e-b0b6-e33720d6fd6e)

**Comment by topirod** [comment]
same problem too

**Comment by solareon** [comment]
The trainer does not work on Live, you need to use SPT. Depending on your configuration you might need to move the installer into the SPT folder and run it from there. @Pegenator @topirod
