### ISSUE TITLE
No NightVision

### ISSUE THREAD

**Issue by Proelgm3** [sailro/EscapeFromTarkov-Trainer#518]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support. 

**Describe the bug**
0.14.1.29197 SPT-AKI 3.8.3 - 01783e. 
if Nightvision on- black screeen. If i have NV device  - all work. without - black. i use universal installer.                               

And on 09.06.2024 - win defender delete instaler.zip

![2024-06-09_13h34_10](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/78214848/f750dec6-ad32-4233-b38d-1c0d9c8fae24)

**Comment by sixiangyu** [comment]
@Proelgm3 
u use AMANDS'S GRAPHICS ???

**Comment by Proelgm3** [comment]
+ yes

сб, 15 июня 2024 г., 6:43 sixiangyu ***@***.***>:

**Comment by Proelgm3** [comment]
Deleted Amanda - it worked. Is there a chance that they can work together?

сб, 15 июн. 2024 г. в 07:17, Stage system ***@***.***>:

**Comment by solareon** [comment]
This is probably due to how Amand's is modifying the night vision shader. We won't be able to support that modification due to how we activate night vision and how Amand's detects the night vision activation and then applies its changes to the shader.
