### ISSUE TITLE
I can't figure out the installation

### ISSUE THREAD

**Issue by sanekkut1** [sailro/EscapeFromTarkov-Trainer#523]
Please help with the installation.When I use the installer, it creates 2 files in different folders and asks me to click the button to close.I log into the game, and I have only WH in it, there is nothing in the console and I cannot register any settings.

**Comment by sailro** [comment]
Could you please show us installer output ?

**Comment by sanekkut1** [comment]
> Could you please show us installer output ?

I'm sorry, I've already fixed everything, now everything works.But the question is, how do I change the loot shown on the map if I can't enter any commands?

**Comment by PurplePeopleEatur** [comment]
could you explain to me how you got it working
