### ISSUE TITLE
Socket's access rights error with Installer

### ISSUE THREAD

**Issue by Auer650** [sailro/EscapeFromTarkov-Trainer#525]
<img width="863" alt="Screenshot 2024-07-02 173951" src="https://github.com/sailro/EscapeFromTarkov-Trainer/assets/174184055/41d93d07-4a32-489c-a581-42e520d15232">

I use windows 11 and have also tried it with firewall and antivirus turned off

**Comment by solareon** [comment]
Two issues here. First you have not given permission to the application to access sockets, this could be a firewall or antivirus on your computer. Second issue is you are running this from the live installation which is not supported and you need to use it with SPT

**Comment by Auer650** [comment]
How do I give permission to the application to access sockets ????

**Comment by solareon** [comment]
You could try running it as administrator?

**Comment by Auer650** [comment]
It's OK if it doesn't work, not so bad but thanks for the quick reply and I've already tried

**Comment by solareon** [comment]
are you using some sort of vpn? maybe try disabling that

**Comment by Auer650** [comment]
I have tried several things including trying on another PC but nothing worked

**Comment by sailro** [comment]
Very first time we are seeing this. Are you hosting some kind of server on those machines ? Perhaps we are hitting some kind of outbound connection limit / dynamic port exhaustion.

What you can try:
- close all unnecessary programs (especially crappy security/antivirus software hooking or monitoring connections)
- update your windows and your network drivers

In the end `0.14.9.30626` is not supported anyway, so if you really want to target this version, it's a waste of time.

Thanks!

**Comment by Auer650** [comment]
I've tried more things, I've also downgraded to EFT 0.14.1.29197, I've tried downloading on other PCs, always the same result, not a big deal, maybe it really is an outbound connection limit / dynamic port exhaustion, well, it's just not meant to be.

**Comment by Auer650** [comment]
I managed to get it to try to download but now I get this message

<img width="868" alt="aa" src="https://github.com/sailro/EscapeFromTarkov-Trainer/assets/174184055/3a79753f-81d6-4c46-b48d-610909a4ce04">

**Comment by Auer650** [comment]
It works
