### ISSUE TITLE
trying to figure out installer 

### ISSUE THREAD

**Issue by PurplePeopleEatur** [sailro/EscapeFromTarkov-Trainer#526]
![image_2024-07-06_005718155](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/124385850/89369bab-c4a8-4ed1-966c-692aee742c30)

i know that's its an older newer version and need help to degrade tarkov if any help is possible thanks

**Comment by solareon** [comment]
Any downgrade would have to be done from SPT. We don't provide any support for that. Per their discord a new release is coming in a few hours but it didn't specify what version they were targeting.
