### ISSUE TITLE
spt-aki 3.9.0

### ISSUE THREAD

**Issue by sailro** [sailro/EscapeFromTarkov-Trainer#527]
I started to update the trainer for 3.9.0, but I miss a patcher-downgrader version:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/2c88a2b0fedcb41c44d8da615c4af49c6a058133

I think that should solve compilation issues but i'm not even able to test.

I have EFT `0.14.9.30985`. I want EFT `0.14.9.30626` to play with spt-aki `3.9.0`, but I'm not able to find the proper patcher-downgrader.

Any link available ?

cc @solareon 

Thanks

**Comment by solareon** [comment]
I believe if you install using the installer https://hub.sp-tarkov.com/files/download/10505/ or https://hub.sp-tarkov.com/files/file/672-spt-installer/#overview it should automatically downgrade? @sailro

**Comment by sailro** [comment]
Indeed. Thanks!

**Comment by sailro** [comment]
I reverted my changes (will be for later).

It is compiling properly for 3.9.0
