### ISSUE TITLE
Compilation failed for master branch.

### ISSUE THREAD

**Issue by GamingDevil31** [sailro/EscapeFromTarkov-Trainer#529]
Need a little help i've tried everything from restarting PC and running as admin. Installer is in SPT folder and EFT is up to date and so is SPT.

Screenshot
![trainer error](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/31113560/4f47c072-72cc-42a0-8c9c-3040035f444c)

Thanks for the help in advance.

**Comment by sailro** [comment]
You are using the trainer on stock EFT. You need to install spt-aki first.

**Comment by GamingDevil31** [comment]
It's SPT but i forgot I needed to run SPT first so it creates the files to compile against it. My bad :/

**Comment by sailro** [comment]
Yep I spotted that our spt-aki detection need to be updated (they changed their data folder). It's now fixed (but we'll need to release an updated installer).

![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/638167/3fb465b2-acb3-4acb-9790-59a6fb33e600)
