### ISSUE TITLE
Hotkey and missing option

### ISSUE THREAD

**Issue by nos4r3** [sailro/EscapeFromTarkov-Trainer#53]
From your Features i don't see some feature in the trainer

and only rightalt key work to bring EFT Trainer menu F1-F12 for other option doesnt work at all have to tick it manually i don't see any console like you use it i want to save option but dunno how

I'm using 1.5.1 SPT-AKI with universal installer

**Comment by sailro** [comment]
You just have to configure your own keys.

Launch the EFT console with tilde-key: "`". Use save to write the current config. Edit this file outside of tarkov. Use load to load the updated config.
