### ISSUE TITLE
Wallhack ESP AI colours not working as intended

### ISSUE THREAD

**Issue by Renkyz** [sailro/EscapeFromTarkov-Trainer#530]
I've just finished setting up SPT 3.9.0 (previously played on 3.8.3) in a brand new game folder. I downloaded the trainer installer from here again to be sure I had the latest version and installed it to my new 3.9.0 SPT install.

Everything seems to work right so far except for the wallhack ESP colours.
Scavs are showing up as yellow, Bosses show up red, but PMC's also show up red. I'm yet to see a Cultist so can't confirm if that colour is working right.

I'll attach a screenshot of my colour settings.
The only thing I could think that might be an issue is I obviously still had a settings file from my older 3.8.3 install, so maybe that has caused issues? I wouldn't have expected it to though.
![Capture](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/33794867/2b5fd4b3-321f-44c0-b1db-2398dd9d4936)

**Comment by solareon** [comment]
This might be due to an update on the SPT-AKI side for what the identification of a PMC vs Scav etc. is

**Comment by Renkyz** [comment]
Yeah that makes sense to me. To be sure, I removed my settings.ini file and had the trainer generate a fresh one. The behaviour remains the same. Hopefully it's fixable. I primarily used the trainer to be able to tell if bosses had spawned as per my settings with other mods and to be able to run around in ghost mode to check AI behaviour. I noticed AI seem to be able to see me now in ghost mode but they don't shoot me until I turn it off lol. But that's not related to this bug report of course. Best of luck if you decide to try fix any of the issues that the new 3.9.0 update has brought with it.

**Comment by AntoniOblomOFF** [comment]
I confirm the issue about a PMC's colors, it's exactly the same thing for me.

**Comment by Seriously111** [comment]
As an aside, this Trainer used to have a GUI interface?? How do I open it? I have been using the console to control......

**Comment by hummelrichard** [comment]
I have also had the problem of PMCs all appearing as bosses.
I set up a local environment and built against my installation of SPT 3.9.3, and noticed that this code snippet, located in the static method `public static HostileType` in PlayerExtensions.cs:
```
if (settings != null)
{
	switch (settings.Role)
	{
		case WildSpawnType.pmcBot:
			return HostileType.ScavRaider;
		case WildSpawnType.sectantWarrior:
			return HostileType.Cultist;
		case WildSpawnType.assault:
			return HostileType.Scav;
		case WildSpawnType.assaultGroup:
			return HostileType.ScavAssault;
		case WildSpawnType.marksman:
			return HostileType.Marksman;
		case WildSpawnType.exUsec:
			return HostileType.RogueUsec;
	}

	if (settings.IsBoss())
		return HostileType.Boss;
}
```

is returning `HostileType.Boss`. I looked through the SPT source for any kind of similar check, and found that `PMCSpawnParamPatch.cs` is also checking a separate method:

```
// is a boss and not a follower and not a PMC
            if (!bot.Profile.Info.Settings.IsBoss() && !CustomAI.AiHelpers.BotIsSptPmc(bot.Profile.Info.Settings.Role, bot))
```

which made me think that maybe I should add an extra check of the settings to see if the role contained 'pmc'. 

I believe (emphasis on **believe**) I fixed issue in the trainer by changing the above code snippet to:

```
bool isPMC = $"{info.Settings.Role}".StartsWith("pmc");

if (settings.IsBoss() & !isPMC)
	return HostileType.Boss;
```

I apologize for my poor C# skills. I'm sure there's a better way but this works for me for now :)

Hope this helps someone.

**Comment by Renkyz** [comment]
If I knew how to test that myself, I would haha.

**Comment by sailro** [comment]
The fix proposed by @hummelrichard should work. As soon as I'm back from vacation I will fix this. Thank you folks.

**Comment by Renkyz** [comment]
Brilliant, enjoy your vacation! :)

**Comment by sailro** [comment]
Should be fixed now (https://github.com/sailro/EscapeFromTarkov-Trainer/commit/4f4546db9585dd2d234d44c1b6110e840c025534)

You just need to re-run the installer to update.
