### ISSUE TITLE
Incorrect operation of Quest. Does not show pointsofinterest

### ISSUE THREAD

**Issue by AlSeeUs** [sailro/EscapeFromTarkov-Trainer#532]
It does not show some places to visit.
For example, quests:
1. Spa tour - 4. Does not show generators at the shore location.
2. Debtor. It does not show the location on the streets of Tarkov.

In previous versions, the same problem was observed with the Pyramid Scheme quest on the streets of Tarkov (find ATMs), but now the places are shown correctly.

![2024-07-18 20-04 _-201 4, -3 7, -115 5_-0 1, 0 3, 0 0, 0 9_14 55 (0)](https://github.com/user-attachments/assets/7f9732fd-79bc-4f99-a541-cd51b0de36d2)
![2024-07-18 20-04 _-201 4, -3 7, -115 5_-0 1, 0 3, 0 0, 0 9_14 52 (0)](https://github.com/user-attachments/assets/f9880535-1e13-43c9-9e77-6337000f2447)
![2024-07-18 20-04 _-282 5, -3 6, -63 2_0 1, 0 8, 0 1, -0 6_14 49 (0)](https://github.com/user-attachments/assets/a6a96fb3-53ad-4b4b-9769-9f8250641ff5)

**Comment by sailro** [comment]
Hey @AlSeeUs, I had a look at this.

It works correctly with SPT-AKI 3.10 (beta) and EFT 0.15.0.32291, so I guess it was an issue with the previous spt-aki setup:

![2024-09-21 09-07 _-162 2, -9 6, -43 3_0 0, 0 9, 0 0, -0 4_12 00 (0)](https://github.com/user-attachments/assets/41828282-97cb-48c5-8f43-d050ef487fe4)

![2024-09-21 09-12 _-128 6, 2 3, 91 7_0 0, 0 9, 0 1, 0 4_12 00 (0)](https://github.com/user-attachments/assets/31a2b0ff-1aa4-47b7-b4a0-2a89dc607047)

Closing.
