### ISSUE TITLE
Tracking List

### ISSUE THREAD

**Issue by ElectricLynx101** [sailro/EscapeFromTarkov-Trainer#534]
I was trying to find a place to ask questions about this before posting here as I know this is more of a platform to report bugs, but I cannot figure out how to use the Track list. I type in the command tracksr into the console but only get error "Invalid argument count "0" for command "Tracksr"

I must be doing something wrong, but I just don't know exactly what.

**Comment by solareon** [comment]
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/503 has a few examples.

**Comment by ElectricLynx101** [comment]
> #503 has a few examples.

Ahhh, I see. I have to add things to a tracklist first, THEN use that command. Got it.
