### ISSUE TITLE
There is a feature missing from the menu

### ISSUE THREAD

**Issue by SnowWolf753** [sailro/EscapeFromTarkov-Trainer#536]
I had it working fine with spt 3.8.0, but with spt 3.8.3 the 'ghost' feature is missing from the menu, and this is so important to me that I'm anxious to know what went wrong
![QQ20240802-024343](https://github.com/user-attachments/assets/46a083a7-6873-4af5-88e9-5856b1b9940b)

**Comment by sailro** [comment]
Any chance you can upgrade to 3.9.0 ? It is working as expected on my side.
