### ISSUE TITLE
Compilation failed for master branch

### ISSUE THREAD

**Issue by TheGerMetal** [sailro/EscapeFromTarkov-Trainer#537]
Compilation failed for master branch thats all i can read than the window closes
sometimes its only Try #0 sometimes it goes up to Try #3

**Comment by sailro** [comment]
What is your exact EFT version ?
What is your exact SPT-AKI version ?

**Comment by TheGerMetal** [comment]
EFT 0.14.9.7.31124

**Comment by sailro** [comment]
That's why, we only support up-to EFT `0.14.9.7.30626` for now (in sync with SPT-AKI)

**Comment by TheGerMetal** [comment]
ah ok :/ Thy for the fast reply :)
