### ISSUE TITLE
Installer Issues

### ISSUE THREAD

**Issue by DatRandoGuy** [sailro/EscapeFromTarkov-Trainer#539]
@
![image_2024-08-10_211303400](https://github.com/user-attachments/assets/9c2bc7d5-0875-431f-b0ca-3330d18673a6)
I am so sorry for bugging about this but when i try to run the installer it only locates the live Tarkov, I've looked through some of the other issues and tried to do the solutions to those including moving it to the same folder that SPT is in and running it as an admin and it just refuses to find SPT, and I'm not very code smart so I cant figure out what code to run into command to make the installer install with SPT. Please help.

**Comment by sailro** [comment]
Did you try:
`installer "path/to/your/eft/install"`

**Comment by DatRandoGuy** [comment]
So in command prompt installer is a code? and then make the path go to spt and finish it off with install?
