### ISSUE TITLE
i know im doing something wrong.

### ISSUE THREAD

**Issue by moneyomm9** [sailro/EscapeFromTarkov-Trainer#54]
hi. first thanks for your help in advance. i think im doing something simple wrong ere. can you help me out? thanks again!
![Screenshot 2021-07-25 034353](https://user-images.githubusercontent.com/87927209/126891692-e7aeda13-0123-4c23-9248-ca2e766c806e.png)

**Comment by sailro** [comment]
This version is too old, it is recommended to use a newer EFT.

Supported versions are here:
https://github.com/sailro/EscapeFromTarkov-Trainer/branches/all

The first supported one is `10.12.9.10532`, yours is `10.12.9.10423`.

**Comment by moneyomm9** [comment]
thank you!
