### ISSUE TITLE
Why don't work? Plz help with problem

### ISSUE THREAD

**Issue by NamNarkolog** [sailro/EscapeFromTarkov-Trainer#540]
![image](https://github.com/user-attachments/assets/8e507e00-3cb8-486c-97f8-09041669f696)
How to fix this problem? Game version: 0.14.9.1.30626 , SPT-AKI - 3.9.5.

**Comment by solareon** [comment]
This is due to any issue with your network connectivity. Try another network or a vpn or different dns servers but it's nothing to do with the trainer installer.
