### ISSUE TITLE
How do I customize my localization translations?

### ISSUE THREAD

**Issue by clevebitr** [sailro/EscapeFromTarkov-Trainer#541]
I've never touched the C# language,How do I customize a localized translation under a file like [Properties/Strings.resx](https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Properties/Strings.resx) and run it in my game?

**Comment by sailro** [comment]
No need to use C# in this case. We made the work to extract all strings to those resource files.

`Strings.resx` contains the default language (en-us), and as an exemple you have `String.fr.resx` for French.

If you just want to quickly customize for your own usage only, the easiest is to directly update `Strings.resx` with a resource editor (like the one provided with Visual Studio).

In the end, you'll need to recompile the bits with Visual Studio.

---

You can also clone `Strings.resx` for your own language let's say Chinese simplified so `Strings.zh-cn.resx` and send us a PR.

This way other users will be able to use this Chinese translation when installing the Trainer using the following command:

`.\Installer -l zh-cn` like we do for the current French version using `.\Installer -l fr`

**Comment by sailro** [comment]
I will add more information about localization support in the main README for awareness.

**Comment by clevebitr** [comment]
I don't find the `Properties` folder in the project directory and there are a lot of reference errors in Visual Studio, how do I handle it correctly?
![image](https://github.com/user-attachments/assets/90936f60-5034-4a29-9b91-b707d2249154)

**Comment by clevebitr** [comment]
Ok, I'm impressed by my stupidity, I found the Properties folder, but I still can't handle the references to `UnityEngine. InputLegacyModule`, `BepinEx`, which one should I compile?

**Comment by clevebitr** [comment]
I tried to create Strings.zh-cn.resx under the Properties folder. Will this enable other users to use Chinese translation during installation？[Strings.zh-cn.resx](https://github.com/clevebitr/EscapeFromTarkov-Trainer/blob/master/Properties/Strings.zh-cn.resx)

**Comment by clevebitr** [comment]
I don't quite understand how to compile this project, could you explain in detail what I have to do?

**Comment by clevebitr** [comment]
Good news, I managed to compile the modified version, but the translation was only achieved by replacing Strings.resx. I am trying to figure out how to change the localization language support through the installer

**Comment by sailro** [comment]
Just create a PR using your fork. Once validated/merged, you'll be able to use the [Universal Installer](https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-3.0) with the following command `.\Installer -l zh-cn`

**Comment by clevebitr** [comment]
I've submitted a pull request, you can see if it's time right

**Comment by sailro** [comment]
All good. It seems to work ! 

![2024-08-18 10-22  (0)](https://github.com/user-attachments/assets/bbf38b97-ba03-46e3-b5e1-08f6edf456ab)

**Comment by clevebitr** [comment]
Thanks for the guidance! Now all users can use localized Chinese translation!

**Comment by sy748139807** [comment]
你好，我现在已经通过轻松安装好了，但是进去游戏加载的是英文，我不知道该怎么去汉化?我对c语言并不了解，麻烦您能讲解一下吗
![Uploading 475f0cbae61ff02cff7495b1c3e1f84.png…]()

**Comment by clevebitr** [comment]
很简单，把安装程序复制到游戏根目录，它会自动检测到游戏，在资源管理器地址栏中输入cmd打开控制台，输入"./安装程序的文件名字 -l zh-cn"来安装程序，如果你之前安装过，不必担心，它会覆盖安装，但是，在安装程序之前，请至少运行过一次游戏

**Comment by zwqute** [comment]
难以置信 现在有中文了  爱你~

**Comment by Yae233** [comment]
我在0.14.9.30626这个版本上使用不了中文翻译了提示Unable to compile trainer for version 0.14.9.30626.是不支持这个版本了吗？

**Comment by solareon** [comment]
> 我在0.14.9.30626这个版本上使用不了中文翻译了提示Unable to compile trainer for version 0.14.9.30626.是不支持这个版本了吗？

`zh-cn` is not supported for this build. you will need to use a newer SPT build for localization.

**Comment by Yae233** [comment]
thank you
