### ISSUE TITLE
Why it starts to fail since compiling the master branch

### ISSUE THREAD

**Issue by KaguraWang** [sailro/EscapeFromTarkov-Trainer#542]
<img width="856" alt="image" src="https://github.com/user-attachments/assets/b3dc412b-ee43-4250-9741-451a000873dd">

**Comment by sailro** [comment]
Do not use it with the live EFT. Use it with EFT + sptaki. master branch can build against EFT 0.14.9.30626 (spt-aki 3.9.5)
