### ISSUE TITLE
Installer crashes on startup, Powershell Error

### ISSUE THREAD

**Issue by Jasontyler221** [sailro/EscapeFromTarkov-Trainer#55]
Hey there, i'm using AKI 1.5.1 with the client downloaded off the EmuTarkov Related Community Discord.

The installer crashes on startup, i saw someone with another issue use powershell, which gives me the error in the image attached.

![image](https://user-images.githubusercontent.com/87929205/126893591-a97b3a96-05bd-4148-8f64-5fcf530268b1.png)

**Comment by sailro** [comment]
It does not seem related to the installer at all. It is a powershell issue, you probably need to quote the path you are passing as parameter. You can try to use a command line prompt instead of a powershell console.
