### ISSUE TITLE
how can i update the trainer automatically or manually

### ISSUE THREAD

**Issue by ERxsz** [sailro/EscapeFromTarkov-Trainer#550]
I just update the game to version 0.14.9.31124, so how can i update the trainer, do i just need to wait for the update, or i dont mind doing it manually i just dont know how,, i have time to learn but not the knowledge
![image](https://github.com/user-attachments/assets/4415e803-77a2-4cf1-b175-f29a92cfe803)

**Comment by clevebitr** [comment]
Simply overwrite the installation;run the installer again

**Comment by ERxsz** [comment]
> Just overlay the installation; Run the installer again Currently supported to client version 0.14.9.30626

whoop it works, thanks
![image](https://github.com/user-attachments/assets/d82f6c64-70f0-415e-8102-e260f7f2cf72)
