### ISSUE TITLE
EFT 0.15.0.32160

### ISSUE THREAD

**Issue by gen8l** [sailro/EscapeFromTarkov-Trainer#553]
![Screenshot 2024-08-27 203111](https://github.com/user-attachments/assets/cd97a8a8-cad6-4842-8b66-a7470f5950ca)
Hi, first of all, thank you for your hard work in creating this trainer. I tried running the installer with my current version (0.15.0.32160) and encountered the error you can see in the attached screenshot. I have already checked the currently supported releases, and I was wondering if you have any plans to update the trainer for version 0.15.0.XXXXX in the near future?
Thank you very much in advance for your response.

**Comment by sailro** [comment]
Hello,

We will update when spt-aki is ready to support this upcoming version.

Thanks!
