### ISSUE TITLE
EFT 0.14.9.30626 - trainer not compiling

### ISSUE THREAD

**Issue by Amiralijalalvand** [sailro/EscapeFromTarkov-Trainer#554]
![Screenshot 2024-09-01 101141](https://github.com/user-attachments/assets/bf2b0c7d-9c83-4441-98cd-6050fed292b6)

Hi i using  EscapeFromTarkov (0.14.9.30626) SPT but its not gonna be install help me please

**Comment by solareon** [comment]
@Amiralijalalvand did you run spt one time first to patch the files?

**Comment by xSMDx** [comment]
well its your internet try using a Vpn

**Comment by xSMDx** [comment]
i have a similar problem but mine doesn't have the first 4 lines
![image_2024-09-01_201353370](https://github.com/user-attachments/assets/e86ed4bd-640f-41d3-9a23-f5af8e4e292c)

**Comment by solareon** [comment]
@xSMDx I don't believe SPT has released a version for that build yet. The trainer only works with SPT now so you can't use it on live

**Comment by xSMDx** [comment]
it did release the current version is v0.15.0.3.32280

**Comment by solareon** [comment]
> it did release the current version is v0.15.0.3.32280 on SPT version 3.10.0

As a bleeding edge release. Once it is final we will work on addressing the issues related to it.

**Comment by sailro** [comment]
Where do you get those beta releases ?

**Comment by solareon** [comment]
> Where do you get those beta releases ?

https://discord.com/channels/875684761291599922/875758493351694396/1279506872919130172 and then select the Bleeding Edge role at the bottom then they are in a pinned comment in the locked channel @sailro

**Comment by sailro** [comment]
> it did release the current version is v0.15.0.3.32280 on SPT version 3.10.0

You can try to re-run the installer. I added a specific branch for working on the bump.

**Comment by xSMDx** [comment]
Alr thanks

**Comment by xSMDx** [comment]
> > it did release the current version is v0.15.0.3.32280 on SPT version 3.10.0
> 
> @xSMDx You can try to re-run the installer. I added a specific branch for working on the bump. (but everything is not working for now).
> 
> ![image](https://private-user-images.githubusercontent.com/638167/364456940-45bb981a-d483-4d68-997d-dce92bd61f2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NjY2MTcsIm5iZiI6MTcyNTQ2NjMxNywicGF0aCI6Ii82MzgxNjcvMzY0NDU2OTQwLTQ1YmI5ODFhLWQ0ODMtNGQ2OC05OTdkLWRjZTkyYmQ2MWYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxNjExNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTE1YTczZjgwYTEyN2YxMTE4YmM5YTliYmZlNGE3NWQ0MjM1YTJlNjczYzA1NTRjNThkOGU5Zjc3MjI2Mzk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sqNjbEa_Qoth_z1qUUPDkUEV-AM51NbTf7wf0wW984g)
