### ISSUE TITLE
How spawn bossBoar?

### ISSUE THREAD

**Issue by AlSeeUs** [sailro/EscapeFromTarkov-Trainer#555]
Error - Found 2 bots, be more specific

not help:
spawnbot bossboar
spawnbot "bossboar"
spawnbot bossboar;

![image](https://github.com/user-attachments/assets/d9f828d3-4c75-4241-96dc-9af20bbb2c94)

**Comment by solareon** [comment]
did you try with it like `spawnbot bossBoar` ?

**Comment by AlSeeUs** [comment]
Yes, not work

![image](https://github.com/user-attachments/assets/0aa0377d-c1e5-41ca-baec-c9b5e488be63)

**Comment by solareon** [comment]
Looking at this more closely there isn't a match case if it's exact. Specifically this section of code https://github.com/sailro/EscapeFromTarkov-Trainer/blob/1c87004740dbd6366d7462cae3f21017b2ffb706/ConsoleCommands/SpawnBot.cs#L46-L60 doesn't cover an edge case like that.

**Comment by sailro** [comment]
Thanks! @solareon fixed it.

We are now doing an exact search first, then a partial search.

So 

`spawnbot bossBoar` => will spawn the boss.
`spawnbot bossBoarS` => will spawn the sniper.
`spawnbot bossBoa` => will show the _be more specific_ warning.
