### ISSUE TITLE
HealthPatch Active when disabled.

### ISSUE THREAD

**Issue by mbradley672** [sailro/EscapeFromTarkov-Trainer#559]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support. 
Using SPT-3.9.8

**Describe the bug**
Bullets still cannot hurt me even when the health feature is disabled.

**To Reproduce**
Steps to reproduce the behavior: Launch game verify setting is off.

**Expected behavior**
With health disabled I should be able to be injured.

**Comment by sailro** [comment]
Ah I'm going to have a look

**Comment by mbradley672** [comment]
Ah, that would make sense.
Maybe I could add a check that would nullify the effects to bullets somehow?

**Comment by mbradley672** [comment]
I did just verify that that is the issue.
What I will do is see if I can add an option to include/exclude bullets.
