### ISSUE TITLE
Unable to compile trainer for version 0.15.0.32280.

### ISSUE THREAD

**Issue by RAMDAC1** [sailro/EscapeFromTarkov-Trainer#564]
Continue with EscapeFromTarkov (0.15.0.32280) in C:\Users\USER\Desktop\Escape.From.Tarkov.v0.15.0.3.32280-P2P\Escape
from Tarkov ? [y/n] (y): y
Target EscapeFromTarkov (0.15.0.32280) in C:\Users\USER\Desktop\Escape.From.Tarkov.v0.15.0.3.32280-P2P\Escape from
Tarkov.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.15.0.32280 not found.
Unable to compile trainer for version 0.15.0.32280. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

i tried to install it on the lates spt aki and tarkov version, sadly i got the error, i saw in BRANCHES some acctivity in newer version.

**Comment by sailro** [comment]
This version doesn't seem to be legit. Buy the game :)
