### ISSUE TITLE
Installer no recognizing paths and Fails compilation

### ISSUE THREAD

**Issue by madmanbeavisx** [sailro/EscapeFromTarkov-Trainer#565]
**Describe the bug**
- Installer does not pickup all instances of Tarkov
- Installer is failing compile.

**To Reproduce**
- Run installer
- Try to install.

**Expected behavior**
- When executing installer It should find all instances of EFT
- When installing it should be able to compile.

**Screenshots**
![image](https://github.com/user-attachments/assets/43701ac2-ce77-4371-8586-5cdac3d796b5)

**Additional context**

**Comment by sailro** [comment]
> When executing installer It should find all instances of EFT

Unfortunately we cannot do that without file-searching the whole disk. So for now:
- We auto-scan the EFT live installation (given we have a registry key to look).
- We auto-scan all directories along with the EFT live installation (like `C:\Battlestate Games\*`).
- We auto-scan SPT-AKI default (`C:\SPT`).
- We auto-scan the directory from where the installer was run.

> Installer is failing compile.

Are you really sure you run the game once from your `E:\A-SPTFiles\Personal_938` installation before running the installer ?
On my side with the exact same version:

![image](https://github.com/user-attachments/assets/d6804e45-12b3-4578-8930-140fd5947124)

**Comment by sailro** [comment]
We could use the MUICache to find instances of `SPT.Server.exe` or `SPT.Launcher.exe` in the registry:
https://www.nirsoft.net/utils/muicache_view.html

**Comment by sailro** [comment]
@madmanbeavisx could you try the following debug installer to see it it's able to detect your spt-aki install?
https://github.com/sailro/EscapeFromTarkov-Trainer/actions/runs/10897879394/artifacts/1941158311

**Comment by SmoulderingSkies** [comment]
I am using the assembly from the site https://thelastgame.org/281-escape-from-tarkov.html

I encountered exactly the same problem, all the files are present, SPT-AKI-Editor works and finds everything, but this trainer cannot install with such errors, what should I do?
![image](https://github.com/user-attachments/assets/f99422cb-5a00-46e3-befe-ba1b5596bf54)

**Comment by solareon** [comment]
@SmoulderingSkies buy a legal copy of the game and don't support dodgy websites.

**Comment by madmanbeavisx** [comment]
> Are you really sure you run the game once from your `E:\A-SPTFiles\Personal_938` installation before running the installer ? On my side with the exact same version:


I did a reinstall of spt and it fixed the issue. Wierd. 

I will run the new installer after work.
