### ISSUE TITLE
Settings randomly re-enable themselves

### ISSUE THREAD

**Issue by paulsnoops** [sailro/EscapeFromTarkov-Trainer#567]
Occasionally, some settings will re-enable themselves when previously disabled. I think this happens when entering a raid and it's seemingly random which settings get enabled. The only way around it seems to be to load settings (assuming you've already saved) to revert back to the settings you want enabled.

SPTarkov version: 3.9.8 (but happened for me on previous versions too)

**Comment by sailro** [comment]
Just to be sure we are on the same page:
- all changes will not be saved (between executable runs) unless you use save.
- all settings are loaded once when you initially run the game (or when you use load).
- If you change something while in raid, you should keep this setting for the next raid.

Could you give a reproducible example? Perhaps we have a conflict or an issue somewhere for a specific setting ?

**Comment by paulsnoops** [comment]
Closing this, there's no problem with the trainer. Let's just say it was user error hahaha
