### ISSUE TITLE
Chrome is blocking the installer download

### ISSUE THREAD

**Issue by MRS88** [sailro/EscapeFromTarkov-Trainer#568]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support. 

**Describe the bug**
Can't download in Chrome because of virus in latest Installer.zip. Meanwhile there is no problem in Firefox

**Comment by solareon** [comment]
Can you show us the error/warning you are receiving. I just downloaded the installer zip from the releases page on chrome without any issues.

**Comment by xlisovGH** [comment]
No problems

**Comment by sailro** [comment]
Here is the virustotal report for the installer:
https://www.virustotal.com/gui/url/5c0190bcce034300e247c32fb3c1f50ef62ddb9c5dd0eb01c66bd732f490416d

As you can see, all is green.

I already spotted that sometimes, Chrome is temporarily blocking us on a fresh release,  but it settles itself in the next few days
