### ISSUE TITLE
virus in the installer.exe

### ISSUE THREAD

**Issue by BonelabDEV** [sailro/EscapeFromTarkov-Trainer#569]
Describe the bug:
A virus inside the installer.exe file.

To Reproduce:
throw the installer.exe inside virustotal

Expected behaviour:
I was just double checking like I do with everything else I download and noticed this.

Screenshots:
![image](https://github.com/user-attachments/assets/b468ac94-ba5f-4444-b422-bdd71dde1f99)

Additional context:
I'm assuming its a false positive but just throwing this out there.

**Comment by sailro** [comment]
See #568

**Comment by sailro** [comment]
Strangely we see false positives when directly scanning the exe file, but all is green when scanning the zip.
