### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Djassie18698** [sailro/EscapeFromTarkov-Trainer#57]
I used the installer and everything went according to the pictures, but when I load into the game and press right alt nothing pops up sadly. Do you know why? Appreciate it!

EDIT: I'm on SPTarkov so im not doing this on live, i have run the game before trying this. It's on 12893

**Comment by Djassie18698** [comment]
It's on 12893 btw

**Comment by Djassie18698** [comment]
![image](https://user-images.githubusercontent.com/51295582/129989284-c7ef2b18-914c-4191-8d36-4a285bcee434.png)

**Comment by Djassie18698** [comment]
I have no idea if you still check this but thought it was worth trying

**Comment by Djassie18698** [comment]
![image](https://user-images.githubusercontent.com/51295582/129991574-d3591e0f-13c5-4631-9c75-fd0da59384be.png)

**Comment by sailro** [comment]
What do you see in `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt` ?

**Comment by Djassie18698** [comment]
[output_log.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7013604/output_log.txt)
I've uploaded the outpout log

**Comment by Djassie18698** [comment]
After trying some more times, I woke up and deleted everything, reinstalled the game and the server and now everything works! Sorry for not trying this before! Thanks for all your work in this, it's amazing!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sailro** [comment]
Great!
