### ISSUE TITLE
Unable to compile trainer for version 0.15.2.32757

### ISSUE THREAD

**Issue by Daniii420** [sailro/EscapeFromTarkov-Trainer#575]
Continue with EscapeFromTarkov (0.15.2.32757) in H:\Programme\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.15.2.32757) in H:\Programme\EFT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.15.2.32757 not found.
Unable to compile trainer for version 0.15.2.32757. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by sailro** [comment]
We should be good now:

![image](https://github.com/user-attachments/assets/46d41a6c-0c1b-4c08-a53c-2011e64b9b5b)
