### ISSUE TITLE
Options not saving

### ISSUE THREAD

**Issue by Hoeggi1** [sailro/EscapeFromTarkov-Trainer#583]
Every time I launch the game, I have to reassign all keybinds and adjust the settings.
Eventhough I always "save settings", it never saves them.

Is this already a known bug?

**Comment by sailro** [comment]
No, never hit this issue before. No error message in the console when you save ?

I guess this is a permissions issue to access `<your documents>\Escape from Tarkov\trainer.ini`

**Comment by Hoeggi1** [comment]
You are a genius. You fixed my monthlong issue!
THANK YOU !!
