### ISSUE TITLE
trainer Install issue.

### ISSUE THREAD

**Issue by POKY1230** [sailro/EscapeFromTarkov-Trainer#586]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support. 

**Describe the bug**
Unable to compile trainer for version 0.15.2.32757.

**To Reproduce**
launch the installer.
**Expected behavior**
activite the trainer.
**Screenshots**
![名称未設定 1](https://github.com/user-attachments/assets/e83d7169-c50c-460a-95c4-18fcd634e537)

**Additional context**
is there have any more detailed for the trainer install.
maybe some step description will help.

**Comment by sailro** [comment]
spt-aki is not installed in your case.

See my screen:
![image](https://github.com/user-attachments/assets/52a298e1-3a86-4abb-9de0-ca9196960d9b)

**Comment by POKY1230** [comment]
i finished spt install,
but it still can't activte.
is there need to place the trainer file in to the tarkov game file.
![名称未設定 2](https://github.com/user-attachments/assets/44222f71-6c29-44b1-9cc6-6be03b73b314)

**Comment by sailro** [comment]
As you can read in the console:

> Warning: it seems that you have never run your SPT-AKI installation. You should quit now and rerun this installer once it's done.

So what about starting the game once ? :)

**Comment by POKY1230** [comment]
still the same.

**Comment by POKY1230** [comment]
spt file version and current tarkov version aren't the same.
is that the problem?

**Comment by POKY1230** [comment]
Will i figure it out.
Turns out i totaly forgot do the spt ruuning step.
Thank for the support.
By the way how am i going to active trainer.
Do i gonna download the master file or just type trainer name in console.
