### ISSUE TITLE
Change character charms color

### ISSUE THREAD

**Issue by allenji02** [sailro/EscapeFromTarkov-Trainer#592]
Hello,

I was wondering if it might be possible to modify the color of the character charms, perhaps to a more noticeable blue? This is because I find it a bit difficult to distinguish red from the environment colors LOL.

I would really appreciate this feature as it could help me spot targets more quickly without resorting to X-ray or box ESP, which can make the screen quite cluttered.

Thank you so much for your contribution!

**Comment by sailro** [comment]
You can change all the colors using the in-game menu, `Players` tab:

![2024-11-09 17-49  (0)](https://github.com/user-attachments/assets/6bcdf1e7-42a5-4e21-b51e-18a3ef04bf4e)
