### ISSUE TITLE
Spawn multiple items

### ISSUE THREAD

**Issue by zzm1997** [sailro/EscapeFromTarkov-Trainer#599]
hello  I want to know spawn ammo Problem   Only one can be produced at a time

**Comment by sailro** [comment]
And instead of spawning one bullet, why not spawning an ammo pack ?

**Comment by zzm1997** [comment]
but  i spawn ammo pack   There's no ammo in there.  if spawn 5.56 sp

**Comment by sailro** [comment]
I see, I'm going to have a look.

**Comment by sailro** [comment]
I update the code see https://github.com/sailro/EscapeFromTarkov-Trainer/commit/352f4eaded9d30dff8446239b8731f3b3d2c284b

Now when you spawn magazines or ammo packs, they will be automatically filled with compatible ammunition.

This will only work with the upcoming SPT-AKI 3.10 (I did not backport to the current stable 3.8 given we made a lot of changes regarding the spawn logic).
