### ISSUE TITLE
Is there an easier trainer then this one?

### ISSUE THREAD

**Issue by neil501** [sailro/EscapeFromTarkov-Trainer#6]
This trainer don't work! I'm not a computer tech i have no idea how to compile data or do a mono injection this trainer seems to be ONLY for computer programmers or computer techs. Did you make a trainer that players can download, install, and then run the trainer? Sadly this current one is way too difficult for me to use :(

**Comment by sailro** [comment]
You can find installation instructions, and compiled bits in the release section. Of course you have to use the exact EFT version matching the release. Else you'll have to compile yourself the trainer.
