### ISSUE TITLE
installer crashing

### ISSUE THREAD

**Issue by teletabis200** [sailro/EscapeFromTarkov-Trainer#60]
Hello i wanted to test this out so i downloaded the installer and when i open it it just closes after a second

**Comment by sailro** [comment]
Run it from a command prompt, so you can see at least the message.

I guess th installer was unable to find your EFT installation, so you need to run:
`installer "path/to/your/EFT/installation"`

Everything is already documented when downloading the installer. Please read before running executables without context.
