### ISSUE TITLE
Player-ESP not disabling

### ISSUE THREAD

**Issue by plxzy255** [sailro/EscapeFromTarkov-Trainer#61]
Turning off the Player-ESP isn't doing anything in SPTarkov. I'm trying to make a UpdateWhenDisabled() function in the Players.cs class. Anyways nice code!

**Comment by sailro** [comment]
It will work on next raid.

That's because we altered shaders for all players. If we want to handle this scenario, we have to restore original shaders when disabling.

**Comment by sailro** [comment]
Dupe of https://github.com/sailro/EscapeFromTarkov-Trainer/issues/40
