### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by CPSEnte** [sailro/EscapeFromTarkov-Trainer#610]
**Describe the bug**
double click on installer to open, cmd opens for a second and closes right after and installer gets deleted

**To Reproduce**
open installer 

**Expected behavior**
cmd should open and i should be able to choose where to install trainer

**Comment by sailro** [comment]
> and installer gets deleted

We do not do this. Are you sure you downloaded the installer from this exact site ?

Try to run a command prompt first (cmd), the run the installer from it so we can see if we can spot messages/errors.

Thanks
