### ISSUE TITLE
Console command "SpawnItem" is Gone in 33420

### ISSUE THREAD

**Issue by StreIitzia** [sailro/EscapeFromTarkov-Trainer#611]

**Comment by sailro** [comment]
Make sure:

- you are using the final SPT-AKI v3.10 (not preview/be-testing ones)
- you are using  an up-to-date version of the trainer (re-use the installer if needed)

Indeed they changed something regarding iteam creation during the 3.10 testing phase and I had to update my code.

I just tested with a fresh EFT 33420, SPT-AKI 3.10 and latest trainer and it's working as expected.

**Comment by StreIitzia** [comment]
I found it, Thanks a lot!
