### ISSUE TITLE
Is it possible to show enemy only when they are within my view(not wallhack)?

### ISSUE THREAD

**Issue by NextNepper** [sailro/EscapeFromTarkov-Trainer#613]
I just want to be able to better distinguish enemies from environment, I am not asking for wall hack. Things like grass block my view but bots can see through them. I just want equality, that's all. Is this currently possible with this trainer?

**Comment by sailro** [comment]
Yes that's possible, open the menu, `Players` tab and disable `XRayVision`. You can also tweak border color.

With `XRayVision`
![image](https://github.com/user-attachments/assets/8c15eb25-86fc-4129-a366-60c6a8971075)

Without:
![image](https://github.com/user-attachments/assets/ec8de97a-fed7-45d1-a986-045687f9b957)

**Comment by NextNepper** [comment]
I don't see a "Players" tab. There is a wallhack option though, do you mean that? Or am I looking at wrong menu? I've pressed right alt(alt gr on my keyboard) to open the menu.

**Comment by sailro** [comment]
Yes, that's because you are on an older version, like with spt-aki 3.9. We renamed this tab

**Comment by NextNepper** [comment]
Yes, I am using an older version due to mod compatibility. By the way I've got it working, thanks!
