### ISSUE TITLE
Unable to compile trainer for version 0.14.9.30626. 

### ISSUE THREAD

**Issue by MY-Git-Li** [sailro/EscapeFromTarkov-Trainer#614]
How to solve this problem?

I use [Universal Installer 3.2](https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-3.2)
command：
.\Installer.exe -l zh-cn
result：
.\Installer.exe -l zh-cn
-=[ EscapeFromTarkov-Trainer Universal Installer - https://github.com/sailro ]=-

Continue with EscapeFromTarkov (0.14.9.30626) in E:\Games\kafefu398\EFT ? [y/n] (y): y
Target EscapeFromTarkov (0.14.9.30626) in E:\Games\kafefu398\EFT.
[SPT-AKI] detected. Please make sure you have run the game at least once before installing the trainer.
SPT-AKI is patching binaries during the first run, and we need to compile against those patched binaries.
If you install this trainer on stock binaries, we'll be unable to compile or the game will freeze at the startup screen.
Continue installation (yes I have run the game at least once) ? [y/n] (y): y
>> Try #0 Compilation failed for master branch.
Warning: no localization support for language 'zh-cn'.
Unable to compile trainer for version 0.14.9.30626. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by solareon** [comment]
This is correct because there was no zh-cn localization for 0.14.9.30626 as seen https://github.com/sailro/EscapeFromTarkov-Trainer/tree/dev-0.14.9.30626/Properties. You will need to update to a newer version for the zh-cn localization
