### ISSUE TITLE
[Feature] Wallshoot - additionally remove damage penalties

### ISSUE THREAD

**Issue by tinshark-seafker** [sailro/EscapeFromTarkov-Trainer#619]
Wallshoot indeed makes player's bullets pass through material, but there's a damage penalty applied when the bullet passes through armor/armor plates. It seems that the reduction happens at EFT.Player.ProceedDamageThroughArmor.

I was able to effectively remove the penalty but only for everyone. I've come short at trying to reference to the player-shooter for making this bypass exclusive to player.

**Comment by sailro** [comment]
I see. The method signature is:

```csharp
public List<ArmorComponent> ProceedDamageThroughArmor(ref DamageInfoStruct damageInfo, EBodyPartColliderType colliderType, EArmorPlateCollider armorPlateCollider, bool damageInfoIsLocal = true)
```

So you can easily use the `damageInfo` to detect if it's related to the player or not.

We do that already here:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Features/Aimbot.cs#L83

Feel free to share your diff or a PR, I will have a look.

**Comment by tinshark-seafker** [comment]
I achieved the wanted effect, by directly modifying "EFT.InventoryLogic" -> ArmorComponent.ApplyDamage method as I couldn't get the "ProceedDamage" method or its Player class to compile without errors, even unedited. Anyway what I did was, I saved the damageInfo.damage attribute at the start of the method and restored the value at the end of the method, putting the restoration inside the if clause you provided.
