### ISSUE TITLE
Installer not working for 12.10.12646

### ISSUE THREAD

**Issue by ELMonke-d** [sailro/EscapeFromTarkov-Trainer#62]
After i press y to install the installer just closes and nothing happens. I have ran the game before too

**Comment by sailro** [comment]
Run the installer from a command prompt, instead of running it directly. So if there is an error message, you can see it.

**Comment by ELMonke-d** [comment]
> 
> 
> Run the installer from a command prompt, instead of running it directly. So if there is an error message, you can see it.

How do i run the installer using cmd?

**Comment by ELMonke-d** [comment]
I found how to run programs thru cmd but it doesnt work for the installer for me. I reinstalled but it still doesn't work. When i try to run it i get an error that says that the program can't be found

**Comment by ELMonke-d** [comment]
I'm gonne reinstall my game now, maybe that'll fix it

**Comment by sailro** [comment]
Perhaps try to upgrade your EFT ? I'm using the installer like everyday...

Give us something like a screenshot, we cannot solve an issue if we don't have inputs.

Thanks!
