### ISSUE TITLE
The trainer is not being installed

### ISSUE THREAD

**Issue by LIGHTY111** [sailro/EscapeFromTarkov-Trainer#624]
Good afternoon! The trainer is unable to complete the installation, and nothing is working. I am attaching a screenshot
![Безымянный](https://github.com/user-attachments/assets/768d5a2e-79b7-47d5-ac51-44991e76155b)

**Comment by solareon** [comment]
Two issues here. One this is an unsupported version. We currently only support up to SPT AKI 3.10.3. It appears you are attempting to install on live which is not going to work. Second you appear to have some dns/vpn filter that is preventing the installer from contacting GitHub.

**Comment by LIGHTY111** [comment]
I use the SPT AKI 3.10.3 server. I checked the network settings - no encryption, DNS and other things, I do not use a VPN

**Comment by sailro** [comment]
I updated our readme, indeed we effectively support `EFT 0.15.5.33420` through SPT-AKI v3.10.x.

But in your case and as displayed in the console, something is redirecting traffic either from your computer or ISP. So we cannot even download source code to compile the trainer.
