### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Batc3r** [sailro/EscapeFromTarkov-Trainer#627]
**Please do not submit bugs for unsupported EFT or unstable SPT-AKI versions**
Double check the [main page](https://github.com/sailro/EscapeFromTarkov-Trainer) for the latest EFT and SPT-AKI versions we support. 

**Describe the bug**
Trying to disable faulting feature/command: Aimbot, Ammunition, Examine, Feature, Ghost, Health, Hits,
LootableContainers, NoSway, Quests, QuickThrow, Spawn, SpawnQuestItems, TemplateHelper.
>> Try #2 Compilation failed for master branch.
Unable to compile trainer for version 0.15.5.33420. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**To Reproduce**
Steps to reproduce the behavior: I just wanna install trainer

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/408993fe-271a-4355-9cd8-137fd89af4c7)

**Additional context**

**Comment by solareon** [comment]
@Batc3r you didn't not run SPT at least once as the installer didn't detect the correct files for modification

**Comment by Batc3r** [comment]
Thank You!
