### ISSUE TITLE
1.2 Installer Not Working 

### ISSUE THREAD

**Issue by MewnianSquire** [sailro/EscapeFromTarkov-Trainer#63]
I've read previous threads about this issue but it's not working for me.
I tried launching it directly and trough command prompt(admin mode too), it just opens then closes quickly, the only thing i can see was a blue line of text but too fast to read. In the cmd there's no error messages either

I hope there's a solution to this

PS I also tried installing .NET Framework 4.7.1 but the .NET installer said it was already installed

**Comment by sailro** [comment]
Did you read the documentation?

Try to run the installer in a command prompt, to see if you can spot an error message.

**Comment by MewnianSquire** [comment]
UPDATE
I managed to get it running but I don't have a correct version of EFT unfortunately and now still trying to find a newer version
