### ISSUE TITLE
Installer not working on 0.12.10.12893

### ISSUE THREAD

**Issue by ELMonke-d** [sailro/EscapeFromTarkov-Trainer#65]
When i run the installer it immediately closes after i type y and then hit enter. No error message. When i try to run it through windows powershell it also doesn't give me an error message. I am not playing on a cracked version btw. I will also attach a video. What i show in the video happens every time. Antivirus and firewall are turned off

https://user-images.githubusercontent.com/85455444/132368895-29e2016c-acce-49ce-96d6-555860be800c.mp4

**Comment by sailro** [comment]
why do you run `powershell` and why do you even use `start`, this will do the same thing as double clicking on the exe ?

Run a simple command prompt: 

Windows button+R / type `cmd` / Enter

Then

`cd "path/where/is/the/installer"`

`installer`

or `installer "path/to/your/eft/installation"`

**Comment by ELMonke-d** [comment]
When i type in installer / installer E:\SPTarkov, it tells me that installer is an invalid command

**Comment by sailro** [comment]
Yes given you propably downloaded the file in your download directory, not in the current folder or your EFT folder...

**Comment by ELMonke-d** [comment]
I don't understand. I extracted the .rar and tried the path of that file too. Still gives me the same error

**Comment by sailro** [comment]
There is no rar file on this site

**Comment by ELMonke-d** [comment]
When i click ''Universal installer 1.2'' in the releases tab on github, it brings me to the installer's page showing how to use it. I then scroll down to the assets tab and click ''universal installer 1.2'' it downloads a rar with the installer inside

**Comment by sailro** [comment]
It's a zip file. I'm sorry but this is probably not for you. Given it's a console application, you need at least to know the basics of what is a file/directory and how to use a command prompt.

**Comment by ELMonke-d** [comment]
Well can you tell me how i run it? Or is it too complicated for me

**Comment by sailro** [comment]
I didn't mean to offend you. I already gave you all the required info, and everything is already documented in the release page. It is simple as hell to use this stuff.

**Comment by ELMonke-d** [comment]
Nah you didn't offend me. Sry if it sounded like that. Ima try reading thru the page again

**Comment by ELMonke-d** [comment]
Alr so how di i run the installer thru cmd? I searched online and they all just tell me to do it how you did. But if that's not the right way, how do i do it?

**Comment by ELMonke-d** [comment]
I also read the manual installation but i don't get what files i have to copy to my game directory

**Comment by ELMonke-d** [comment]
nvm, i finally found a vid the showed me how to run it. sry for wasting your time. You can mark this as closed now

**Comment by sailro** [comment]
Glad you were able to install it.

Could you share the video?
