### ISSUE TITLE
Installed problem~！

### ISSUE THREAD

**Issue by Nemesir** [sailro/EscapeFromTarkov-Trainer#66]
Hello, I’m a little white who doesn’t understand the code at all. When I open Installer.exe, the program will crash. When I open it in cmd, he says that the game cannot be found, and then I try to install it manually, but find I can’t find the NLog.EFT.Trainer.dll file, what should I do?

**Comment by KoiPanda** [comment]
Any instructions would be helpful for me too :)

**Comment by wolfgang-WY** [comment]
It would be better you could use the Universal Installer. 
Also the Universal Installer link in readme.md is broken 

https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-1.2

**Comment by sailro** [comment]
Thanks @wolfgang-WY, I just fixed the link.

**Comment by voodabass** [comment]
> 
> 
> Hello, I’m a little white who doesn’t understand the code at all. When I open Installer.exe, the program will crash. When I open it in cmd, he says that the game cannot be found, and then I try to install it manually, but find I can’t find the NLog.EFT.Trainer.dll file, what should I do?

same for me .

**Comment by sailro** [comment]
Everything is documented here:
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/installer-1.2
