### ISSUE TITLE
WallShoot disregarding PMC armor

### ISSUE THREAD

**Issue by bvparekh** [sailro/EscapeFromTarkov-Trainer#67]
Hi Sailro,

Hope you are well. I recently updated your trainer on my SPT-AKI 12893 installation. Right after that, I started getting one shot by 9mm AP6.3 to thorax with Slick armor and it happened on about 6 trial raids that I did on factory where, regardless of the armor, I was getting one shot. It was around this time that I, also, realized that I could shoot through the walls (I had not enabled that option and did not know that this existed in your trainer); So I came back to Github and read through the description. I realized that wallshoot was ON by default. The very next game, I disable wallshoot and viola, everything was back to normal and behaving how it should be behaving. 

The default Wallshoot ON is disregarding PMC armor as well and so any AI on the map can shoot you with the worst ammo and the PMC will die as if he did not have any armor on. I wanted to flag it to you in case you were not aware of this issue.

Best,

**Comment by sailro** [comment]
Ah good catch :) I'm going to have a look at this issue.

Thanks!

**Comment by sailro** [comment]
This should be fixed now:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/6efd73a656f65ebf3d362a9e0ee3333fbc154daf

Could you give it a try?

Thanks!

**Comment by bvparekh** [comment]
Thanks Sailro - I will try it out this evening and let you know.

**Comment by bvparekh** [comment]
Sailro - Sorry for the delay in posting an update. I did try the updated trainer and the problem seems to be resolved. One thing I am noticing is that using the in-game ` to turn it off does not work. Once turned ON, it is only turning off once I restart the SPT-AKI server. Do take a look at it when you have time. Thank you.
