### ISSUE TITLE
Where should I make a trainer.ini file?

### ISSUE THREAD

**Issue by Razatop** [sailro/EscapeFromTarkov-Trainer#7]
For some reason the game isn't recognizing save or load, I'm guessing cause there is no trainer.ini file. Where should I go to create one. This is for SPT by the way. Thanks!

**Comment by sailro** [comment]
You are probably using a pre-compiled release ? I only added save/load support in the 'main'

**Comment by Razatop** [comment]
I'm just using the latest release that you posted 3 days ago it says. Is that the wrong thing? New to github sorry.

**Comment by sailro** [comment]
No worries. I'm contributing to the repo quite often, so precompiled releases do not contain all the news. That's exactly the case for the save/load feature.

**Comment by Razatop** [comment]
Well then I'm very excited to see that feature added and where you take this fun little project, thank you for getting back to me. Looking forward for the next release!

**Comment by sailro** [comment]
Just updated this one with the latest bits:
https://github.com/sailro/EscapeFromTarkov-Trainer/releases/tag/0.12.9.10532

Make sure you are on EFT 0.12.9.10532
