### ISSUE TITLE
SKP-AKI install

### ISSUE THREAD

**Issue by bobstar3233** [sailro/EscapeFromTarkov-Trainer#70]
Hey I'm trying to install to SPT-AKI 2.0 RC1 but the installer finishes when I launch the game it doesn't activate or none of the keybinds work, nor is the tainer.ini file in the Documents folder.

also when I try to compile myself with VS 2019 it doesn't compile 

Main error
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'Assembly-CSharp' with identity 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'	NLog.EFT.Trainer	C:\Battlestate Games\AKI 2.0\EscapeFromTarkov-Trainer-master\CSC	1	Active

Warning

Severity	Code	Description	Project	File	Line	Suppression State
Warning		Found conflicts between different versions of "Newtonsoft.Json" that could not be resolved.
There was a conflict between "Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" and "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed".
    "Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" was chosen because it was primary and "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" was not.
    References which depend on "Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" [C:\Program Files\IIS\Microsoft Web Deploy V3\Newtonsoft.Json.dll].
        C:\Program Files\IIS\Microsoft Web Deploy V3\Newtonsoft.Json.dll
          Project file item includes which caused reference "C:\Program Files\IIS\Microsoft Web Deploy V3\Newtonsoft.Json.dll".
            Newtonsoft.Json
    References which depend on "Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" [C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed\Newtonsoft.Json.dll].
        C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll
          Project file item includes which caused reference "C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll".
            Assembly-CSharp	NLog.EFT.Trainer

**Comment by sailro** [comment]
What is your EFT version?

**Comment by bobstar3233** [comment]
0.12.11.2.14002

**Comment by bobstar3233** [comment]
when i install to SPT 1.5.1 it recognises it and asks if I have done a first run but doesn't with 2.0 RC1

**Comment by bobstar3233** [comment]
Installer PowerShell output when removing and reinstalling the trainer


PS C:\Users\jorda\Downloads> .\Installer.exe uninstall
-=[ EscapeFromTarkov-Trainer Universal Installer ]=-

Target EscapeFromTarkov (0.12.11.14002) in C:\Battlestate Games\AKI 2.0.
Removed NLog.EFT.Trainer.dll in C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed.
Removed outline in C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data.
Unpatched NLog.dll.nlog in C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed.
PS C:\Users\jorda\Downloads> .\Installer.exe install
-=[ EscapeFromTarkov-Trainer Universal Installer ]=-

Target EscapeFromTarkov (0.12.11.14002) in C:\Battlestate Games\AKI 2.0.
Compilation succeded for master branch.
Created NLog.EFT.Trainer.dll in C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed.
Created outline in C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data.
Patched NLog.dll.nlog in C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data\Managed.
PS C:\Users\jorda\Downloads>

**Comment by sailro** [comment]
I'm using `0.12.11.14002` with `SPT-AKI 2.0 RC1` on my box. Indeed we do not see that spt-aki is installed (but it is working as expected if you ran the game once).

I'm going to have a look.

**Comment by sailro** [comment]
note: it is expected to not have a `trainer.ini`, it will be auto-created when using `save`. But at least you should be able to do like `status` and see enabled features.

**Comment by bobstar3233** [comment]
when using any commands it doesnt reconise ill do a screen recording and upload it for you in a few minutes

**Comment by bobstar3233** [comment]
https://youtu.be/JOqLa-NmSGQ

its uploading and processing now should be watchable within like 10 mins tops

**Comment by sailro** [comment]
I updated the installer here:
https://github.com/sailro/EscapeFromTarkov-Trainer/releases

but I don't think this is linked to your issue.

What do you see in `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt` ?

**Comment by bobstar3233** [comment]
[output_log.txt](https://github.com/sailro/EscapeFromTarkov-Trainer/files/7192714/output_log.txt)

**Comment by sailro** [comment]
In the output_log.txt I can see references to `E:/AKI 2.0/EscapeFromTarkov_Data` but in the installer screenshot you have I can see  `C:\Battlestate Games\AKI 2.0\EscapeFromTarkov_Data`. We are not using the same drive !?

Are you sure you are running the proper EFT instance ? :) Could you double check you links.

I guess you are running the `E:\` game executable and that's why the trainer is not enabled. You need to run the spt-aki server/launcher located in `C:\Battlestate Games\AKI 2.0`

**Comment by bobstar3233** [comment]
Yup it was me forgetting to update the launcher to the new path, my fault
