### ISSUE TITLE
Installer not working (Or i'm doing something wrong)

### ISSUE THREAD

**Issue by xavieraiden** [sailro/EscapeFromTarkov-Trainer#72]
Hi, I've been following the instructions for the automatic installer and whenever I start it through CMD it opens for a few frames, shows the blue text, and then closes. I have checked and am using the version mentioned (2.0.0 RC1)

I would try to use Visual studio to compile the source code but I want to try and sort this out first.

Any help is appreciated.

Edit: I've just noticed that the normal install of Tarkov would be in a folder called "Battlestate games" but mine is just installed in the "Games" folder in C drive, if this is the issue is there a way to change what folder the installer searches for the game? I'll try and copy my install of Tarkov to a folder of the same name, and see if it works then, If it does I'll close the issue.

Edit 2: Making a new folder didn't work.

**Comment by sailro** [comment]
Could you give the output of the installer?

**Comment by xavieraiden** [comment]
> Could you give the output of the installer?

It closes too fast for me to get a screenshot, but it closes just after showing the light blue text that can be seen in the installation tutorial 
Image of that can be found here ---> https://ibb.co/hmF9Vz1

**Comment by sailro** [comment]
"I've been following the instructions". yes sure.

Open a cmd prompt, then run the installer.exe from the command prompt.

As already explained many times, you can also pass a custom installation path on the commande line: installer.exe "C:\Program Files\EFT", given the installer is probably unable to find your EFT installation.

**Comment by xavieraiden** [comment]
> "I've been following the instructions". yes sure.
> 
> Open a cmd prompt, then run the installer.exe from the command prompt.
> 
> As already explained many times, you can also pass a custom installation path on the commande line: installer.exe "C:\Program Files\EFT", given the installer is probably unable to find your EFT installation.

So far I've just been using these commands to install
`cd C:\Users\Xavier\Desktop\
start installer.exe`
With the custom installation path, would the command be: `start installer.exe C:\Games` ?

**Comment by xavieraiden** [comment]
I've just gotten it working. 
the command for me was 
`start installer "C:\Games\Escape from Tarkov"`
