### ISSUE TITLE
BUG - ESP not showing containers after trainer updates

### ISSUE THREAD

**Issue by ShadoweCZ** [sailro/EscapeFromTarkov-Trainer#73]
Hello, 

i have encountered some weird behavior when im tracking items 
i ahve set the trainer.ini to work in 30m radius and my goal is to show every item AND container around 

1) there (as far as i know) is no way to just track every item / container with just single command
2) when i name itemms i want to be tracked, they even show when they are inside containers on the ESP 
3) when i name containers it sometimes shows containers (aka Safe shows Safe on esp no matter if its full or empty)
4) when i search for whole alphabet it shows all items that are on teh ground but NOT in containers
4) when i try to name everything including containers it WONT show any containers at all 

here is what i did hoping for ESP for all items and containers
```
EFT.Trainer.Features.LootItems.CacheTimeInSec=1.0
EFT.Trainer.Features.LootItems.Color=[0.55,0.42,0.0,1.0]
EFT.Trainer.Features.LootItems.Enabled=true
EFT.Trainer.Features.LootItems.Key="F2"
EFT.Trainer.Features.LootItems.MaximumDistance=30.0
EFT.Trainer.Features.LootItems.SearchInsideContainers=true
EFT.Trainer.Features.LootItems.SearchInsideCorpses=true
EFT.Trainer.Features.LootItems.TrackedNames=["Wooden","Weapon","Tool","Sport","Safe","crate","suitcase","PC","Med","Jacket","Drawer","Dead","stash","register","loot","box","container","a","e","i","o","u","y","x","-","0","1","2","3","4","5","6","7","8","9","q","w","r","t","p","s","d","f","g","h","j","k","l","z","c","v","b","n","m"]
```
problem: only shows items that are on the ground and not a single container or "item (inside container)"

Is there any chance to get some update that would add some new parameters for tracking loot ?? 
```
EFT.Trainer.Features.LootItems.ShowAllLoot
EFT.Trainer.Features.LootItems.ShowContainers
EFT.Trainer.Features.LootItems.ContainerColor
EFT.Trainer.Features.LootItems.HideEmptyContainers
EFT.Trainer.Features.LootItems.ContainerMaximumDistance
```

**Comment by sailro** [comment]
1. No but it is easy to do, but this will clutter the display as hell.
2. Well this is expected. Set `EFT.Trainer.Features.LootItems.SearchInsideContainers=false` if you don't want that.
3. Yes this is by design for now.
4. That is strange. Could you give an exact example?
5. I have to double check that.

This feature was initialy made to tracker 'items'.

For containers, we have `stash` (well only for buried barrel cache and ground cache, but that could easily be extended to all containers)

Thanks!

**Comment by ShadoweCZ** [comment]
i just installed nev version with AKI 2.0.0 (before i was using RC1 version) and i have to say that everything works perfectly 
so idk if it was just the RC1 version or you did something :)

**Comment by ShadoweCZ** [comment]
ok so after updating from 1.3 to 1.4 i got the same problem with containers not showing

could it be because i have updated the trainer by just reinstalling ?? if so can you make it so the installer will first uninstall any old version of the trianer ?

**Comment by ShadoweCZ** [comment]
UPDATE 
i have uninstalled the trainer
installed it again (1.5) 

stil ldont see any containers or bodies
all i see is free loot on teh ground

**Comment by ShadoweCZ** [comment]
so it has nothing to do with updates but with item weights being zero thanks to mods 
aka https://github.com/sailro/EscapeFromTarkov-Trainer/issues/85 

im closing it here
