### ISSUE TITLE
this will work with 0.12.11.2.14290?

### ISSUE THREAD

**Issue by Labirint69** [sailro/EscapeFromTarkov-Trainer#74]
since the new 2.0 version is using this version, plus i have zero knowledge with VS, so the automatic version will do the work without needing me for anything complex?

Edit: Yeah sorry talking about SPT-AKI 2.0.0

**Comment by ShadoweCZ** [comment]
i will just add he is talking about SPT-AKI 2.0.0
i cannot say yes or no but it works with the 2.0.0 RC1 version so i would hope it will work

**Comment by Noahhhlmao** [comment]
For me, the installer works, but once I start my game, nothing happens. I'm assuming it will just need an update, but that could just be on my side, any help is appreciated!

**Comment by sailro** [comment]
I'm going to have a look

**Comment by Billybishop** [comment]
I can confirm the hook is working for me with Tarkov 0.12.11.2.14290 and SPT-AKI v2.0.0-RC1

**Comment by Noahhhlmao** [comment]
hmm, ok, it may be an issue on my side, do you know why the trainer wouldn't load after running the installer? I may have just missed something.

**Comment by sailro** [comment]
it is working properly for `SPT-AKI 2.0.0 final` and `0.12.11.14290` 👍 

![image](https://user-images.githubusercontent.com/638167/134398249-ebbd3acc-6768-44de-8e42-90b06da01de2.png)

![image](https://user-images.githubusercontent.com/638167/134398435-34154124-5308-4a40-9265-7791f334234f.png)

![image](https://user-images.githubusercontent.com/638167/134398478-a735c79d-8e0e-4543-86ee-95d4021d8f46.png)

**Comment by sailro** [comment]
> hmm, ok, it may be an issue on my side, do you know why the trainer wouldn't load after running the installer? I may have just missed something.

Are you sure you are using the proper EFT instance? a user just had his issue, and forgot to update links to server/launcher.

Show us your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt`

**Comment by Labirint69** [comment]
ok, will test eveything today, just wanted to make sure before i screw things up, thank you very much you all

**Comment by Noahhhlmao** [comment]
> > hmm, ok, it may be an issue on my side, do you know why the trainer wouldn't load after running the installer? I may have just missed something.
> 
> Are you sure you are using the proper EFT instance? a user just had his issue, and forgot to update links to server/launcher.
> 
> Show us your `%LOCALAPPDATA%Low\Battlestate Games\EscapeFromTarkov\output_log.txt`

I am checking to make sure i have the right eft instance, ill let you know what i see

**Comment by sailro** [comment]
Look for this error (you can always find it):

`Fallback handler could not load library C:/Battlestate Games/sptarkov/EscapeFromTarkov_Data/Mono/data-000001F57A9B85C0.dll
Fallback handler could not load library C:/Battlestate Games/sptarkov/EscapeFromTarkov_Data/Mono/data-000001F57B2320A0.dll
Fallback handler could not load library C:/Battlestate Games/sptarkov/EscapeFromTarkov_Data/Mono/data-000001F55F504E00.dll
Fallback handler could not load library C:/Battlestate Games/sptarkov/EscapeFromTarkov_Data/Mono/data-000001F57B74B010.dll
`

=> you are running `C:/Battlestate Games/sptarkov`

**Comment by Noahhhlmao** [comment]
You were right, I had the wrong eft instance being loaded, I have fixed it and the hook works perfectly now, thanks for the help :)

**Comment by sailro** [comment]
Ok great. I will add a troubleshooting section, given it seems to be a thing.
