### ISSUE TITLE
ENHANCEMENT - item tracking text

### ISSUE THREAD

**Issue by ShadoweCZ** [sailro/EscapeFromTarkov-Trainer#79]
Hello, 

currently if you track multiple items in 1 container / body, its all written in the same position making it unreadable 
![image](https://user-images.githubusercontent.com/30881363/134842405-64043a8c-ce44-4716-a109-d6794539e947.png)

what should be changed is how text behaves in that situation by making it being writen as a list with each item on new line
Example : 
![image](https://user-images.githubusercontent.com/30881363/134816485-0d339475-7cc4-4963-ae16-9770dac50c59.png)

also being able to alert the text itself (size, color etc) would be great addition, the "track name" command could be expanded with those additional (but not mandatory) properties so it could result in "track name [color] size ....."

**Comment by ByYasin** [comment]
of course.

**Comment by sailro** [comment]
Worked on that and implemented auto-grouping and auto-newline:

See, one item found in dead scav:
![image](https://user-images.githubusercontent.com/638167/135155363-2d41fd30-ec3b-47dc-8169-351d5a107704.png)

When several items are found: auto-grouping per container, +newline for each item:
![image](https://user-images.githubusercontent.com/638167/135155526-f47b7c91-2cc5-404a-a359-099dbd98c1e4.png)

In-game:
![image](https://user-images.githubusercontent.com/638167/135155620-eec44b44-78c0-46f6-a306-c69a42fc6ead.png)

This should help removing a good amount of clutter.

**Comment by sailro** [comment]
For reference:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/26db781eb58895e4de74ede7877028c0e9384067

**Comment by sailro** [comment]
Ok so after grouping, I improved custom colors for tracking.

Now you can do like:
`track blood red`
`track alk blue`
`track action [1,1,1,1]`

![image](https://user-images.githubusercontent.com/638167/135521973-c82d71ee-4608-4f26-aab6-6fede0e00cc8.png)

It will show the color as well in the tracklist:
![image](https://user-images.githubusercontent.com/638167/135522074-5476e090-ad87-4a37-a797-5310c47fb87c.png)

Color names are Unity well known colors (see static properties section):
https://docs.unity3d.com/ScriptReference/Color.html

Or custom rgba-float  color like we use in the trainer.ini. So red is [1,0,0,1], white is [1,1,1,1]

You can do as well `track *` to display all loot, but that's a bit cluttered :)
