### ISSUE TITLE
Salut :) 

### ISSUE THREAD

**Issue by Queenofx** [sailro/EscapeFromTarkov-Trainer#80]
Merci d’abord pour ton boulot ! 

J'ai cependant un problème, je n'arrive pas a installer le trainer que ce soit via l'installer.bat qui se lance et se ferme aussi tot, ou bien manuelle ou ou, il ne se passe rien in game ? J'ai la version aki 2.0.0 ? 

Merci encore !

**Comment by sailro** [comment]
installer.exe "C:\Ton\Repertoire\D'installation\de\EFT"

**Comment by Queenofx** [comment]
![okkk](https://user-images.githubusercontent.com/91037123/134960106-fdfb7536-36f6-4d3c-86fe-627ad40c9369.png)

Comme ceci ? C'est pourtant la que je l'ai mis initialement :m

**Comment by sailro** [comment]
- re-telecharge l'installeur (je viens de faire une mise à jour).
- re-copie le dans ton répertoire de EFT
- lance le et ça devrait marcher
