### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by RGOace** [sailro/EscapeFromTarkov-Trainer#81]
Hello, I'm facing this error while I'm installing the trainer to my SPT. I really have no idea where to begin, any pointers that you can give to solve this issue?
![Could not create SSL TLS secure channel](https://user-images.githubusercontent.com/90565331/135080512-18f5cd4f-5ab9-4bac-8f6a-0e919255a6ec.jpg)

**Comment by RGOace** [comment]
> 
> 
> What is your OS ? (I'm on Windows 10)
> 
> I guess you have an old .NET version installed. Indeed with like 4.5 and earlier SSL 3.0 and TLS 1.0 are only supported. With recent versions you should have newer protocols like TLS 1.1 and TLS 1.2.
> 
> Could you try to install .NET 4.8 ? https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer

Thank you for the fast reply. I'm using Windows 7 64bit.

I have tried installing .NET 4.8 but the problem persists. Is it an OS issue?

**Comment by RGOace** [comment]
Hi Sailro, as you have said, I needed to update my protocols to TLS 1.2. and I did. It works. 
I tinkered with my registry editor a bit. The catch is, I can't log in to my Steam account. 

Oh well, as long as your trainer works.
Thanks a lot for your help, now I just need to figure out how to fix my connection to Steam.

**Comment by sailro** [comment]
How did you manage to "update to TLS 1.2" ?

**Comment by riQQ** [comment]
Creating / setting the following registry key works should be enough on Windows 7:
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client`
`DisabledByDefault` of type `REG_DWORD` with Value 0

**Comment by RGOace** [comment]
> 
> 
> How did you manage to "update to TLS 1.2" ?
> 
> Perhaps using this: https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392
> 
> is better than messing with the registry :)

Hey Sailro, sorry for the very late reply. So, based on what riQQ said:

> 
> 
> Creating / setting the following registry key works should be enough on Windows 7: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client` `DisabledByDefault` of type `REG_DWORD` with Value 0

I pretty much did that.

Thanks a lot with your help. Your trainer work wonders!

**Comment by Hasji** [comment]
.NET Framework 4.8 или более позднее обновление уже установлены на этом компьютере.
![image](https://github.com/sailro/EscapeFromTarkov-Trainer/assets/81190903/296a9a55-a7e5-498a-be2e-d314a8d0914a)
and what do in this situation?
