### ISSUE TITLE
Installer crashing 

### ISSUE THREAD

**Issue by Joemorgan21** [sailro/EscapeFromTarkov-Trainer#82]
Hi,
Hate to be an annoyance but I've tried and failed to manually install the trainer because plainly I am dumb but every time I use the installer it crashes after i enter "y" command to install the trainer. It successfully compiles the trainer but it seems it cannot get any further. 
Can anybody run me through it?
thanks 
![image_2021-09-28_222656](https://user-images.githubusercontent.com/86241118/135168100-5465c6ef-b2ba-497d-ac49-e0ba9b81d3de.png)

**Comment by sailro** [comment]
Could you try to run the installer from a command prompt, instead of double-clicking on the exe file ? (given it's a console application). So we can see all messages.

I'm not even sure it's "crashing", just when the job is finished it's closing.

**Comment by sailro** [comment]
Please use the latest installer. I just bumped the version.
