### ISSUE TITLE
Wallshoot will make the game stutter

### ISSUE THREAD

**Issue by nos4r3** [sailro/EscapeFromTarkov-Trainer#84]
I don't use this option it feel too overpowered but i will report it anyway in case anyone face this problem and don't know what cause it i come back to play SPT Tarkov when 12.11.2.14290 update install trainer and this option activate by default 

When playing i found stutter problem first i though it was a mod fin ai mod or spawn mod something like that i remove the mod one by one but nothing fix stutter problem then i think it probably trainer try disable loot item quest nothing happen then wallshoot option and the stutter is gone

Also if you ever make ESP into a box like other suggestion please don't remove the current cham one make it an option instead because i use similar trainer before 2D ESP dropping fps really hard when it using in SPT-Aki ( probably AI )

**Comment by sailro** [comment]
Should be a lot better with this.

https://github.com/sailro/EscapeFromTarkov-Trainer/commit/89534e4e2657df763ac854771aac662825c14e89

Do not forget to update your trainer.ini as well:

` EFT.Trainer.Features.WallShoot.CacheTimeInSec=5.5`
