### ISSUE TITLE
Item ESP not working correctly

### ISSUE THREAD

**Issue by Timoros98** [sailro/EscapeFromTarkov-Trainer#85]
Am using SPT-AKI 2.0.1 version

1. The "List" command only returns EUR,USD,RUB
2. The tracking is working only for loose items on the ground and not in containers!

The only tracking items in containers are the EUR,USD,RUB

Attaching images with the issues

![2021-10-07 18-27 _58 4, 1 5, 20 0_0 0, -0 6, 0 0, 0 8 (2)](https://user-images.githubusercontent.com/17567930/136416022-0c449f1d-d25d-43c3-bfa4-9e0a8c854f96.png)

![2021-10-07 18-27 _58 4, 1 5, 20 0_0 0, -0 6, 0 0, 0 8 (0)](https://user-images.githubusercontent.com/17567930/136416044-ee77d476-652f-46de-898e-a60926d1f51f.png)!

**Comment by Timoros98** [comment]
Ok so I will try 2.0.0 for now since is the same version of tarkov!
When do you planning to upgrade to 2.0.1?

**Comment by Timoros98** [comment]
I disabled stamina from the other mod but still not working i will try disable one by one untill i have nothing changed from the other mod and if that's not working then the mod itself has something to do with it

**Comment by sailro** [comment]
Good catch.

https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Extensions/ItemExtension.cs#L23

Yes  we are filtering all items without weight.

**Comment by Timoros98** [comment]
> > Ah great.
> > 
> > @ShadoweCZ are you using extra mods like this?
> 
> yes, 
> and i also had the weight set to 0 so i will change and try 
> ![image](https://user-images.githubusercontent.com/30881363/136457699-11e767f2-d81e-482b-9cb8-27ccf3cf446c.png)
> 
> so my problem https://github.com/sailro/EscapeFromTarkov-Trainer/issues/73 
> of not seeing items was caused because they had no weight ? 
> 
> 

There is a very high possibilty that this is your problem too try removing the mod that make the items weightless and try again!

**Comment by sailro** [comment]
Ok great. Perhaps I have to change my strategy on my side as well to prevent that
