### ISSUE TITLE
Question about wallhack colors 

### ISSUE THREAD

**Issue by Cherrytr33** [sailro/EscapeFromTarkov-Trainer#88]
Hey thanks for the trainer !! in 1.5.1 i got more then one color ESP in 2.0 everything is red (scav boss players bots) i wonder if i do something wrong ? Thanks !

**Comment by sailro** [comment]
Thanks, and what is the file size of your `EscapeFromTarkov_Data\outline` file ? This is the shader we use for coloring players. Perhaps something altered the file. Mine is 13.6 KB (13,943 bytes).

**Comment by Cherrytr33** [comment]
13,6 kB (13.943 bytes) i got both version on my computer 1.5.1 and 2.0 never opened  1.5.1 after installing 2.0

**Comment by Cherrytr33** [comment]
i will delete both and reinstall 2.0 when i can and report if it still show red only thanks for the help

**Comment by sailro** [comment]
Yep, let's try that, first time I'm seeing this.
