### ISSUE TITLE
Can we track by item ID?

### ISSUE THREAD

**Issue by megamango** [sailro/EscapeFromTarkov-Trainer#89]
Right now you have to track by the thumbnail name so the Green Keycard is simply "Green", and this causes Green Ice to show up for instance.  "RR" for the Ice pick tracks Herring.  "MedCase" tracks the orange doctor bag container and not the inventory container.  I would appreciate it if we could track by item ID, or the full name, as those are more specific.

**Comment by sailro** [comment]
Yes this should be easy. For now everything is using item "shortname" given:
- this is what you see in the inventory
- it's compact so well suited for display

Let me think how we can do that without breaking what we have currently.

**Comment by sailro** [comment]
I think new commands like `trackr` or `tracksr` should help here.

**Comment by sailro** [comment]
@megamango you can now track by item ID.

See:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/124#issuecomment-1031937651

**Comment by megamango** [comment]
Beautiful. Thank you
