### ISSUE TITLE
Can you get banned from this?

### ISSUE THREAD

**Issue by alexjshepler** [sailro/EscapeFromTarkov-Trainer#9]
Like, I know you can get banned for cheating/hacking but is this detectable?

**Comment by sailro** [comment]
Yes, BattlEye will probably catch the extra assembly load (NLog.EFT.Trainer).

**Comment by alexjshepler** [comment]
Have you tested it on your account? And have you gotten banned from it yet?

**Comment by sailro** [comment]
Yes
