### ISSUE TITLE
Hit marker feature & floating damage numbers

### ISSUE THREAD

**Issue by Billybishop** [sailro/EscapeFromTarkov-Trainer#91]
I finished implementing this last night and decided to share it with the boys on UC first. I miss the days of Gamedeception..... Anyway, hopefully you can implement this.

https://www.unknowncheats.me/forum/3270961-post5072.html

**Comment by sailro** [comment]
I will revisit this one given I added support for hooking existing EFT code.

We just need a new hook comparable to this one:
https://github.com/sailro/EscapeFromTarkov-Trainer/blob/master/Features/Health.cs#L22

We have bodyPart, damage, damageInfo, IHealthController, player so we should be good.

We can even add Hit sounds as well

**Comment by sailro** [comment]
@Billybishop I added hit markers, without using Reflection or scrambled classes, so this should work across versions:

![Screenshot 2022-02-01 20 48 08](https://user-images.githubusercontent.com/638167/152043291-c2dfbd46-b508-47d2-881c-a3dd325d19ee.png)

See implementation here:
https://github.com/sailro/EscapeFromTarkov-Trainer/commit/df5e3d77a39269e140a5c4f4cde1332ac4787383

Thank you for the prototype!
