### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by Cavanite** [sailro/EscapeFromTarkov-Trainer#92]
![image](https://user-images.githubusercontent.com/38662369/138093752-ea071205-d0d8-4a75-a36e-dbf088d80a37.png)
I cannot combile the trainer

**Comment by sailro** [comment]
Fixed here: https://github.com/sailro/EscapeFromTarkov-Trainer/commit/9b20cb257dc4813baee0788b6836f76b5fb94ab0

You should be able to install now.
